// Minton_v10.1.0/Next.js/TS/src/app/(admin)/widgets/StatisticsChartWidget2.tsx
"use client"
import React from "react";
import { ApexOptions } from "apexcharts";
import ReactApexChart from "react-apexcharts";

// components
import { ChartStatistics } from "@/components";

const StatisticsChartWidget2 = () => {
  const options: ApexOptions = {
    chart: {
      type: "line",
      toolbar: {
        show: false,
      },
      sparkline: {
        enabled: true,
      },
    },
    stroke: {
      curve: "straight",
      width: [1],
    },
    grid: {
      padding: {
        left: -9,
        right: 0,
      },
    },
    fill: {
      type: "solid",
      opacity: [0.3, 0.3],
    },
    colors: ["#3bafda", "#1abc9c"],
    xaxis: {
      labels: {
        show: false,
      },
      axisTicks: {
        show: false,
      },
    },
    yaxis: {
      labels: {
        show: false,
      },
    },
    legend: {
      show: false,
    },
    tooltip: {
      fixed: {
        enabled: false,
      },
      x: {
        show: false,
      },
      y: {
        title: {
          formatter: (seriesName: string) => {
            return "";
          },
        },
      },
      marker: {
        show: false,
      },
    },
  };

  const series = [
    {
      type: "area",
      data: [0, 23, 43, 35, 44, 45, 56, 37, 40],
    },
    {
      type: "area",
      data: [25, 23, 26, 24, 25, 32, 30, 24, 19],
    },
  ];

  return (
    <div className="card">
      <div className="card-body">
        <h4 className="header-title mb-3">Total Revenue</h4>

        <div className="widget-chart text-center">
          <ReactApexChart
            type="line"
            options={options}
            series={series}
            height={165}
            className="apex-charts mt-0"
          />

          <div className="row mt-3">
            <div className="col-4">
              <ChartStatistics title="Target" stats="$1000" />
            </div>
            <div className="col-4">
              <ChartStatistics title="Last week" stats="$523" />
            </div>
            <div className="col-4">
              <ChartStatistics title="Last Month" stats="$965" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default StatisticsChartWidget2;

// Minton_v10.1.0/Angular/Minton/src/app/views/apps/widgets/components/statistics-chart-widget2/statistics-chart-widget2.component.ts
import { Component } from '@angular/core'
import type { ChartOptions } from '@common/apexchart.model'
import { currency } from '@common/constants'
import { NgApexchartsModule } from 'ng-apexcharts'

@Component({
  selector: 'statistics-chart-widget2',
  standalone: true,
  imports: [NgApexchartsModule],
  templateUrl: './statistics-chart-widget2.component.html',
  styles: ``,
})
export class StatisticsChartWidget2Component {
  currency = currency

  sparkline1Chart: Partial<ChartOptions> = {
    chart: {
      type: 'line',
      height: 165,
      toolbar: {
        show: false,
      },
      sparkline: {
        enabled: true,
      },
    },
    series: [
      {
        type: 'area',
        data: [0, 23, 43, 35, 44, 45, 56, 37, 40],
      },
      {
        type: 'area',
        data: [25, 23, 26, 24, 25, 32, 30, 24, 19],
      },
    ],
    stroke: {
      curve: 'straight',
      width: [1],
    },
    grid: {
      padding: {
        left: -9,
        right: 0,
      },
    },
    fill: {
      type: 'solid',
      opacity: [0.3, 0.3],
    },
    colors: ['#3bafda', '#1abc9c'],
    xaxis: {
      labels: {
        show: false,
      },
      axisTicks: {
        show: false,
      },
    },
    yaxis: {
      labels: {
        show: false,
      },
    },
    legend: {
      show: false,
    },
    tooltip: {
      fixed: {
        enabled: false,
      },
      x: {
        show: false,
      },
      y: {
        title: {
          formatter: (seriesName: string) => {
            return ''
          },
        },
      },
      marker: {
        show: false,
      },
    },
  }
}

<div class="card">
  <div class="card-body">
    <h4 class="header-title mb-3">Total Revenue</h4>

    <div class="widget-chart text-center">
      <div id="sparkline1" data-colors="#3bafda,#1abc9c">
        <apx-chart
          [chart]="sparkline1Chart.chart!"
          [series]="sparkline1Chart.series!"
          [stroke]="sparkline1Chart.stroke!"
          [grid]="sparkline1Chart.grid!"
          [fill]="sparkline1Chart.fill!"
          [colors]="sparkline1Chart.colors!"
          [xaxis]="sparkline1Chart.xaxis!"
          [yaxis]="sparkline1Chart.yaxis!"
          [legend]="sparkline1Chart.legend!"
          [tooltip]="sparkline1Chart.tooltip!"
        />
      </div>
      <div class="row mt-3">
        <div class="col-4">
          <p class="text-muted font-15 mb-1 text-truncate">Target</p>
          <h4>{{ currency }}1000</h4>
        </div>
        <div class="col-4">
          <p class="text-muted font-15 mb-1 text-truncate">Last week</p>
          <h4>{{ currency }}523</h4>
        </div>
        <div class="col-4">
          <p class="text-muted font-15 mb-1 text-truncate">Last Month</p>
          <h4>{{ currency }}965</h4>
        </div>
      </div>
    </div>
  </div>
</div>
