// Minton_v10.1.0/React.js/JS/src/app/(admin)/widgets/page.jsx
import Statistics from "./Statistics";
import Statistics2 from "./Statistics2";
import Statistics3 from "./Statistics3";
import ProfileCard from "./ProfileCard";
import WeatherWidget from "./WeatherWidget";
import StatisticsChartWidget2 from "./StatisticsChartWidget2";
import StatisticsChartWidget3 from "./StatisticsChartWidget3";
import StatisticsChartWidget4 from "./StatisticsChartWidget4";
import StatisticsChartWidget5 from "./StatisticsChartWidget5";
import StatisticsChartWidget6 from "./StatisticsChartWidget6";
import StatisticsChartWidget7 from "./StatisticsChartWidget7";

// components
import PageBreadcrumb from "@/components/PageBreadcrumb";
import StatisticsChartWidget from "@/components/StatisticsChartWidget";
import StatisticsWidget from "@/components/StatisticsWidget";
import Messages from "@/components/Messages";
import ChatList from "@/components/ChatList";
import TodoList from "@/components/TodoList";

// images
import user1 from "@/assets/images/users/avatar-1.jpg";
import user2 from "@/assets/images/users/avatar-2.jpg";
import user3 from "@/assets/images/users/avatar-3.jpg";
import user4 from "@/assets/images/users/avatar-4.jpg";

// dummy data
import { weather, chatMessages } from "./data";
import { Col, Row } from "react-bootstrap";
const Widgets = () => {
  return <>
      <PageBreadcrumb breadCrumbItems={[{
      label: "Components",
      path: "/apps/widgets"
    }, {
      label: "Widgets",
      path: "/apps/widgets",
      active: true
    }]} title={"Widgets"} />

      <Row>
        <Col xl={3} md={6}>
          <Statistics variant="success" description="Total Sales today" stats="2562" />
        </Col>
        <Col xl={3} md={6}>
          <Statistics variant="primary" description="Daily visitors" stats="5685" />
        </Col>
        <Col xl={3} md={6}>
          <Statistics variant="pink" description="Total Earning" counterOptions={{
          prefix: "$ "
        }} stats="12480" />
        </Col>
        <Col xl={3} md={6}>
          <Statistics variant="purple" description="Pending Orders" stats="62" />
        </Col>
      </Row>

      <Row>
        <Col xl={3} md={6}>
          <Statistics2 variant="success" description="Today's Visits" icon="mdi mdi-android-studio" stats="64570" />
        </Col>
        <Col xl={3} md={6}>
          <Statistics2 variant="primary" description="Total Revenue" icon="mdi mdi-amazon" stats="31570" />
        </Col>
        <Col xl={3} md={6}>
          <Statistics2 variant="danger" description="Today's Sales" icon="mdi mdi-apple" stats="280" />
        </Col>
        <Col xl={3} md={6}>
          <Statistics2 variant="purple" description="Conversion" icon="mdi mdi-barley" counterOptions={{
          suffix: "%",
          decimals: 2
        }} stats="0.16" />
        </Col>
      </Row>

      <Row>
        <Col xl={3} md={6}>
          <Statistics2 variant="info" description="Today's Visits" icon="mdi mdi-black-mesa" stats="23570" />
        </Col>
        <Col xl={3} md={6}>
          <Statistics2 variant="warning" description="Total Revenue" icon="mdi mdi-bullseye" stats="9654" />
        </Col>
        <Col xl={3} md={6}>
          <Statistics2 variant="dark" description="Today's Sales" icon="mdi mdi-cart" stats="965" />
        </Col>
        <Col xl={3} md={6}>
          <Statistics2 variant="pink" description="Conversion" icon="mdi mdi-clock" counterOptions={{
          suffix: "%",
          decimals: 2
        }} stats="0.65" />
        </Col>
      </Row>

      <Row>
        <Col xl={3} md={6}>
          <StatisticsChartWidget hasHeader title={"New Customers"} color={"#f05050"} data={58} stats={"268"} description={"Since last week"} />
        </Col>
        <Col xl={3} md={6}>
          <StatisticsChartWidget hasHeader title={"Online Orders"} color={"#675db7"} data={80} stats={"8715"} description={"Since last month"} />
        </Col>
        <Col xl={3} md={6}>
          <StatisticsChartWidget hasHeader title={"Revenue"} color={"#23b397"} data={77} stats={"$925"} description={"This week"} />
        </Col>
        <Col xl={3} md={6}>
          <StatisticsChartWidget hasHeader title={"Daily Average"} color={"#ffbd4a"} data={35} stats={"$78.58"} description={"Revenue today "} />
        </Col>
      </Row>

      <Row>
        <Col xl={3} md={6}>
          <StatisticsWidget icon="ri-stack-line" stats="865" title="Campaign Sent" trend={{
          value: "5.27%",
          title: "Since last month",
          icon: "mdi mdi-arrow-up-bold",
          variant: "success"
        }} />
        </Col>
        <Col xl={3} md={6}>
          <StatisticsWidget icon="ri-slideshow-2-line" stats="384" title="New Leads" trend={{
          value: "3.27%",
          title: "Since last month",
          icon: "mdi mdi-arrow-down-bold",
          variant: "danger"
        }} />
        </Col>
        <Col xl={3} md={6}>
          <StatisticsWidget icon="ri-hand-heart-line" stats="34521" title="Deals" trend={{
          value: "8.58%",
          title: "Since last month",
          icon: "mdi mdi-arrow-up-bold",
          variant: "success"
        }} />
        </Col>
        <Col xl={3} md={6}>
          <StatisticsWidget icon="ri-money-dollar-box-line" stats="89357" title="Booked Revenue" counterOptions={{
          prefix: "$"
        }} trend={{
          value: "34.61%",
          title: "Since last month",
          icon: "mdi mdi-arrow-up-bold",
          variant: "success"
        }} />
        </Col>
      </Row>

      <Row>
        <Col xl={3} md={6}>
          <ProfileCard avatar={user1} name="Chadengle" email="coderthemes@gmail.com" role="Admin" variant="warning" />
        </Col>
        <Col xl={3} md={6}>
          <ProfileCard avatar={user2} name="Tomaslau" email="coderthemes@gmail.com" role="User" variant="success" />
        </Col>
        <Col xl={3} md={6}>
          <ProfileCard avatar={user3} name="Stillnotdavid" email="coderthemes@gmail.com" role="Admin" variant="pink" />
        </Col>
        <Col xl={3} md={6}>
          <ProfileCard avatar={user4} name="Arashasghari" email="coderthemes@gmail.com" role="User" variant="info" />
        </Col>
      </Row>

      <Row>
        <Col xl={3} md={6}>
          <Statistics3 icon="mdi mdi-coffee" variant="primary" title="New User" stats="8541" trend={{
          value: "39% Up",
          variant: "success"
        }} />
        </Col>
        <Col xl={3} md={6}>
          <Statistics3 icon="mdi mdi-contrast-circle" variant="warning" title="New ORDERS" stats="6521" trend={{
          value: "56% Down",
          variant: "danger"
        }} />
        </Col>
        <Col xl={3} md={6}>
          <Statistics3 icon="mdi mdi-crown" variant="success" title="Bug Reports" stats="1452" trend={{
          value: "0%",
          variant: "info"
        }} />
        </Col>
        <Col xl={3} md={6}>
          <Statistics3 icon="mdi mdi-download" variant="pink" title="Total Downloads" stats="562" trend={{
          value: "39% Up",
          variant: "success"
        }} />
        </Col>
      </Row>

      {/* weather */}
      <Row>
        {(weather || []).map((item, index) => {
        return <Col xl={6} key={index}>
              <WeatherWidget item={item} />
            </Col>;
      })}
      </Row>

      <Row>
        <Col xs={12}>
          <h4 className="mb-3">Chart Widgets</h4>

          <Row>
            <Col xl={4}>
              <StatisticsChartWidget2 />
            </Col>
            <Col xl={4}>
              <StatisticsChartWidget3 />
            </Col>
            <Col xl={4}>
              <StatisticsChartWidget4 />
            </Col>
          </Row>

          <Row>
            <Col xl={4}>
              <StatisticsChartWidget5 />
            </Col>
            <Col xl={4}>
              <StatisticsChartWidget6 />
            </Col>
            <Col xl={4}>
              <StatisticsChartWidget7 />
            </Col>
          </Row>
        </Col>
      </Row>
      <Row>
        <Col xs={12}>
          <h4 className="mb-3">Chart Widgets</h4>
          <Row>
            <Col xl={4}>
              <Messages />
            </Col>
            <Col xl={4}>
              <ChatList title="Chat" messages={chatMessages} />
            </Col>
            <Col xl={4}>
              <TodoList addTodo={true} height={"310px"} />
            </Col>
          </Row>
        </Col>
      </Row>
    </>;
};
export default Widgets;

// Minton_v10.1.0/Angular/Minton/src/app/views/apps/widgets/widgets.component.ts
import { Component } from '@angular/core'
import { PageTitleComponent } from '@component/page-title.component'
import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap'
import { CountUpModule } from 'ngx-countup'
import { Stat2Component } from './components/stat2/stat2.component'
import { StatisticsChartWidgetComponent } from '@component/statistics-chart-widget/statistics-chart-widget.component'
import { StatisticsWidgetComponent } from '@component/statistics-widget/statistics-widget.component'
import { ProfileStatesComponent } from './components/profile-states/profile-states.component'
import { Stat3Component } from './components/stat3/stat3.component'
import { WeatherWidgetComponent } from './components/weather-widget/weather-widget.component'
import { weather } from './data'
import { StatisticsChartWidget3Component } from './components/statistics-chart-widget3/statistics-chart-widget3.component'
import { StatisticsChartWidget2Component } from './components/statistics-chart-widget2/statistics-chart-widget2.component'
import { StatisticsChartWidget4Component } from './components/statistics-chart-widget4/statistics-chart-widget4.component'
import { StatisticsChartWidget5Component } from './components/statistics-chart-widget5/statistics-chart-widget5.component'
import { StatisticsChartWidget6Component } from './components/statistics-chart-widget6/statistics-chart-widget6.component'
import { StatisticsChartWidget7Component } from './components/statistics-chart-widget7/statistics-chart-widget7.component'
import { InboxComponent } from './components/inbox/inbox.component'
import { ChatComponent } from './components/chat/chat.component'
import { TodoComponent } from './components/todo/todo.component'

@Component({
  selector: 'app-widgets',
  standalone: true,
  imports: [
    PageTitleComponent,
    NgbDropdownModule,
    CountUpModule,
    Stat2Component,
    StatisticsChartWidgetComponent,
    StatisticsWidgetComponent,
    ProfileStatesComponent,
    Stat3Component,
    WeatherWidgetComponent,
    StatisticsChartWidget2Component,
    StatisticsChartWidget3Component,
    StatisticsChartWidget4Component,
    StatisticsChartWidget5Component,
    StatisticsChartWidget6Component,
    StatisticsChartWidget7Component,
    InboxComponent,
    ChatComponent,
    TodoComponent,
  ],
  templateUrl: './widgets.component.html',
  styles: ``,
})
export class WidgetsComponent {
  breadCrumbItems = [
    { label: 'Components', path: '/apps/widgets' },
    { label: 'Widgets', path: '/apps/widgets', active: true },
  ]

  weather = weather
}

<app-page-title title="Widgets" [breadCrumbItems]="breadCrumbItems" />

<div class="row">
  <div class="col-xl-3 col-md-6">
    <div class="widget-simple text-center card">
      <div class="card-body">
        <h3 class="text-success mt-0"><span [countUp]="2562">2562</span></h3>
        <p class="text-muted mb-0">Total Sales today</p>
      </div>
    </div>
  </div>

  <div class="col-xl-3 col-md-6">
    <div class="widget-simple text-center card">
      <div class="card-body">
        <h3 class="text-primary mt-0"><span [countUp]="5685">5685</span></h3>
        <p class="text-muted mb-0">Daily visitors</p>
      </div>
    </div>
  </div>

  <div class="col-xl-3 col-md-6">
    <div class="widget-simple text-center card">
      <div class="card-body">
        <h3 class="text-pink mt-0">$ <span [countUp]="12480">12480</span></h3>
        <p class="text-muted mb-0">Total Earning</p>
      </div>
    </div>
  </div>

  <div class="col-xl-3 col-md-6">
    <div class="widget-simple text-center card">
      <div class="card-body">
        <h3 class="text-purple mt-0"><span [countUp]="62">62</span></h3>
        <p class="text-muted mb-0">Pending Orders</p>
      </div>
    </div>
  </div>
</div>

<widget-stat2 />

<div class="row">
  <div class="col-xl-3 col-md-6">
    <app-statistics-chart-widget
      [hasHeader]="true"
      [data]="58"
      [color]="'#f05050'"
      [stats]="268"
      title="New Customers"
      description="Since last week"
      [counterOptions]="{ startVal: 0, useGrouping: false }"
    />
  </div>

  <div class="col-xl-3 col-md-6">
    <app-statistics-chart-widget
      [hasHeader]="true"
      [data]="80"
      [color]="'#675db7'"
      [stats]="8715"
      title="Online Orders"
      description="Since last month"
      [counterOptions]="{ startVal: 0, useGrouping: false }"
    />
  </div>

  <div class="col-xl-3 col-md-6">
    <app-statistics-chart-widget
      [hasHeader]="true"
      [data]="77"
      [color]="'#23b397'"
      [stats]="925"
      title="Revenue"
      description="This week"
      [counterOptions]="{ prefix: '$', decimalPlaces: 2, useGrouping: false }"
    />
  </div>

  <div class="col-xl-3 col-md-6">
    <app-statistics-chart-widget
      [hasHeader]="true"
      [data]="35"
      [color]="'#ffbd4a'"
      [stats]="78.58"
      title="Daily Average"
      description="Revenue today"
      [counterOptions]="{ prefix: '$', decimalPlaces: 2, useGrouping: false }"
    />
  </div>
</div>

<div class="row">
  <div class="col-xl-3 col-md-6">
    <app-statistics-widget
      title="Campaign Sent"
      [stats]="865"
      [counterOptions]="{ startVal: '0' }"
      [trend]="{
        value: '5.27%',
        title: 'Since last month',
        icon: 'mdi mdi-arrow-up-bold',
        variant: 'success',
      }"
      icon="ri-stack-line"
    />
  </div>

  <div class="col-xl-3 col-md-6">
    <app-statistics-widget
      title="New Leads"
      [stats]="384"
      [counterOptions]="{ startVal: '0' }"
      [trend]="{
        value: '3.27%',
        title: 'Since last month',
        icon: 'mdi mdi-arrow-down-bold',
        variant: 'danger',
      }"
      icon="ri-slideshow-2-line"
    />
  </div>

  <div class="col-xl-3 col-md-6">
    <app-statistics-widget
      title="Deals"
      [stats]="34521"
      [counterOptions]="{ startVal: '0' }"
      [trend]="{
        value: '8.58%',
        title: 'Since last month',
        icon: 'mdi mdi-arrow-up-bold',
        variant: 'success',
      }"
      icon="ri-hand-heart-line"
    />
  </div>

  <div class="col-xl-3 col-md-6">
    <app-statistics-widget
      title="Booked Revenue"
      [stats]="89357"
      [counterOptions]="{ startVal: '0', prefix: '$' }"
      [trend]="{
        value: '34.61%',
        title: 'Since last month',
        icon: 'mdi mdi-arrow-up-bold',
        variant: 'success',
      }"
      icon="ri-money-dollar-box-line"
    />
  </div>
</div>

<div class="row">
  <div class="col-xl-3 col-md-6">
    <widget-profile-states
      avatar="assets/images/users/avatar-1.jpg"
      name="Chadengle"
      email="coderthemes&#64;gmail.com"
      role="Admin"
      variant="warning"
    />
  </div>

  <div class="col-xl-3 col-md-6">
    <widget-profile-states
      avatar="assets/images/users/avatar-2.jpg"
      name="Tomaslau"
      email="coderthemes&#64;gmail.com"
      role="User"
      variant="success"
    />
  </div>

  <div class="col-xl-3 col-md-6">
    <widget-profile-states
      avatar="assets/images/users/avatar-3.jpg"
      name="Stillnotdavid"
      email="coderthemes&#64;gmail.com"
      role="Admin"
      variant="pink"
    />
  </div>

  <div class="col-xl-3 col-md-6">
    <widget-profile-states
      avatar="assets/images/users/avatar-4.jpg"
      name="Arashasghari"
      email="coderthemes&#64;gmail.com"
      role="User"
      variant="info"
    />
  </div>
</div>

<div class="row">
  <div class="col-xl-3 col-md-6">
    <widget-stat3
      [variant]="'primary'"
      [title]="'New User'"
      [icon]="'mdi mdi-coffee'"
      [stats]="'8541'"
      [trend]="{ value: '39% Up', variant: 'success' }"
    />
  </div>

  <div class="col-xl-3 col-md-6">
    <widget-stat3
      [variant]="'warning'"
      [title]="'New Orders'"
      [icon]="'mdi mdi-contrast-circle'"
      [stats]="'6521'"
      [trend]="{ value: '56% Down', variant: 'danger' }"
    />
  </div>

  <div class="col-xl-3 col-md-6">
    <widget-stat3
      [variant]="'success'"
      [title]="'Bug Reports'"
      [icon]="'mdi mdi-crown'"
      [stats]="'1452'"
      [trend]="{ value: '0%', variant: 'info' }"
    />
  </div>

  <div class="col-xl-3 col-md-6">
    <widget-stat3
      [variant]="'pink'"
      [title]="'Total Downloads'"
      [icon]="'mdi mdi-download'"
      [stats]="'562'"
      [trend]="{ value: '39% Up', variant: 'success' }"
    />
  </div>
</div>

<div class="row">
  @for (item of weather; track $index) {
    <div class="col-xl-6">
      <weather-widget [item]="item" />
    </div>
  }
</div>

<div class="row">
  <div class="col-12">
    <h4 class="mb-3">Chart Widgets</h4>

    <div class="row">
      <div class="col-xl-4">
        <statistics-chart-widget2 />
      </div>

      <div class="col-xl-4">
        <statistics-chart-widget3 />
      </div>

      <div class="col-xl-4">
        <statistics-chart-widget4 />
      </div>
    </div>

    <div class="row">
      <div class="col-xl-4">
        <statistics-chart-widget5 />
      </div>

      <div class="col-xl-4">
        <statistics-chart-widget6 />
      </div>

      <div class="col-xl-4">
        <statistics-chart-widget7 />
      </div>
    </div>
  </div>
  <!-- end col-->
</div>

<div class="row">
  <div class="col-12">
    <h4 class="mb-3">Other Widgets</h4>

    <div class="row">
      <div class="col-xl-4">
        <widget-inbox />
      </div>

      <div class="col-xl-4">
        <widget-chat />
      </div>
      <!-- end col-->

      <div class="col-xl-4">
        <!-- Todo-->
        <widget-todo />
      </div>
    </div>
  </div>
  <!-- end col-->
</div>
