// Minton_v10.1.0/Next.js/TS/src/app/(admin)/ui/spinners/page.tsx
import React from "react";
import { Metadata } from "next";
import dynamic from "next/dynamic";
const ButtonSpinners = dynamic(() => import('./ButtonSpinners'))
import Spinner from "@/components/Spinner";

// components
import PageBreadcrumb from "@/components/PageBreadcrumb";

const colors: string[] = [
  "primary",
  "secondary",
  "success",
  "danger",
  "warning",
  "info",
  "light",
  "dark",
  "blue",
  "pink",
];

const BorderedSpinners = () => {
  return (
    <div className="card">
      <div className="card-body">
        <h4 className="header-title">Border spinner</h4>
        <p className="sub-header">
          Use the border spinners for a lightweight loading indicator.
        </p>
        <Spinner type="bordered" className="m-2" color="primary" />
      </div>
    </div>
  );
};

const GrowingSpinners = () => {
  return (
    <div className="card">
      <div className="card-body">
        <h4 className="header-title">Growing spinner</h4>
        <p className="sub-header">
          If you don’t fancy a border spinner, switch to the grow spinner. While
          it doesn’t technically spin, it does repeatedly grow!
        </p>
        <Spinner type="grow" color="success" />
      </div>
    </div>
  );
};

const Colors = () => {
  return (
    <div className="card">
      <div className="card-body">
        <h4 className="header-title">Colors</h4>
        <p className="sub-header">
          All standard visual variants are available for both animation styles
          by setting the <code>variant</code> property.
        </p>

        {(colors || []).map((color, index) => {
          return <Spinner key={index} type="bordered" className="m-2" color={color} />;
        })}
      </div>
    </div>
  );
};

const ColorGrowingSpinners = () => {
  return (
    <div className="card">
      <div className="card-body">
        <h4 className="header-title">Color Growing spinner</h4>
        <p className="sub-header">
          Here it is in blue, along with the supported variants.
        </p>
        {(colors || []).map((color, index) => {
          return (
            <Spinner key={index} className="m-2" type="grow" color={color} />
          );
        })}
      </div>
    </div>
  );
};

const AlignmentSpinners = () => {
  return (
    <>
      <div className="card">
        <div className="card-body">
          <h4 className="header-title">Alignment</h4>
          <p className="sub-header">
            Use flexbox utilities, float utilities, or text alignment utilities
            to place spinners exactly where you need them in any situation.
          </p>
          <div className="d-flex justify-content-center">
            <Spinner type="bordered"/>
          </div>
        </div>
      </div>
    </>
  );
};

const SpinnerPlacements = () => {
  return (
    <>
      <div className="card">
        <div className="card-body">
          <h4 className="header-title">Placement</h4>
          <p className="sub-header">
            Use <code>flexbox utilities</code>, <code>float utilities</code>, or{" "}
            <code>text alignment</code> utilities to place spinners exactly
            where you need them in any situation.
          </p>
          <div className="d-flex align-items-center">
            <strong>Loading...</strong>
            <Spinner type="bordered" className="ms-auto" />
          </div>
        </div>
      </div>
    </>
  );
};

const SpinnersSizes = () => {
  const sizes: ("lg" | "md" | "sm")[] = ["lg", "md", "sm"];

  return (
    <div className="card">
      <div className="card-body">
        <h4 className="header-title">Size</h4>
        <p className="sub-header">
          Add <code>size</code> attribute to make spinner with sizes including
          lg, md or sm.
        </p>
        <div className="row">
          {(sizes || []).map((size, index) => {
            return (
              <div key={index} className="col-lg-6">
                <Spinner type="bordered"
                  className="text-primary m-2"
                  color="primary"
                  size={size}
                />
                <Spinner
                  className="text-secondary m-2"
                  type="grow"
                  size={size}
                />
              </div>
            );
          })}
          <div className="col-lg-6">
            <Spinner type="bordered" className="spinner-border-sm m-2" />
            <Spinner type="grow" className="spinner-grow-sm m-2" />
          </div>
        </div>
      </div>
    </div>
  );
};


export const metadata: Metadata = {
  title: "Spinners"
}

const Spinners = () => {
  return (
    <React.Fragment>
      <PageBreadcrumb
        breadCrumbItems={[
          { label: "Base UI", path: "/ui/spinners" },
          { label: "Spinners", path: "/ui/spinners", active: true },
        ]}
        title={"Spinners"}
      />

      <div className="row">
        <div className="col-lg-6">
          <BorderedSpinners />
        </div>
        <div className="col-lg-6">
          <GrowingSpinners />
        </div>
      </div>

      <div className="row">
        <div className="col-lg-6">
          <Colors />
        </div>

        <div className="col-lg-6">
          <ColorGrowingSpinners />
        </div>
      </div>
      <div className="row">
        <div className="col-lg-6">
          <AlignmentSpinners />
        </div>
        <div className="col-lg-6">
          <SpinnerPlacements />
        </div>
      </div>

      <div className="row">
        <div className="col-lg-6">
          <SpinnersSizes />
        </div>
        <div className="col-lg-6">
          <ButtonSpinners />
        </div>
      </div>
    </React.Fragment>
  );
};

export default Spinners;

// Minton_v10.1.0/Angular/Minton/src/app/views/base-ui/spinners/spinners.component.ts
import { Component } from '@angular/core'
import { PageTitleComponent } from '@component/page-title.component'

@Component({
  selector: 'app-spinners',
  standalone: true,
  imports: [PageTitleComponent],
  templateUrl: './spinners.component.html',
  styles: ``,
})
export class SpinnersComponent {
  breadCrumbItems = [
    { label: 'Base UI', path: '/ui/spinners' },
    { label: 'Spinners', path: '/ui/spinners', active: true },
  ]
}

<app-page-title title="Spinners" [breadCrumbItems]="breadCrumbItems" />

<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <h4 class="header-title">Border spinner</h4>
        <p class="sub-header">
          Use the border spinners for a lightweight loading indicator.
        </p>
        <div class="spinner-border text-primary m-2" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
      </div>
      <!--end card-body-->
    </div>
    <!--end card-->
  </div>

  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <h4 class="header-title">Growing spinner</h4>
        <p class="sub-header">
          If you don’t fancy a border spinner, switch to the grow spinner. While
          it doesn’t technically spin, it does repeatedly grow!
        </p>
        <div class="spinner-grow text-success" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
      </div>
      <!--end card-body-->
    </div>
    <!--end card-->
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <h4 class="header-title">Colors</h4>
        <p class="sub-header">
          You can use any of our text color utilities on the standard spinner.
        </p>
        <div class="spinner-border text-primary m-2" role="status"></div>
        <div class="spinner-border text-secondary m-2" role="status"></div>
        <div class="spinner-border text-success m-2" role="status"></div>
        <div class="spinner-border text-danger m-2" role="status"></div>
        <div class="spinner-border text-warning m-2" role="status"></div>
        <div class="spinner-border text-info m-2" role="status"></div>
        <div class="spinner-border text-light m-2" role="status"></div>
        <div class="spinner-border text-dark m-2" role="status"></div>
        <div class="spinner-border text-blue m-2" role="status"></div>
        <div class="spinner-border text-pink m-2" role="status"></div>
      </div>
      <!--end card-body-->
    </div>
    <!--end card-->
  </div>

  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <h4 class="header-title">Color Growing spinner</h4>
        <p class="sub-header">
          Here it is in blue, along with the supported variants.
        </p>
        <div class="spinner-grow text-primary m-2" role="status"></div>
        <div class="spinner-grow text-secondary m-2" role="status"></div>
        <div class="spinner-grow text-success m-2" role="status"></div>
        <div class="spinner-grow text-danger m-2" role="status"></div>
        <div class="spinner-grow text-warning m-2" role="status"></div>
        <div class="spinner-grow text-info m-2" role="status"></div>
        <div class="spinner-grow text-light m-2" role="status"></div>
        <div class="spinner-grow text-dark m-2" role="status"></div>
        <div class="spinner-grow text-blue m-2" role="status"></div>
        <div class="spinner-grow text-pink m-2" role="status"></div>
      </div>
      <!--end card-body-->
    </div>
    <!--end card-->
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <h4 class="header-title">Alignment</h4>
        <p class="sub-header">
          Use flexbox utilities, float utilities, or text alignment utilities to
          place spinners exactly where you need them in any situation.
        </p>
        <div class="d-flex justify-content-center">
          <div class="spinner-border" role="status"></div>
        </div>
      </div>
      <!--end card-body-->
    </div>
    <!--end card-->
  </div>

  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <h4 class="header-title">Placement</h4>
        <p class="sub-header">
          Use <code>flexbox utilities</code>, <code>float utilities</code>, or
          <code>text alignment</code> utilities to place spinners exactly where
          you need them in any situation.
        </p>
        <div class="d-flex align-items-center">
          <strong>Loading...</strong>
          <div
            class="spinner-border ms-auto"
            role="status"
            aria-hidden="true"
          ></div>
        </div>
      </div>
      <!--end card-body-->
    </div>
    <!--end card-->
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <h4 class="header-title">Size</h4>
        <p class="sub-header">
          Add <code>.spinner-border-sm</code> and
          <code>.spinner-border.avatar-**</code>
          to make a smaller spinner that can quickly be used within other
          components.
        </p>
        <div class="row">
          <div class="col-lg-6">
            <div
              class="spinner-border avatar-lg text-primary m-2"
              role="status"
            ></div>
            <div
              class="spinner-grow avatar-lg text-secondary m-2"
              role="status"
            ></div>
          </div>

          <div class="col-lg-6">
            <div
              class="spinner-border avatar-md text-primary m-2"
              role="status"
            ></div>
            <div
              class="spinner-grow avatar-md text-secondary m-2"
              role="status"
            ></div>
          </div>

          <div class="col-lg-6">
            <div
              class="spinner-border avatar-sm text-primary m-2"
              role="status"
            ></div>
            <div
              class="spinner-grow avatar-sm text-secondary m-2"
              role="status"
            ></div>
          </div>

          <div class="col-lg-6">
            <div
              class="spinner-border spinner-border-sm m-2"
              role="status"
            ></div>
            <div class="spinner-grow spinner-grow-sm m-2" role="status"></div>
          </div>
        </div>
        <!--end row-->
      </div>
      <!--end card-body-->
    </div>
    <!--end card-->
  </div>

  <div class="col-lg-6">
    <div class="card">
      <div class="card-body">
        <h4 class="header-title">Buttons spinner</h4>
        <p class="sub-header">
          Use spinners within buttons to indicate an action is currently
          processing or taking place. You may also swap the text out of the
          spinner element and utilize button text as needed.
        </p>
        <div class="row">
          <div class="col-lg-6">
            <div class="button-list">
              <button class="btn btn-primary" type="button" disabled>
                <span
                  class="spinner-border spinner-border-sm"
                  role="status"
                  aria-hidden="true"
                ></span
                ><span class="visually-hidden">Loading...</span>
              </button>
              <button class="btn btn-primary" type="button" disabled>
                <span
                  class="spinner-border spinner-border-sm me-1"
                  role="status"
                  aria-hidden="true"
                ></span>
                Loading...
              </button>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="button-list">
              <button class="btn btn-success" type="button" disabled>
                <span
                  class="spinner-grow spinner-grow-sm"
                  role="status"
                  aria-hidden="true"
                ></span>
                <span class="visually-hidden">Loading...</span>
              </button>
              <button class="btn btn-success" type="button" disabled>
                <span
                  class="spinner-grow spinner-grow-sm me-1"
                  role="status"
                  aria-hidden="true"
                ></span>
                Loading...
              </button>
            </div>
          </div>
        </div>
      </div>
      <!--end card-body-->
    </div>
    <!--end card-->
  </div>
</div>
