// Minton_v10.1.0/Next.js/JS/src/app/(admin)/apps/email/inbox/EmailList.jsx
"use client";

import React, { useState } from "react";
import Link from "next/link";
import { Dropdown, ButtonGroup, Button } from "react-bootstrap";
import classNames from "classnames";

// dafault data
import { emails as mails } from "../data";
import LeftBar from "@/app/(admin)/apps/email/LeftBar";

// emails list
const EmailsList = props => {
  const emails = props.emails || [];
  return <ul className="message-list">
      {(emails || []).map((email, idx) => {
      return <li className={classNames({
        unread: !email.is_read
      })} key={idx}>
            <div className="col-mail col-mail-1">
              <div className="checkbox-wrapper-mail">
                <div className="form-check">
                  <input type="checkbox" className="form-check-input" id={"mail" + email.id} />
                  <label className="toggle" htmlFor={"mail" + email.id}></label>
                </div>
              </div>
              <span className={classNames("star-toggle", "far", "fa-star", {
            "text-warning": email.is_important
          })}></span>
              <Link href="/apps/email/details" className="title">
                {email.from_name}
                {email.number_of_reply > 1 && <span> ({email.number_of_reply})</span>}
              </Link>
            </div>
            <div className="col-mail col-mail-2">
              <Link href="/apps/email/details" className="subject">
                {email.subject} &nbsp;&ndash;&nbsp;
                <span className="teaser">{email.teaser}</span>
              </Link>
              <div className="date">{email.time}</div>
            </div>
          </li>;
    })}
    </ul>;
};
const EmailList = () => {
  const [emails, setEmails] = useState(mails.slice(0, 20));
  const [totalEmails] = useState(mails.length);
  const [pageSize] = useState(20);
  const [page, setPage] = useState(1);
  const [startIndex, setStartIndex] = useState(1);
  const [endIndex, setEndIndex] = useState(20);
  const [totalPages] = useState(mails.length / 20);
  const [totalUnreadEmails] = useState(mails.filter(e => e.is_read === false).length);

  /**
   * Gets the next page
   */
  const getNextPage = () => {
    let nextPage = page + 1;
    if (nextPage > totalEmails / pageSize) {
      nextPage = totalEmails / pageSize;
    }
    const startIdx = nextPage * pageSize - pageSize + 1;
    const endIdx = nextPage * pageSize;
    setPage(nextPage);
    setStartIndex(startIdx);
    setEndIndex(endIdx);
    setEmails(mails.slice(startIdx, endIdx));
  };

  /**
   * Gets the prev page
   */
  const getPrevPage = () => {
    let prevPage = page - 1;
    if (prevPage === 0) prevPage = 1;
    const startIdx = prevPage * pageSize - pageSize + 1;
    const endIdx = prevPage * pageSize;
    setPage(prevPage);
    setStartIndex(startIdx);
    setEndIndex(endIndex);
    setEmails(mails.slice(startIdx, endIdx));
  };

  /**
   * Shows the starred emails only
   */
  const showAllEmails = () => {
    setEmails(mails.slice(0, 20));
  };

  /**
   * Shows the starred emails only
   */
  const showStarredEmails = () => {
    setEmails(mails.filter(e => e.is_important).slice(0, 20));
  };
  return <div className="card">
      <div className="card-body">
        {/* left sidebar */}
        <LeftBar totalUnreadEmails={totalUnreadEmails} showAllEmails={showAllEmails} showStarredEmails={showStarredEmails} />

        {/* right sidebar */}
        <div className="inbox-rightbar">
          <ButtonGroup className="me-1">
            <Button variant="light" className="btn-sm waves-effect">
              <i className="mdi mdi-archive font-18"></i>
            </Button>
            <Button variant="light" className="btn-sm waves-effect">
              <i className="mdi mdi-alert-octagon font-18"></i>
            </Button>
            <Button variant="light" className="btn-sm waves-effect">
              <i className="mdi mdi-delete-variant font-18"></i>
            </Button>
          </ButtonGroup>

          <Dropdown as={ButtonGroup} className="me-1">
            <Dropdown.Toggle className="btn btn-light btn-sm waves-effect">
              <i className="mdi mdi-folder font-18"></i>{" "}
              <i className="mdi mdi-chevron-down"></i>
            </Dropdown.Toggle>
            <Dropdown.Menu>
              <Dropdown.Header as="span">Move to:</Dropdown.Header>
              <Dropdown.Item>Social</Dropdown.Item>
              <Dropdown.Item>Promotions</Dropdown.Item>
              <Dropdown.Item>Updates</Dropdown.Item>
              <Dropdown.Item>Forums</Dropdown.Item>
            </Dropdown.Menu>
          </Dropdown>

          <Dropdown as={ButtonGroup} className="me-1">
            <Dropdown.Toggle className="btn btn-light btn-sm waves-effect">
              <i className="mdi mdi-label font-18"></i>{" "}
              <i className="mdi mdi-chevron-down"></i>
            </Dropdown.Toggle>
            <Dropdown.Menu>
              <Dropdown.Header as="span">Label as:</Dropdown.Header>
              <Dropdown.Item>Social</Dropdown.Item>
              <Dropdown.Item>Promotions</Dropdown.Item>
              <Dropdown.Item>Updates</Dropdown.Item>
              <Dropdown.Item>Forums</Dropdown.Item>
            </Dropdown.Menu>
          </Dropdown>

          <Dropdown as={ButtonGroup} className="me-1">
            <Dropdown.Toggle className="btn btn-light btn-sm waves-effect">
              <i className="mdi mdi-dots-horizontal font-18"></i> More{" "}
              <i className="mdi mdi-chevron-down"></i>
            </Dropdown.Toggle>
            <Dropdown.Menu>
              <Dropdown.Header as="span">More Options :</Dropdown.Header>
              <Dropdown.Item>Mark as Unread</Dropdown.Item>
              <Dropdown.Item>Add to Tasks</Dropdown.Item>
              <Dropdown.Item>Add Star</Dropdown.Item>
              <Dropdown.Item>Mute</Dropdown.Item>
            </Dropdown.Menu>
          </Dropdown>

          <div className="mt-3">
            <EmailsList emails={emails} />
          </div>

          <div className="row">
            <div className="col-xs-7 mt-1">
              Showing {startIndex} - {endIndex} of {totalEmails}
            </div>
            <div className="col-xs-5">
              <ButtonGroup className="float-end">
                {page === 1 ? <Button variant="light" className="btn-sm" disabled>
                    <i className="mdi mdi-chevron-left"></i>
                  </Button> : <Button variant="info" className="btn-sm" onClick={getPrevPage}>
                    <i className="mdi mdi-chevron-left"></i>
                  </Button>}

                {page < totalPages ? <Button variant="info" className="btn-sm" onClick={getNextPage}>
                    <i className="mdi mdi-chevron-right"></i>
                  </Button> : <Button variant="light" className="btn-sm" disabled>
                    <i className="mdi mdi-chevron-right"></i>
                  </Button>}
              </ButtonGroup>
            </div>
          </div>
        </div>

        <div className="clearfix"></div>
      </div>
    </div>;
};
export default EmailList;

// Minton_v10.1.0/Angular/Minton/src/app/views/email/inbox/component/email-list/email-list.component.ts
import { CommonModule } from '@angular/common'
import { Component, type OnInit } from '@angular/core'
import { RouterLink } from '@angular/router'
import { emails } from '@views/email/data'

@Component({
  selector: 'email-list',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './email-list.component.html',
  styles: ``,
})
export class EmailListComponent implements OnInit {
  emails = emails
  page: number = 1
  pageSize: number = 20
  totalEmails: number = 100 // Placeholder for total emails
  startIndex: number = 1
  endIndex: number = this.pageSize
  totalPages: number = Math.ceil(this.totalEmails / this.pageSize)

  ngOnInit(): void {
    this.updateEmailList()
  }

  getNextPage() {
    this.page =
      this.page + 1 > this.totalPages ? this.totalPages : this.page + 1
    this.updateEmailList()
  }

  getPrevPage() {
    this.page = this.page - 1 <= 0 ? 1 : this.page - 1
    this.updateEmailList()
  }

  updateEmailList() {
    const startIdx = (this.page - 1) * this.pageSize
    const endIdx = this.page * this.pageSize
    this.emails = emails.slice(startIdx, endIdx)
    this.startIndex = startIdx + 1
    this.endIndex = endIdx
  }
}

<div class="mt-3">
  <ul class="message-list">
    @for (email of emails; track $index) {
      <li [class]="{ unread: !email.is_read }">
        <div class="col-mail col-mail-1">
          <div class="checkbox-wrapper-mail">
            <input type="checkbox" [id]="'mail' + email.id" />
            <label [for]="'mail' + email.id" class="toggle"></label>
          </div>
          <span
            class="star-toggle far fa-star"
            [ngClass]="{ 'text-warning': email.is_important }"
          ></span>
          <a routerLink="/email/read" class="title"
            >{{ email.from_name }}
            @if (email.number_of_reply > 1) {
              <span> ({{ email.number_of_reply }})</span>
            }
          </a>
        </div>
        <div class="col-mail col-mail-2">
          <a routerLink="/email/read" class="subject"
            >{{ email.subject }} &nbsp;&ndash;&nbsp;
            <span class="teaser">&#64;{{ email.teaser }}</span>
          </a>
          <div class="date">{{ email.time }}</div>
        </div>
      </li>
    }
  </ul>
</div>

<div class="row">
  <div class="col-7 mt-1">
    Showing {{ startIndex }} - {{ endIndex }} of {{ totalEmails }}
  </div>
  <!-- end col-->
  <div class="col-5">
    <div class="btn-group float-end">
      <button
        type="button"
        class="btn btn-light btn-sm"
        [disabled]="page === 1"
        (click)="getPrevPage()"
      >
        <i class="mdi mdi-chevron-left"></i>
      </button>
      <button
        type="button"
        class="btn btn-light btn-sm"
        [disabled]="page >= totalPages"
        (click)="getNextPage()"
      >
        <i class="mdi mdi-chevron-right"></i>
      </button>
    </div>
  </div>
  <!-- end col-->
</div>
