// Minton_v10.1.0/Angular/Minton/src/app/views/charts/apex/components/candlestick-chart/candlestick-chart.component.ts
import { Component } from '@angular/core'
import type { ChartOptions } from '@common/apexchart.model'
import { CustomCardPortletComponent } from '@component/custom-card-portlet/custom-card-portlet.component'
import { NgApexchartsModule } from 'ng-apexcharts'
import { seriesData } from '../../data'

@Component({
  selector: 'candlestick-chart',
  standalone: true,
  imports: [NgApexchartsModule, CustomCardPortletComponent],
  templateUrl: './candlestick-chart.component.html',
  styles: ``,
})
export class CandlestickChartComponent {
  apexcandlestick1Chart: Partial<ChartOptions> = {
    chart: {
      height: 400,
      type: 'candlestick',
    },
    plotOptions: {
      candlestick: {
        colors: {
          upward: '#3bafda',
          downward: '#1abc9c',
        },
      },
    },
    series: [
      {
        data: seriesData,
      },
    ],

    stroke: {
      show: true,
      colors: ['#f1f3fa'],
      width: [1, 4],
    },
    xaxis: {
      type: 'datetime',
    },
    grid: {
      borderColor: '#f1f3fa',
    },
  }
}

<custom-card-portlet
  cardTitle="Simple Candlestick Chart"
  cardTitleClass="header-title mb-0"
>
  <div
    id="apex-candlestick-1"
    class="apex-charts"
    data-colors="#3bafda,#1abc9c"
  >
    <apx-chart
      [chart]="apexcandlestick1Chart.chart!"
      [plotOptions]="apexcandlestick1Chart.plotOptions!"
      [series]="apexcandlestick1Chart.series!"
      [stroke]="apexcandlestick1Chart.stroke!"
      [xaxis]="apexcandlestick1Chart.xaxis!"
      [grid]="apexcandlestick1Chart.grid!"
    />
  </div>
</custom-card-portlet>

// Minton_v10.1.0/React.js/TS/src/app/(admin)/charts/apex/CandleStickChart.tsx


import {ApexOptions} from "apexcharts";
import {Card} from "react-bootstrap";

import {candleStickChartData1} from "@/app/(admin)/charts/apex/data";

import ReactApexChart from "react-apexcharts";

const CandleStickChart = () => {
    const options: ApexOptions = {
        chart: {
            height: 400,
            type: "candlestick",
            toolbar: {
                show: false,
            },
        },
        colors: ["#3bafda", "#1abc9c"],
        plotOptions: {
            candlestick: {
                colors: {
                    upward: "#3bafda",
                    downward: "#1abc9c",
                },
            },
        },
        stroke: {
            show: true,
            colors: ["#f1f3fa"],
            width: 1,
        },
        xaxis: {
            type: "datetime",
        },
        grid: {
            borderColor: "#f1f3fa",
        },
    };

    const series = [
        {
            data: candleStickChartData1.data || [],
        },
    ];

    return (
        <Card>
            <Card.Body>
                <h5 className="header-title mb-0">Simple Candlestick Chart</h5>
                <div className="pt-3">
                    <ReactApexChart
                        options={options}
                        series={series}
                        type="candlestick"
                        height={400}
                        
                    />
                </div>
            </Card.Body>
        </Card>
    );
};

export default CandleStickChart;
