// Minton_v10.1.0/Angular/Minton/src/app/views/charts/apex/components/column-chart/column-chart.component.ts
import { Component } from '@angular/core'
import type { ChartOptions } from '@common/apexchart.model'
import { CustomCardPortletComponent } from '@component/custom-card-portlet/custom-card-portlet.component'
import { NgApexchartsModule } from 'ng-apexcharts'

@Component({
  selector: 'column-chart',
  standalone: true,
  imports: [NgApexchartsModule, CustomCardPortletComponent],
  templateUrl: './column-chart.component.html',
  styles: ``,
})
export class ColumnChartComponent {
  apexcolumn1Chart: Partial<ChartOptions> = {
    chart: {
      height: 380,
      type: 'bar',
      toolbar: {
        show: false,
      },
    },
    plotOptions: {
      bar: {
        horizontal: false,
        columnWidth: '55%',
      },
    },
    dataLabels: {
      enabled: false,
    },
    stroke: {
      show: true,
      width: 2,
      colors: ['transparent'],
    },
    colors: ['#3bafda', '#1abc9c', '#CED4DC'],
    series: [
      {
        name: 'Net Profit',
        data: [44, 55, 57, 56, 61, 58, 63, 60, 66],
      },
      {
        name: 'Revenue',
        data: [76, 85, 101, 98, 87, 105, 91, 114, 94],
      },
      {
        name: 'Free Cash Flow',
        data: [35, 41, 36, 26, 45, 48, 52, 53, 41],
      },
    ],
    xaxis: {
      categories: [
        'Feb',
        'Mar',
        'Apr',
        'May',
        'Jun',
        'Jul',
        'Aug',
        'Sep',
        'Oct',
      ],
    },
    legend: {
      offsetY: 5,
    },
    yaxis: {
      title: {
        text: '$ (thousands)',
      },
    },
    fill: {
      opacity: 1,
    },
    grid: {
      row: {
        colors: ['transparent', 'transparent'], // takes an array which will be repeated on columns
        opacity: 0.2,
      },
      borderColor: '#f1f3fa',
      padding: {
        bottom: 10,
      },
    },
    tooltip: {
      y: {
        formatter: function (val) {
          return '$ ' + val + ' thousands'
        },
      },
    },
  }
}

<custom-card-portlet
  cardTitle="Basic Column Chart"
  cardTitleClass="header-title mb-0"
>
  <div
    id="apex-column-1"
    class="apex-charts"
    data-colors="#3bafda,#1abc9c,#CED4DC"
  >
    <apx-chart
      [chart]="apexcolumn1Chart.chart!"
      [plotOptions]="apexcolumn1Chart.plotOptions!"
      [dataLabels]="apexcolumn1Chart.dataLabels!"
      [stroke]="apexcolumn1Chart.stroke!"
      [colors]="apexcolumn1Chart.colors!"
      [series]="apexcolumn1Chart.series!"
      [xaxis]="apexcolumn1Chart.xaxis!"
      [legend]="apexcolumn1Chart.legend!"
      [yaxis]="apexcolumn1Chart.yaxis!"
      [fill]="apexcolumn1Chart.fill!"
      [grid]="apexcolumn1Chart.grid!"
      [tooltip]="apexcolumn1Chart.tooltip!"
    />
  </div>
</custom-card-portlet>

// Minton_v10.1.0/React.js/TS/src/app/(admin)/charts/apex/ColumnChart.tsx

import {ApexOptions} from "apexcharts";
import {basicColumnChartData} from "@/app/(admin)/charts/apex/data";
import {Card} from "react-bootstrap";


import ReactApexChart from "react-apexcharts";

const ColumnChart = () => {
    const options: ApexOptions = {
        chart: {
            height: 380,
            type: "bar",
            toolbar: {
                show: false,
            },
        },
        plotOptions: {
            bar: {
                horizontal: false,
                columnWidth: "55%",
            },
        },
        dataLabels: {
            enabled: false,
        },
        stroke: {
            show: true,
            width: 2,
            colors: ["transparent"],
        },
        colors: ["#3bafda", "#1abc9c", "#CED4DC"],
        xaxis: {
            categories: [
                "Feb",
                "Mar",
                "Apr",
                "May",
                "Jun",
                "Jul",
                "Aug",
                "Sep",
                "Oct",
            ],
        },
        legend: {
            offsetY: 5,
        },
        yaxis: {
            title: {
                text: "$ (thousands)",
            },
        },
        fill: {
            opacity: 1,
        },
        grid: {
            row: {
                colors: ["transparent", "transparent"], // takes an array which will be repeated on columns
                opacity: 0.2,
            },
            borderColor: "#f1f3fa",
            padding: {
                bottom: 10,
            },
        },
        tooltip: {
            y: {
                formatter: function (val) {
                    return "$ " + val + " thousands";
                },
            },
        },
    };

    const series = [
        {
            name: "Net Profit",
            data: basicColumnChartData.data1 || [],
        },
        {
            name: "Revenue",
            data: basicColumnChartData.data2 || [],
        },
        {
            name: "Free Cash Flow",
            data: basicColumnChartData.data3 || [],
        },
    ];

    return (
        <Card>
            <Card.Body>
                <h5 className="header-title mb-0">Basic Column Chart</h5>
                <ReactApexChart
                    options={options}
                    series={series}
                    type="bar"
                    height={380}
                    
                />
            </Card.Body>
        </Card>
    );
};

export default ColumnChart;
