// Minton_v10.1.0/React.js/TS/src/app/(admin)/apps/tasks/kanban/KanbanBoard.tsx

import { closestCenter, DndContext, PointerSensor, useSensor, useSensors, } from "@dnd-kit/core";
import {
    arrayMove,
    defaultAnimateLayoutChanges,
    SortableContext,
    useSortable,
    verticalListSortingStrategy
} from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { useState } from "react";

// dummy data
import { tasks, TaskTypes } from "./data";

// images
import { Link } from "react-router-dom";

import { Button, Card, CardBody, Col, Dropdown, Row } from "react-bootstrap";

interface TaskItemProps {
    task: TaskTypes;
    id: string
}

const TaskItem = ({id, task}: TaskItemProps) => {
    const {
        attributes,
        listeners,
        setNodeRef,
        transform,
        transition,
        isDragging
    } = useSortable({id, animateLayoutChanges: defaultAnimateLayoutChanges,});

    const style = {
        transform: CSS.Transform.toString(transform),
        transition,
        cursor: "grab",
        opacity: isDragging ? 0.5 : 1,
        zIndex: isDragging ? 100 : 1,
    };

    return (
        <li ref={setNodeRef} style={style} {...attributes} {...listeners} className={`task-${task.priority}`}>
            <div className="form-check mb-2 float-end">
                <input className="form-check-input ms-0" type="checkbox" value=""/>
            </div>
            <h5 className="mt-0">
                <Link to="" className="text-dark">
                    {task.title}
                </Link>
            </h5>

            <p>{task.description}</p>

            <div className="clearfix"></div>

            <Row>
                <Col xs={'auto'}>
                    <div>
                        {(task.userAvatar || []).map((avatar, index) => {
                            return (
                                <Link key={index} to="" className="me-1">
                                    <img
                                        src={avatar}
                                        alt="avatar"
                                        className="avatar-sm img-thumbnail rounded-circle"
                                        height={36}
                                        width={36}
                                    />
                                </Link>
                            );
                        })}
                    </div>
                </Col>
                <Col>
                    <div className="text-end">
                        <p className="font-13 mt-2 mb-0">
                            <i className="mdi mdi-calendar"></i> {task.dueDate}
                        </p>
                    </div>
                </Col>
            </Row>
        </li>
    );
};

const TaskList = ({list, title}: {
    list: TaskTypes[], title?: string
}) => {

    return (
        <SortableContext items={list.map(i => i.id.toString())} strategy={verticalListSortingStrategy}>
            <Col lg={4}>
                <Card>
                    <CardBody>
                        <Dropdown className="float-end" align="end">
                            <Dropdown.Toggle as="a" className="cursor-pointer">
                                <i className="mdi mdi-dots-vertical m-0 text-muted h3"></i>
                            </Dropdown.Toggle>
                            <Dropdown.Menu>
                                <Dropdown.Item>Edit</Dropdown.Item>
                                <Dropdown.Item>Delete</Dropdown.Item>
                                <Dropdown.Item>Add Members</Dropdown.Item>
                                <Dropdown.Item>Add Due Date</Dropdown.Item>
                            </Dropdown.Menu>
                        </Dropdown>

                        <h5 className="header-title">{title}</h5>
                        <p className="sub-header">
                            Your awesome text goes here. Your awesome text goes here.
                        </p>

                        <ul className="sortable-list tasklist list-unstyled">
                            {list.map((item) => (
                                <TaskItem task={item} id={item.id.toString()} key={item.id}/>
                            ))}
                        </ul>
                        <div className="d-grid">
                            <Button variant="primary" className="mt-3 waves-effect waves-light">
                                <i className="mdi mdi-plus-circle"></i> Add New
                            </Button>
                        </div>
                    </CardBody>
                </Card>
            </Col>
        </SortableContext>
    )
};

const KanbanBoard = () => {

    const [upcomingTasks, setUpcomingTasks] = useState<TaskTypes[]>(tasks.filter((t) => t.status === "upcoming"))
    const [inProgressTasks, setInProgressTasks] = useState<TaskTypes[]>(tasks.filter((t) => t.status === "in-progress"))
    const [completedTasks, setCompletedTasks] = useState<TaskTypes[]>(tasks.filter((t) => t.status === "completed"))

    const sensors = useSensors(useSensor(PointerSensor));

    const allLists = {
        'upcoming': upcomingTasks,
        'in-progress': inProgressTasks,
        'completed': completedTasks,
    };

    const setListByKey = {
        'upcoming': setUpcomingTasks,
        'in-progress': setInProgressTasks,
        'completed': setCompletedTasks,
    };

    const findContainer = (id: string) => {
        if (upcomingTasks.some((t) => t.id.toString() === id)) return 'upcoming';
        if (inProgressTasks.some((t) => t.id.toString() === id)) return 'in-progress';
        if (completedTasks.some((t) => t.id.toString() === id)) return 'completed';
        return null;
    };

    const handleDragEnd = ({active, over}:any) => {

        if (!over) return;

        const activeList = findContainer(active.id);
        const overList = findContainer(over.id);

        if (!activeList || !overList) return;

        if (activeList === overList) {
            const list = allLists[activeList];
            const oldIndex = list.findIndex((t) => t.id.toString() === active.id);
            const newIndex = list.findIndex((t) => t.id.toString() === over.id);
            const updated = arrayMove(list, oldIndex, newIndex);
            setListByKey[activeList](updated);
        } else {
            const sourceList = allLists[activeList].filter((t) => t.id.toString() !== active.id);
            const draggedItem = allLists[activeList].find((t) => t.id.toString() === active.id);
            const targetList = [...allLists[overList]];
            const overIndex = targetList.findIndex((t) => t.id.toString() === over.id);
            targetList.splice(overIndex, 0, draggedItem!);

            setListByKey[activeList](sourceList);
            setListByKey[overList](targetList);
        }
    };

    return (
        <>
            <DndContext sensors={sensors}
                        collisionDetection={closestCenter}
                        onDragEnd={handleDragEnd}>

                <Row>
                    <TaskList title="Upcoming" list={upcomingTasks}/>
                    <TaskList title="In Progress" list={inProgressTasks}/>
                    <TaskList title="Completed" list={completedTasks}/>
                </Row>
            </DndContext>

        </>
    )
}

export default KanbanBoard

// Minton_v10.1.0/Angular/Minton/src/app/views/task/kanban-board/kanban-board.component.ts
import { Component, type OnInit } from '@angular/core'
import { PageTitleComponent } from '@component/page-title.component'
import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap'
import {
    CdkDrag,
    CdkDragDrop,
    CdkDropList,
    CdkDropListGroup,
    moveItemInArray,
    transferArrayItem,
} from '@angular/cdk/drag-drop'
import { TaskItemComponent } from './components/task-item/task-item.component'
import { tasks, type TaskTypes } from './data'

@Component({
  selector: 'app-kanban-board',
  standalone: true,
  imports: [
    PageTitleComponent,
    NgbDropdownModule,
    TaskItemComponent,
    CdkDropListGroup, CdkDropList, CdkDrag
  ],
  templateUrl: './kanban-board.component.html',
  styles: ``,
})
export class KanbanBoardComponent implements OnInit {
  breadCrumbItems = [
    { label: 'Tasks', path: '/task/list' },
    { label: 'Kanban Board', path: '/task/kanban-board', active: true },
  ]

  upcomingTasks: TaskTypes[] = []
  inprogressTasks: TaskTypes[] = []
  completedTasks: TaskTypes[] = []
  newTaskDetails: any = null
  totalTasks: number = tasks.length

  constructor() {}

  ngOnInit(): void {
    this.upcomingTasks = tasks.filter((t) => t.status === 'Upcoming')
    this.inprogressTasks = tasks.filter((t) => t.status === 'Inprogress')
    this.completedTasks = tasks.filter((t) => t.status === 'Completed')
  }

  drop(event: CdkDragDrop<TaskTypes[], any, any>) {
    if (event.previousContainer === event.container) {
      moveItemInArray(event.container.data, event.previousIndex, event.currentIndex);
    } else {
      transferArrayItem(
        event.previousContainer.data,
        event.container.data,
        event.previousIndex,
        event.currentIndex,
      );
    }
  }
}

<app-page-title title="Kanban Board" [breadCrumbItems]="breadCrumbItems" />

<div class="row" cdkDropListGroup>
  <div class="col-lg-4">
    <div class="card">
      <div class="card-body">
        <div ngbDropdown class="float-end">
          <a ngbDropdownToggle class="arrow-none">
            <i class="mdi mdi-dots-vertical m-0 text-muted h3"></i>
          </a>
          <div ngbDropdownMenu class="dropdown-menu-end">
            <a role="button" ngbDropdownItem>Edit</a>
            <a role="button" ngbDropdownItem>Delete</a>
            <a role="button" ngbDropdownItem>Add Members</a>
            <a role="button" ngbDropdownItem>Add Due Date</a>
          </div>
        </div>

        <h4 class="header-title">Upcoming</h4>
        <p class="sub-header">
          Your awesome text goes here. Your awesome text goes here.
        </p>

        <ul
          class="sortable-list tasklist list-unstyled"
          id="upcoming"
          (cdkDropListDropped)="drop($event)"
          cdkDropList
          [cdkDropListData]="upcomingTasks"
        >
          @for (task of upcomingTasks; track $index) {
            <li id="task{{ task.id }}" class="task-{{ task.priority }} card card-body overflow-hidden" cdkDrag>
              <div>
                <kanban-task-item [task]="task" />
              </div>
            </li>
          }
        </ul>
        <div class="d-grid">
          <a
            href="javascript: void(0);"
            class="btn btn-primary mt-3 waves-effect waves-light"
            ><i class="mdi mdi-plus-circle"></i> Add New</a
          >
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="card">
      <div class="card-body">
        <div ngbDropdown class="float-end">
          <a ngbDropdownToggle class="arrow-none">
            <i class="mdi mdi-dots-vertical m-0 text-muted h3"></i>
          </a>
          <div ngbDropdownMenu class="dropdown-menu-end">
            <a role="button" ngbDropdownItem>Edit</a>
            <a role="button" ngbDropdownItem>Delete</a>
            <a role="button" ngbDropdownItem>Add Members</a>
            <a role="button" ngbDropdownItem>Add Due Date</a>
          </div>
        </div>

        <h4 class="header-title">In Progress</h4>
        <p class="sub-header">Your awesome text goes here.</p>

        <ul
          class="sortable-list tasklist list-unstyled"
          id="inprogress"
          cdkDropList
          (cdkDropListDropped)="drop($event)"
          [cdkDropListData]="inprogressTasks"
        >
          @for (task of inprogressTasks; track $index) {
            <li id="task{{ task.id }}" class="task-{{ task.priority }} card card-body overflow-hidden" cdkDrag>
              <div>
                <kanban-task-item [task]="task" />
              </div>
            </li>
          }
        </ul>
        <div class="d-grid">
          <a
            href="javascript: void(0);"
            class="btn btn-primary mt-3 waves-effect waves-light"
            ><i class="mdi mdi-plus-circle"></i> Add New</a
          >
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="card">
      <div class="card-body">
        <div ngbDropdown class="float-end">
          <a ngbDropdownToggle class="arrow-none">
            <i class="mdi mdi-dots-vertical m-0 text-muted h3"></i>
          </a>
          <div ngbDropdownMenu class="dropdown-menu-end">
            <a role="button" ngbDropdownItem>Edit</a>
            <a role="button" ngbDropdownItem>Delete</a>
            <a role="button" ngbDropdownItem>Add Members</a>
            <a role="button" ngbDropdownItem>Add Due Date</a>
          </div>
        </div>

        <h4 class="header-title">Completed</h4>
        <p class="sub-header">
          Your awesome text goes here. Your awesome text goes here.
        </p>

        <ul
          class="sortable-list tasklist list-unstyled"
          id="completed"
          cdkDropList
          (cdkDropListDropped)="drop($event)"
          [cdkDropListData]="completedTasks"
        >
          @for (task of completedTasks; track $index) {
            <li id="task{{ task.id }}" class="task-{{ task.priority }} card card-body overflow-hidden" cdkDrag>
              <div>
                <kanban-task-item [task]="task" />
              </div>
            </li>
          }
        </ul>
        <div class="d-grid">
          <a
            href="javascript: void(0);"
            class="btn btn-primary mt-3 waves-effect waves-light"
            ><i class="mdi mdi-plus-circle"></i> Add New</a
          >
        </div>
      </div>
    </div>
  </div>
</div>
