// Minton_v10.1.0/Next.js/TS/src/app/(admin)/dashboard/analytics/EngagementOverviews.tsx
import React from "react";
import Link from "next/link";

// types
import { EngagementOverviewsTypes } from "./data";

interface EngagementOverviewsProps {
  engagementOverview: EngagementOverviewsTypes[];
}

const EngagementOverviews = ({
  engagementOverview,
}: EngagementOverviewsProps) => {
  return (
    <div className="card">
      <div className="card-body">
        <div className="clearfix">
          <Link href="" className="p-0 float-end mb-3">
            Export <i className="mdi mdi-download ms-1"></i>
          </Link>
          <h4 className="header-title">Engagement Overview</h4>
        </div>

        <div className="table-responsive">
          <table className="table table-sm table-centered mb-0 font-14">
            <thead className="table-light">
              <tr>
                <th>Duration (Secs)</th>
                <th style={{ width: "30%" }}>Sessions</th>
                <th style={{ width: "30%" }}>Views</th>
              </tr>
            </thead>
            <tbody>
              {(engagementOverview || []).map((item, index) => {
                return (
                  <tr key={index}>
                    <td>{item.duration}</td>
                    <td>{item.sessions}</td>
                    <td>{item.views}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default EngagementOverviews;

// Minton_v10.1.0/Angular/Minton/src/app/views/dashboard/analytics/components/engagement-overviews/engagement-overviews.component.ts
import { Component } from '@angular/core'
import { engagementOverview } from '../../data'

@Component({
  selector: 'analytics-engagement-overviews',
  standalone: true,
  imports: [],
  templateUrl: './engagement-overviews.component.html',
  styles: ``,
})
export class EngagementOverviewsComponent {
  engagementList = engagementOverview
}

<div class="card">
  <div class="card-body">
    <div class="clearfix">
      <a href="javascript:void(0);" class="p-0 float-end mb-3"
        >Export <i class="mdi mdi-download ms-1"></i
      ></a>
      <h4 class="header-title">Engagement Overview</h4>
    </div>

    <div class="table-responsive">
      <table class="table table-sm table-centered mb-0 font-14">
        <thead class="table-light">
          <tr>
            <th>Duration (Secs)</th>
            <th style="width: 30%">Sessions</th>
            <th style="width: 30%">Views</th>
          </tr>
        </thead>
        <tbody>
          @for (item of engagementList; track $index) {
            <tr>
              <td>{{ item.duration }}</td>
              <td>{{ item.sessions }}</td>
              <td>{{ item.views }}</td>
            </tr>
          }
        </tbody>
      </table>
    </div>
    <!-- end table-responsive-->
  </div>
  <!-- end card-body-->
</div>
<!-- end card-->
