// Minton_v10.1.0/React.js/JS/src/app/(admin)/ui/ribbons/page.jsx
import classNames from "classnames";

// components
import PageBreadcrumb from "@/components/PageBreadcrumb";
import { Card, CardBody, Col, Row } from "react-bootstrap";
import React from "react";
const Ribbon1 = ({
  label,
  color,
  direction
}) => {
  return <Card className="ribbon-box">
      <CardBody>
        <div className={classNames("ribbon", "ribbon-" + color, direction === "left" ? "float-start" : "float-end")}>
          <i className="mdi mdi-access-point me-1"></i> {label}
        </div>
        <h5 className={classNames("text-" + color, "mt-0", direction === "left" ? "float-end" : "float-start")}>
          {label} Header
        </h5>
        <div className="ribbon-content">
          <p className="mb-0">
            Quisque nec turpis at urna dictum luctus. Suspendisse convallis
            dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
            dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
            dapibus odio.
          </p>
        </div>
      </CardBody>
    </Card>;
};
const Ribbon2 = ({
  label,
  color
}) => {
  return <Card className="ribbon-box">
      <CardBody>
        <div className={classNames("ribbon-two", "ribbon-two-" + color)}>
          <span>{label}</span>
        </div>
        <p className="mb-0">
          Quisque nec turpis at urna dictum luctus. Suspendisse convallis
          dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
          dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
          dapibus odio. Vivamus pretium nec odio cursus elementum. Suspendisse
          molestie ullamcorper ornare.
        </p>
      </CardBody>
    </Card>;
};
const Ribbon3 = ({
  label,
  color,
  direction
}) => {
  return <Card className="ribbon-box">
      <CardBody>
        <div className={classNames("ribbon", "ribbon-shape", "ribbon-" + color, direction === "left" ? "float-start" : "float-end")}>
          {label}
        </div>
        <h5 className={classNames("text-" + color, "mt-0", direction === "left" ? "float-end" : "float-start")}>
          {label} Header
        </h5>

        <div className="ribbon-content">
          <p className="mb-0">
            Quisque nec turpis at urna dictum luctus. Suspendisse convallis
            dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
            dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
            dapibus odio.
          </p>
        </div>
      </CardBody>
    </Card>;
};
const Ribbons = () => {
  return <React.Fragment>
      <PageBreadcrumb breadCrumbItems={[{
      label: "Base UI",
      path: "/ui/ribbons"
    }, {
      label: "Ribbons",
      path: "/ui/ribbons",
      active: true
    }]} title={"Ribbons"} />

      <Row>
        <Col lg={4}>
          <Ribbon1 label="Purple" color="purple" direction="left" />
        </Col>
        <Col lg={4}>
          <Ribbon1 label="Primary" color="primary" direction="right" />
        </Col>
        <Col lg={4}>
          <Ribbon1 label="Success" color="success" direction="right" />
        </Col>
      </Row>

      <Row>
        <Col lg={4}>
          <Ribbon1 label="Info" color="info" direction="left" />
        </Col>
        <Col lg={4}>
          <Ribbon1 label="Warning" color="warning" direction="right" />
        </Col>
        <Col lg={4}>
          <Ribbon1 label="Danger" color="danger" direction="right" />
        </Col>
      </Row>

      <Row>
        <Col lg={4}>
          <Ribbon3 label="Pink" color="pink" direction="left" />
        </Col>
        <Col lg={4}>
          <Ribbon3 label="Secondary" color="secondary" direction="right" />
        </Col>
        <Col lg={4}>
          <Ribbon3 label="Dark" color="dark" direction="right" />
        </Col>
      </Row>

      <Row>
        <Col lg={4}>
          <Ribbon2 label="Secondary" color="secondary" />
        </Col>
        <Col lg={4}>
          <Ribbon2 label="Primary" color="primary" />
        </Col>
        <Col lg={4}>
          <Ribbon2 label="Success" color="success" />
        </Col>
      </Row>

      <Row>
        <Col lg={4}>
          <Ribbon2 label="Info" color="info" />
        </Col>
        <Col lg={4}>
          <Ribbon2 label="Warning" color="warning" />
        </Col>
        <Col lg={4}>
          <Ribbon2 label="Danger" color="danger" />
        </Col>
      </Row>

      <Row>
        <Col lg={4}>
          <Ribbon2 label="Pink" color="pink" />
        </Col>
        <Col lg={4}>
          <Ribbon2 label="Purple" color="purple" />
        </Col>
        <Col lg={4}>
          <Ribbon2 label="Dark" color="dark" />
        </Col>
      </Row>
    </React.Fragment>;
};
export default Ribbons;

// Minton_v10.1.0/Angular/Minton/src/app/views/base-ui/ribbons/ribbons.component.ts
import { Component } from '@angular/core'
import { PageTitleComponent } from '@component/page-title.component'

@Component({
  selector: 'app-ribbons',
  standalone: true,
  imports: [PageTitleComponent],
  templateUrl: './ribbons.component.html',
  styles: ``,
})
export class RibbonsComponent {
  breadCrumbItems = [
    { label: 'Base UI', path: '/ui/ribbons' },
    { label: 'Ribbons', path: '/ui/ribbons', active: true },
  ]
}

<app-page-title title="Ribbons" [breadCrumbItems]="breadCrumbItems" />

<div class="row">
  <div class="col-lg-4">
    <div class="card ribbon-box">
      <div class="card-body">
        <div class="ribbon ribbon-purple float-start">
          <i class="mdi mdi-access-point me-1"></i> Purple
        </div>
        <h5 class="text-purple float-end mt-0">Purple Header</h5>
        <div class="ribbon-content">
          <p class="mb-0">
            Quisque nec turpis at urna dictum luctus. Suspendisse convallis
            dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
            dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
            dapibus odio.
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="card ribbon-box">
      <div class="card-body">
        <div class="ribbon ribbon-primary float-end">
          <i class="mdi mdi-access-point me-1"></i> Primary
        </div>
        <h5 class="text-primary float-start mt-0">Primary Header</h5>
        <div class="ribbon-content">
          <p class="mb-0">
            Quisque nec turpis at urna dictum luctus. Suspendisse convallis
            dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
            dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
            dapibus odio.
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="card ribbon-box">
      <div class="card-body">
        <div class="ribbon ribbon-success float-end">
          <i class="mdi mdi-access-point me-1"></i> Success
        </div>
        <h5 class="text-success float-start mt-0">Success Header</h5>
        <div class="ribbon-content">
          <p class="mb-0">
            Quisque nec turpis at urna dictum luctus. Suspendisse convallis
            dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
            dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
            dapibus odio.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <div class="card ribbon-box">
      <div class="card-body">
        <div class="ribbon ribbon-info float-start">
          <i class="mdi mdi-access-point me-1"></i> Info
        </div>
        <h5 class="text-info float-end mt-0">Info Header</h5>
        <div class="ribbon-content">
          <p class="mb-0">
            Quisque nec turpis at urna dictum luctus. Suspendisse convallis
            dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
            dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
            dapibus odio.
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="card ribbon-box">
      <div class="card-body">
        <div class="ribbon ribbon-warning float-end">
          <i class="mdi mdi-access-point me-1"></i> Warning
        </div>
        <h5 class="text-warning float-start mt-0">Warning Header</h5>
        <div class="ribbon-content">
          <p class="mb-0">
            Quisque nec turpis at urna dictum luctus. Suspendisse convallis
            dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
            dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
            dapibus odio.
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="card ribbon-box">
      <div class="card-body">
        <div class="ribbon ribbon-danger float-end">
          <i class="mdi mdi-access-point me-1"></i> Danger
        </div>
        <h5 class="text-danger float-start mt-0">Danger Header</h5>
        <div class="ribbon-content">
          <p class="mb-0">
            Quisque nec turpis at urna dictum luctus. Suspendisse convallis
            dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
            dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
            dapibus odio.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <div class="card ribbon-box">
      <div class="card-body">
        <div class="ribbon ribbon-pink float-start ribbon-shape">Pink</div>
        <h5 class="text-pink float-end mt-0">Pink Header</h5>
        <div class="ribbon-content">
          <p class="mb-0">
            Quisque nec turpis at urna dictum luctus. Suspendisse convallis
            dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
            dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
            dapibus odio.
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="card ribbon-box">
      <div class="card-body">
        <div class="ribbon ribbon-secondary float-end ribbon-shape">
          Secondary
        </div>
        <h5 class="text-secondary float-start mt-0">Secondary Header</h5>
        <div class="ribbon-content">
          <p class="mb-0">
            Quisque nec turpis at urna dictum luctus. Suspendisse convallis
            dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
            dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
            dapibus odio.
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="card ribbon-box">
      <div class="card-body">
        <div class="ribbon ribbon-dark float-end ribbon-shape">Dark</div>
        <h5 class="text-dark float-start mt-0">Dark Header</h5>
        <div class="ribbon-content">
          <p class="mb-0">
            Quisque nec turpis at urna dictum luctus. Suspendisse convallis
            dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
            dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
            dapibus odio.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <div class="card ribbon-box">
      <div class="card-body">
        <div class="ribbon-two ribbon-two-secondary">
          <span>Secondary</span>
        </div>
        <p class="mb-0">
          Quisque nec turpis at urna dictum luctus. Suspendisse convallis
          dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
          dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
          dapibus odio. Vivamus pretium nec odio cursus elementum. Suspendisse
          molestie ullamcorper ornare.
        </p>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="card ribbon-box">
      <div class="card-body">
        <div class="ribbon-two ribbon-two-primary"><span>Primary</span></div>
        <p class="mb-0">
          Quisque nec turpis at urna dictum luctus. Suspendisse convallis
          dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
          dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
          dapibus odio. Vivamus pretium nec odio cursus elementum. Suspendisse
          molestie ullamcorper ornare.
        </p>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="card ribbon-box">
      <div class="card-body">
        <div class="ribbon-two ribbon-two-success"><span>Success</span></div>
        <p class="mb-0">
          Quisque nec turpis at urna dictum luctus. Suspendisse convallis
          dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
          dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
          dapibus odio. Vivamus pretium nec odio cursus elementum. Suspendisse
          molestie ullamcorper ornare.
        </p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <div class="card ribbon-box">
      <div class="card-body">
        <div class="ribbon-two ribbon-two-info"><span>Info</span></div>
        <p class="mb-0">
          Quisque nec turpis at urna dictum luctus. Suspendisse convallis
          dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
          dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
          dapibus odio. Vivamus pretium nec odio cursus elementum. Suspendisse
          molestie ullamcorper ornare.
        </p>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="card ribbon-box">
      <div class="card-body">
        <div class="ribbon-two ribbon-two-warning"><span>Warning</span></div>
        <p class="mb-0">
          Quisque nec turpis at urna dictum luctus. Suspendisse convallis
          dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
          dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
          dapibus odio. Vivamus pretium nec odio cursus elementum. Suspendisse
          molestie ullamcorper ornare.
        </p>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="card ribbon-box">
      <div class="card-body">
        <div class="ribbon-two ribbon-two-danger"><span>Danger</span></div>
        <p class="mb-0">
          Quisque nec turpis at urna dictum luctus. Suspendisse convallis
          dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
          dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
          dapibus odio. Vivamus pretium nec odio cursus elementum. Suspendisse
          molestie ullamcorper ornare.
        </p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <div class="card ribbon-box">
      <div class="card-body">
        <div class="ribbon-two ribbon-two-pink"><span>Pink</span></div>
        <p class="mb-0">
          Quisque nec turpis at urna dictum luctus. Suspendisse convallis
          dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
          dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
          dapibus odio. Vivamus pretium nec odio cursus elementum. Suspendisse
          molestie ullamcorper ornare.
        </p>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="card ribbon-box">
      <div class="card-body">
        <div class="ribbon-two ribbon-two-purple"><span>Purple</span></div>
        <p class="mb-0">
          Quisque nec turpis at urna dictum luctus. Suspendisse convallis
          dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
          dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
          dapibus odio. Vivamus pretium nec odio cursus elementum. Suspendisse
          molestie ullamcorper ornare.
        </p>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="card ribbon-box">
      <div class="card-body">
        <div class="ribbon-two ribbon-two-dark"><span>Dark</span></div>
        <p class="mb-0">
          Quisque nec turpis at urna dictum luctus. Suspendisse convallis
          dignissim eros at volutpat. In egestas mattis dui. Aliquam mattis
          dictum aliquet. Nulla sapien mauris, eleifend et sem ac, commodo
          dapibus odio. Vivamus pretium nec odio cursus elementum. Suspendisse
          molestie ullamcorper ornare.
        </p>
      </div>
    </div>
  </div>
</div>
