// Minton_v10.1.0/Angular/Minton/src/app/views/base-ui/grid/grid.component.ts
import { Component } from '@angular/core'
import { PageTitleComponent } from '@component/page-title.component'

@Component({
  selector: 'app-grid',
  standalone: true,
  imports: [PageTitleComponent],
  templateUrl: './grid.component.html',
  styles: ``,
})
export class GridComponent {
  breadCrumbItems = [
    { label: 'Base UI', path: '/ui/grid' },
    { label: 'Grid System', path: '/ui/grid', active: true },
  ]
}

<app-page-title title="Grid System" [breadCrumbItems]="breadCrumbItems" />

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <h4 class="header-title">Grid options</h4>
        <p class="sub-header">
          See how aspects of the Bootstrap grid system work across multiple
          devices with a handy table.
        </p>

        <div class="table-responsive">
          <table class="table table-bordered table-striped mb-0">
            <thead>
              <tr>
                <th></th>
                <th class="text-center">
                  Extra small<br />
                  <small>&lt;576px</small>
                </th>
                <th class="text-center">
                  Small<br />
                  <small>≥576px</small>
                </th>
                <th class="text-center">
                  Medium<br />
                  <small>≥768px</small>
                </th>
                <th class="text-center">
                  Large<br />
                  <small>≥992px</small>
                </th>
                <th class="text-center">
                  Extra large<br />
                  <small>≥1200px</small>
                </th>
                <th class="text-center">
                  Extra large<br />
                  <small>≥1400px</small>
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th class="text-nowrap" scope="row">Max container width</th>
                <td>None (auto)</td>
                <td>540px</td>
                <td>720px</td>
                <td>960px</td>
                <td>1140px</td>
                <td>1320px</td>
              </tr>
              <tr>
                <th class="text-nowrap" scope="row">Class prefix</th>
                <td><code>.col-</code></td>
                <td><code>.col-sm-</code></td>
                <td><code>.col-md-</code></td>
                <td><code>.col-lg-</code></td>
                <td><code>.col-xl-</code></td>
                <td><code>.col-xxl-</code></td>
              </tr>
              <tr>
                <th class="text-nowrap" scope="row"># of columns</th>
                <td colspan="6">12</td>
              </tr>
              <tr>
                <th class="text-nowrap" scope="row">Gutter width</th>
                <td colspan="6">24px (12px on each side of a column)</td>
              </tr>
              <tr>
                <th class="text-nowrap" scope="row">Custom gutters</th>
                <td colspan="6">Yes</td>
              </tr>
              <tr>
                <th class="text-nowrap" scope="row">Nestable</th>
                <td colspan="6">Yes</td>
              </tr>
              <tr>
                <th class="text-nowrap" scope="row">Column ordering</th>
                <td colspan="6">Yes</td>
              </tr>
            </tbody>
          </table>
        </div>
        <!-- end table-responsive-->
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <h4 class="header-title mb-2">Grid Example</h4>

        <div class="grid-structure">
          <div class="row">
            <div class="col-lg-12">
              <div class="grid-container">col-lg-12</div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-11">
              <div class="grid-container">col-lg-11</div>
            </div>
            <div class="col-lg-1">
              <div class="grid-container">col-lg-1</div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-10">
              <div class="grid-container">col-lg-10</div>
            </div>
            <div class="col-lg-2">
              <div class="grid-container">col-lg-2</div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-9">
              <div class="grid-container">col-lg-9</div>
            </div>
            <div class="col-lg-3">
              <div class="grid-container">col-lg-3</div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-8">
              <div class="grid-container">col-lg-8</div>
            </div>
            <div class="col-lg-4">
              <div class="grid-container">col-lg-4</div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-7">
              <div class="grid-container">col-lg-7</div>
            </div>
            <div class="col-lg-5">
              <div class="grid-container">col-lg-5</div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="grid-container">col-lg-6</div>
            </div>
            <div class="col-lg-6">
              <div class="grid-container">col-lg-6</div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-5">
              <div class="grid-container">col-lg-5</div>
            </div>
            <div class="col-lg-7">
              <div class="grid-container">col-lg-7</div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-4">
              <div class="grid-container">col-lg-4</div>
            </div>
            <div class="col-lg-8">
              <div class="grid-container">col-lg-8</div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-3">
              <div class="grid-container">col-lg-3</div>
            </div>
            <div class="col-lg-9">
              <div class="grid-container">col-lg-9</div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-2">
              <div class="grid-container">col-lg-2</div>
            </div>
            <div class="col-lg-10">
              <div class="grid-container">col-lg-10</div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-1">
              <div class="grid-container">col-lg-1</div>
            </div>
            <div class="col-lg-11">
              <div class="grid-container">col-lg-11</div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-2">
              <div class="grid-container">col-lg-2</div>
            </div>
            <div class="col-lg-3">
              <div class="grid-container">col-lg-3</div>
            </div>
            <div class="col-lg-4">
              <div class="grid-container">col-lg-4</div>
            </div>
            <div class="col-lg-2">
              <div class="grid-container">col-lg-2</div>
            </div>
            <div class="col-lg-1">
              <div class="grid-container">col-lg-1</div>
            </div>
          </div>
        </div>
      </div>
      <!-- end card-body-->
    </div>
    <!-- end card-->
  </div>
  <!-- end col-->
</div>
<!-- end row-->

// Minton_v10.1.0/React.js/JS/src/app/(admin)/ui/grid/page.jsx
// components
import PageBreadcrumb from "@/components/PageBreadcrumb";
import { Card, CardBody, Col, Row } from "react-bootstrap";
import GridTable from "./GridTable";
const Grid = () => {
  return <>
      <PageBreadcrumb breadCrumbItems={[{
      label: "Base UI",
      path: "/ui/grid"
    }, {
      label: "Grid System",
      path: "/ui/grid",
      active: true
    }]} title={"Grid System"} />

      <Row>
        <Col xs={12}>
          <Card>
            <CardBody>
              <h4 className="header-title">Grid options</h4>
              <p className="sub-header">
                See how aspects of the Bootstrap grid system work across
                multiple devices with a handy table.
              </p>

              <GridTable />
            </CardBody>
          </Card>
        </Col>
      </Row>

      {/* example */}
      <Row>
        <Col xs={12}>
          <Card>
            <CardBody>
              <h4 className="header-title mb-3">Grid Example</h4>

              <div className="grid-structure">
                <Row>
                  <Col lg={12}>
                    <div className="grid-container">
                      &lt;Col lg={12}&gt; - col-lg-12
                    </div>
                  </Col>
                </Row>

                <Row>
                  <Col lg={11}>
                    <div className="grid-container">
                      &lt;Col lg={11}&gt; - col-lg-11
                    </div>
                  </Col>
                  <Col lg={1}>
                    <div className="grid-container">col-lg-1</div>
                  </Col>
                </Row>

                <Row>
                  <Col lg={10}>
                    <div className="grid-container">
                      &lt;Col lg={10}&gt; - col-lg-10
                    </div>
                  </Col>
                  <Col lg={2}>
                    <div className="grid-container">
                      &lt;Col lg={2}&gt; - col-lg-2
                    </div>
                  </Col>
                </Row>

                <Row>
                  <Col lg={9}>
                    <div className="grid-container">
                      &lt;Col lg={9}&gt; - col-lg-9
                    </div>
                  </Col>
                  <Col lg={3}>
                    <div className="grid-container">
                      &lt;Col lg={3}&gt; - col-lg-3
                    </div>
                  </Col>
                </Row>

                <Row>
                  <Col lg={8}>
                    <div className="grid-container">
                      &lt;Col lg={8}&gt; - col-lg-8
                    </div>
                  </Col>
                  <Col lg={4}>
                    <div className="grid-container">
                      &lt;Col lg={4}&gt; - col-lg-4
                    </div>
                  </Col>
                </Row>

                <Row>
                  <Col lg={7}>
                    <div className="grid-container">
                      &lt;Col lg={7}&gt; - col-lg-7
                    </div>
                  </Col>
                  <Col lg={5}>
                    <div className="grid-container">
                      &lt;Col lg={5}&gt; - col-lg-5
                    </div>
                  </Col>
                </Row>

                <Row>
                  <Col lg={6}>
                    <div className="grid-container">
                      &lt;Col lg={6}&gt; - col-lg-6
                    </div>
                  </Col>
                  <Col lg={6}>
                    <div className="grid-container">
                      &lt;Col lg={6}&gt; - col-lg-6
                    </div>
                  </Col>
                </Row>

                <Row>
                  <Col lg={5}>
                    <div className="grid-container">
                      &lt;Col lg={5}&gt; - col-lg-5
                    </div>
                  </Col>
                  <Col lg={7}>
                    <div className="grid-container">
                      &lt;Col lg={7}&gt; - col-lg-7
                    </div>
                  </Col>
                </Row>

                <Row>
                  <Col lg={4}>
                    <div className="grid-container">
                      &lt;Col lg={4}&gt; - col-lg-4
                    </div>
                  </Col>
                  <Col lg={8}>
                    <div className="grid-container">
                      &lt;Col lg={8}&gt; - col-lg-8
                    </div>
                  </Col>
                </Row>

                <Row>
                  <Col lg={3}>
                    <div className="grid-container">
                      &lt;Col lg={3}&gt; - col-lg-3
                    </div>
                  </Col>
                  <Col lg={9}>
                    <div className="grid-container">
                      &lt;Col lg={9}&gt; - col-lg-9
                    </div>
                  </Col>
                </Row>

                <Row>
                  <Col lg={2}>
                    <div className="grid-container">
                      &lt;Col lg={2}&gt; - col-lg-2
                    </div>
                  </Col>
                  <Col lg={10}>
                    <div className="grid-container">
                      &lt;Col lg={10}&gt; - col-lg-10
                    </div>
                  </Col>
                </Row>

                <Row>
                  <Col lg={1}>
                    <div className="grid-container">col-lg-1</div>
                  </Col>
                  <Col lg={11}>
                    <div className="grid-container">
                      &lt;Col lg={11}&gt; - col-lg-11
                    </div>
                  </Col>
                </Row>

                <Row>
                  <Col lg={2}>
                    <div className="grid-container">col-lg-2</div>
                  </Col>
                  <Col lg={3}>
                    <div className="grid-container">col-lg-3</div>
                  </Col>

                  <Col lg={4}>
                    <div className="grid-container">col-lg-4</div>
                  </Col>

                  <Col lg={2}>
                    <div className="grid-container">col-lg-2</div>
                  </Col>

                  <Col lg={1}>
                    <div className="grid-container">col-lg-1</div>
                  </Col>
                </Row>
              </div>
            </CardBody>
          </Card>
        </Col>
      </Row>
    </>;
};
export default Grid;
