// Minton_v10.1.0/Next.js/TS/src/app/(admin)/apps/contacts/profile/UserBox.tsx
"use client"
import React from "react";
import {Button, Card, Table} from "react-bootstrap";
import Link from "next/link";

// images
import profileImg from "@/assets/images/users/avatar-1.jpg";
import Image from "next/image";

const UserBox = () => {
    return (
        <Card className="text-center">
            <Card.Body>
                <Image
                    src={profileImg}
                    className="rounded-circle avatar-xl img-thumbnail"
                    alt=""
                    height={96}
                    width={96}
                />
                <h4 className="mt-3 mb-0">Nik G. Patel</h4>
                <p className="text-muted">@webdesigner</p>
                <Button
                    variant="success"
                    className="btn-xs waves-effect mb-2 waves-light"
                >
                    Follow
                </Button>{" "}
                <Button
                    variant="danger"
                    className="btn-xs waves-effect mb-2 waves-light"
                >
                    Message
                </Button>
                <div className="text-start mt-3">
                    <h4 className="font-13 text-uppercase">About Me :</h4>
                    <p className="text-muted font-13 mb-3">
                        Hi I&apos;m Johnathn Deo,has been the industry&apos;s standard dummy text ever
                        since the 1500s, when an unknown printer took a galley of type.
                    </p>

                    <Table borderless size="sm" responsive>
                        <tbody>
                        <tr>
                            <th scope="row">Full Name :</th>
                            <td className="text-muted">Nik G. Patel</td>
                        </tr>
                        <tr>
                            <th scope="row">Mobile :</th>
                            <td className="text-muted">(123) 123 1234</td>
                        </tr>
                        <tr>
                            <th scope="row">Email :</th>
                            <td className="text-muted">user@email.domain</td>
                        </tr>
                        <tr>
                            <th scope="row">Location :</th>
                            <td className="text-muted">USA</td>
                        </tr>
                        </tbody>
                    </Table>
                </div>
                <ul className="social-list list-inline mb-0">
                    <li className="list-inline-item">
                        <Link href="" className="social-list-item border-purple text-purple">
                            <i className="mdi mdi-facebook"></i>
                        </Link>
                    </li>
                    <li className="list-inline-item">
                        <Link href="" className="social-list-item border-danger text-danger">
                            <i className="mdi mdi-google"></i>
                        </Link>
                    </li>
                    <li className="list-inline-item">
                        <Link href="" className="social-list-item border-info text-info">
                            <i className="mdi mdi-twitter"></i>
                        </Link>
                    </li>
                    <li className="list-inline-item">
                        <Link
                            href=""
                            className="social-list-item border-secondary text-secondary"
                        >
                            <i className="mdi mdi-github"></i>
                        </Link>
                    </li>
                </ul>
            </Card.Body>
        </Card>
    );
};

export default UserBox;

// Minton_v10.1.0/Angular/Minton/src/app/views/contacts/profile/components/user-box/user-box.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'profile-user-box',
  standalone: true,
  imports: [],
  templateUrl: './user-box.component.html',
  styles: ``,
})
export class UserBoxComponent {}

<div class="card text-center">
  <div class="card-body">
    <img
      src="assets/images/users/avatar-1.jpg"
      class="rounded-circle avatar-xl img-thumbnail"
      alt="profile-image"
    />

    <h4 class="mt-3 mb-0">Nik G. Patel</h4>
    <p class="text-muted">&#64;webdesigner</p>

    <button
      type="button"
      class="btn btn-success btn-xs waves-effect mb-2 waves-light me-1"
    >
      Follow
    </button>
    <button
      type="button"
      class="btn btn-danger btn-xs waves-effect mb-2 waves-light"
    >
      Message
    </button>

    <div class="text-start mt-3">
      <h4 class="font-13 text-uppercase">About Me :</h4>
      <p class="text-muted font-13 mb-3">
        Hi I'm Johnathn Deo,has been the industry's standard dummy text ever
        since the 1500s, when an unknown printer took a galley of type.
      </p>

      <div class="table-responsive">
        <table class="table table-borderless table-sm">
          <tbody>
            <tr>
              <th scope="row">Full Name :</th>
              <td class="text-muted">Nik G. Patel</td>
            </tr>
            <tr>
              <th scope="row">Mobile :</th>
              <td class="text-muted">(123) 123 1234</td>
            </tr>
            <tr>
              <th scope="row">Email :</th>
              <td class="text-muted">user&#64;email.domain</td>
            </tr>
            <tr>
              <th scope="row">Location :</th>
              <td class="text-muted">USA</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <ul class="social-list list-inline mb-0">
      <li class="list-inline-item">
        <a
          href="javascript: void(0);"
          class="social-list-item border-purple text-purple"
          ><i class="mdi mdi-facebook"></i
        ></a>
      </li>
      <li class="list-inline-item">
        <a
          href="javascript: void(0);"
          class="social-list-item border-danger text-danger"
          ><i class="mdi mdi-google"></i
        ></a>
      </li>
      <li class="list-inline-item">
        <a
          href="javascript: void(0);"
          class="social-list-item border-info text-info"
          ><i class="mdi mdi-twitter"></i
        ></a>
      </li>
      <li class="list-inline-item">
        <a
          href="javascript: void(0);"
          class="social-list-item border-secondary text-secondary"
          ><i class="mdi mdi-github"></i
        ></a>
      </li>
    </ul>
  </div>
</div>
