// Minton_v10.1.0/React.js/TS/src/app/(admin)/charts/apex/PieChart.tsx


import {ApexOptions} from "apexcharts";
import {Card} from "react-bootstrap";


import ReactApexChart from "react-apexcharts";

const colors1 = ["#3e60d5", "#6c757d", "#47ad77", "#fa5c7c", "#e3eaef"];

const PieChart = () => {
    const SimplePieOpt: ApexOptions = {
        chart: {
            height: 320,
            type: "pie",
        },
        series: [44, 55, 41, 17, 15],
        labels: ["Series 1", "Series 2", "Series 3", "Series 4", "Series 5"],
        colors: colors1,
        legend: {
            show: true,
            position: "bottom",
            horizontalAlign: "center",
            // verticalAlign: "middle",
            floating: false,
            fontSize: "14px",
            offsetX: 0,
            offsetY: 7,
        }
    };


    return (
        <Card>
            <Card.Body>
                <h5 className="header-title mb-0">Basic bar chart</h5>
                <div className="pt-3">
                    <ReactApexChart
                        options={SimplePieOpt}
                        series={SimplePieOpt.series}
                        type="pie"
                        height={320}
                        
                    />
                </div>
            </Card.Body>
        </Card>
    );
};

export default PieChart;

// Minton_v10.1.0/Angular/Minton/src/app/views/charts/apex/components/pie-chart/pie-chart.component.ts
import { Component } from '@angular/core'
import type { ChartOptions } from '@common/apexchart.model'
import { CustomCardPortletComponent } from '@component/custom-card-portlet/custom-card-portlet.component'
import { NgApexchartsModule } from 'ng-apexcharts'

@Component({
  selector: 'pie-chart',
  standalone: true,
  imports: [NgApexchartsModule, CustomCardPortletComponent],
  templateUrl: './pie-chart.component.html',
  styles: ``,
})
export class PieChartComponent {
  apexpie1Chart: Partial<ChartOptions> = {
    chart: {
      height: 320,
      type: 'pie',
    },
    series: [44, 55, 41, 17, 15],
    labels: ['Series 1', 'Series 2', 'Series 3', 'Series 4', 'Series 5'],
    colors: ['#3bafda', '#1abc9c', '#f7b84b', '#6559cc', '#f672a7'],
    legend: {
      show: true,
      position: 'bottom',
      horizontalAlign: 'center',
      floating: false,
      fontSize: '14px',
      offsetX: 0,
      offsetY: 7,
    },
    responsive: [
      {
        breakpoint: 600,
        options: {
          chart: {
            height: 240,
          },
          legend: {
            show: false,
          },
        },
      },
    ],
  }
}

<custom-card-portlet
  cardTitle="Simple Pie Chart"
  cardTitleClass="header-title mb-0"
>
  <div
    id="apex-pie-1"
    class="apex-charts"
    data-colors="#3bafda,#1abc9c,#f7b84b,#6559cc,#f672a7"
  >
    <apx-chart
      [chart]="apexpie1Chart.chart!"
      [series]="apexpie1Chart.series!"
      [legend]="apexpie1Chart.legend!"
      [colors]="apexpie1Chart.colors!"
      [labels]="apexpie1Chart.labels!"
      [responsive]="apexpie1Chart.responsive!"
    />
  </div>
</custom-card-portlet>
