// Minton_v10.1.0/React.js/JS/src/app/(admin)/dashboard/analytics/SocialMediaTraffic.jsx
import { Card, CardBody, ProgressBar } from "react-bootstrap";
import { Link } from "react-router-dom";

// types

const SocialMediaTraffic = ({
  socialMediaTraffic
}) => {
  return <Card>
      <CardBody>
        <div className="clearfix">
          <Link to="" className="p-0 float-end mb-3">
            Export <i className="mdi mdi-download ms-1"></i>
          </Link>
          <h4 className="header-title">Social Media Traffic</h4>
        </div>

        <div className="table-responsive">
          <table className="table table-sm table-centered mb-0 font-14">
            <thead className="table-light">
              <tr>
                <th>Network</th>
                <th>Visits</th>
                <th style={{
                width: "40%"
              }}></th>
              </tr>
            </thead>
            <tbody>
              {(socialMediaTraffic || []).map((item, index) => {
              return <tr key={index}>
                    <td>{item.network}</td>
                    <td>{item.visits}</td>
                    <td>
                      <ProgressBar now={item.progress} style={{
                    height: "3px"
                  }} />
                    </td>
                  </tr>;
            })}
            </tbody>
          </table>
        </div>
      </CardBody>
    </Card>;
};
export default SocialMediaTraffic;

// Minton_v10.1.0/Angular/Minton/src/app/views/dashboard/analytics/components/social-media-traffic/social-media-traffic.component.ts
import { Component } from '@angular/core'
import { socialMediaTraffic } from '../../data'
import { NgbProgressbarModule } from '@ng-bootstrap/ng-bootstrap'

@Component({
  selector: 'analytics-social-media-traffic',
  standalone: true,
  imports: [NgbProgressbarModule],
  templateUrl: './social-media-traffic.component.html',
  styles: ``,
})
export class SocialMediaTrafficComponent {
  socialList = socialMediaTraffic
}

<div class="card">
  <div class="card-body">
    <div class="clearfix">
      <a href="javascript:void(0);" class="p-0 float-end mb-3"
        >Export <i class="mdi mdi-download ms-1"></i
      ></a>
      <h4 class="header-title">Social Media Traffic</h4>
    </div>

    <div class="table-responsive">
      <table class="table table-sm table-centered mb-0 font-14">
        <thead class="table-light">
          <tr>
            <th>Network</th>
            <th>Visits</th>
            <th style="width: 40%"></th>
          </tr>
        </thead>
        <tbody>
          @for (item of socialList; track $index) {
            <tr>
              <td>{{ item.network }}</td>
              <td>{{ item.visits }}</td>
              <td>
                <ngb-progressbar [value]="item.progress" style="height: 3px" />
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
    <!-- end table-responsive-->
  </div>
  <!-- end card-body-->
</div>
<!-- end card-->
