// Minton_v10.1.0/Angular/Minton/src/app/views/apps/widgets/components/statistics-chart-widget6/statistics-chart-widget6.component.ts
import { Component } from '@angular/core'
import type { ChartOptions } from '@common/apexchart.model'
import { currency } from '@common/constants'
import { NgApexchartsModule } from 'ng-apexcharts'

@Component({
  selector: 'statistics-chart-widget6',
  standalone: true,
  imports: [NgApexchartsModule],
  templateUrl: './statistics-chart-widget6.component.html',
  styles: ``,
})
export class StatisticsChartWidget6Component {
  currency = currency
  sparkline6Chart: Partial<ChartOptions> = {
    chart: {
      type: 'line',
      height: 165,
      toolbar: {
        show: false,
      },
      sparkline: {
        enabled: true,
      },
    },
    series: [
      {
        data: [50, 23, 43, 35, 44, 45, 56, 37, 40],
      },
    ],
    stroke: {
      curve: 'straight',
      width: [1],
    },
    fill: {
      type: 'solid',
      opacity: [0.3],
    },
    grid: {
      padding: {
        left: -9,
        right: 0,
      },
    },
    colors: ['#3bafda'],
    xaxis: {
      labels: {
        show: false,
      },
      axisTicks: {
        show: false,
      },
    },
    yaxis: {
      labels: {
        show: false,
      },
    },
    legend: {
      show: false,
    },
    tooltip: {
      fixed: {
        enabled: false,
      },
      x: {
        show: false,
      },
      y: {
        title: {
          formatter: (seriesName: string) => {
            return ''
          },
        },
      },
      marker: {
        show: false,
      },
    },
  }
}

<div class="card">
  <div class="card-body">
    <h4 class="header-title mb-3">Sales Status</h4>

    <div class="widget-chart text-center">
      <div id="sparkline5" data-colors="#3bafda" class="text-center">
        <apx-chart
          [chart]="sparkline6Chart.chart!"
          [series]="sparkline6Chart.series!"
          [stroke]="sparkline6Chart.stroke!"
          [grid]="sparkline6Chart.grid!"
          [fill]="sparkline6Chart.fill!"
          [colors]="sparkline6Chart.colors!"
          [xaxis]="sparkline6Chart.xaxis!"
          [yaxis]="sparkline6Chart.yaxis!"
          [legend]="sparkline6Chart.legend!"
          [tooltip]="sparkline6Chart.tooltip!"
        />
      </div>

      <div class="row mt-3">
        <div class="col-4">
          <p class="text-muted font-15 mb-1 text-truncate">Target</p>
          <h4>{{ currency }}1022</h4>
        </div>
        <div class="col-4">
          <p class="text-muted font-15 mb-1 text-truncate">Last week</p>
          <h4>{{ currency }}538</h4>
        </div>
        <div class="col-4">
          <p class="text-muted font-15 mb-1 text-truncate">Last Month</p>
          <h4>{{ currency }}988</h4>
        </div>
      </div>
    </div>
  </div>
</div>

// Minton_v10.1.0/React.js/JS/src/app/(admin)/widgets/StatisticsChartWidget6.jsx
import ReactApexChart from "react-apexcharts";
// components
import { ChartStatistics } from "@/components";
import { Card, CardBody, Col, Row } from "react-bootstrap";
const StatisticsChartWidget6 = () => {
  /*
    initial options
    */
  const options = {
    chart: {
      type: "line",
      toolbar: {
        show: false
      },
      sparkline: {
        enabled: true
      }
    },
    stroke: {
      curve: "straight",
      width: [1]
    },
    fill: {
      type: "solid",
      opacity: [0.3]
    },
    grid: {
      padding: {
        left: -9,
        right: 0
      }
    },
    colors: ["#3bafda"],
    xaxis: {
      labels: {
        show: false
      },
      axisTicks: {
        show: false
      }
    },
    yaxis: {
      labels: {
        show: false
      }
    },
    legend: {
      show: false
    },
    tooltip: {
      fixed: {
        enabled: false
      },
      x: {
        show: false
      },
      y: {
        title: {
          formatter: () => {
            return "";
          }
        }
      },
      marker: {
        show: false
      }
    }
  };
  const series = [{
    data: [50, 23, 43, 35, 44, 45, 56, 37, 40]
  }];
  return <Card>
      <CardBody>
        <h4 className="header-title mb-3">Total Revenue</h4>

        <div className="widget-chart text-center">
          <ReactApexChart type="area" options={options} series={series} height={165} className="apex-charts mt-0" />

          <Row className="mt-3">
            <Col xs={4}>
              <ChartStatistics title="Target" stats="$1000" />
            </Col>
            <Col xs={4}>
              <ChartStatistics title="Last week" stats="$523" />
            </Col>
            <Col xs={4}>
              <ChartStatistics title="Last Month" stats="$965" />
            </Col>
          </Row>
        </div>
      </CardBody>
    </Card>;
};
export default StatisticsChartWidget6;
