// Minton_v10.1.0/Angular/Minton/src/app/components/statistics-widget/statistics-widget.component.ts
import { Component, Input } from '@angular/core'
import { CountUpModule } from 'ngx-countup'

type Trend = {
  value: string
  title: string
  icon: string
  variant: string
}

@Component({
  selector: 'app-statistics-widget',
  standalone: true,
  imports: [CountUpModule],
  templateUrl: './statistics-widget.component.html',
  styles: ``,
})
export class StatisticsWidgetComponent {
  @Input() icon!: string
  @Input() stats!: number
  @Input() title!: string
  @Input() trend!: Trend
  @Input() counterOptions?: any
}

<div class="card">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <div>
        <h5
          class="text-muted fw-normal mt-0 text-truncate"
          title="Campaign Sent"
        >
          {{ title }}
        </h5>
        <h3 class="my-2 py-1">
          <span [countUp]="stats" [options]="counterOptions"></span>
        </h3>
        <p class="mb-0 text-muted">
          <span class="text-{{ trend.variant }} me-2"
            ><span [class]="trend.icon"></span> {{ trend.value }}</span
          >
          <span class="text-nowrap"> {{ trend.title }}</span>
        </p>
      </div>
      <div class="avatar-sm">
        <span class="avatar-title bg-soft-primary rounded">
          <i class="{{ icon }} font-20 text-primary"></i>
        </span>
      </div>
    </div>
  </div>
</div>

// Minton_v10.1.0/Next.js/TS/src/components/StatisticsWidget.tsx
"use client"
import React from "react";
import CountUp from "react-countup";
import classNames from "classnames";

interface StatisticsWidgetProps {
  icon: string;
  stats: string;
  title: string;
  trend: {
    value: string;
    title: string;
    icon: string;
    variant: string;
  };
  counterOptions?: any;
}

const StatisticsWidget = ({
  icon,
  stats,
  title,
  trend,
  counterOptions,
}: StatisticsWidgetProps) => {
  return (
    <div className="card">
      <div className="card-body">
        <div className="d-flex align-items-start justify-content-between">
          <div>
            <h5
              className="text-muted fw-normal mt-0 text-truncate"
              title="Campaign Sent"
            >
              {title}
            </h5>
            <h3 className="my-2 py-1">
              <span>
                <CountUp
                  duration={1}
                  end={stats}
                  {...counterOptions}
                  separator={","}
                />
              </span>
            </h3>
            <p className="mb-0 text-muted">
              <span className={classNames("me-2", "text-" + trend.variant)}>
                <span className={trend.icon}></span>
                {trend.value}
              </span>
              <span className="text-nowrap">{trend.title}</span>
            </p>
          </div>
          <div className="avatar-sm">
            <span className="avatar-title bg-soft-primary rounded">
              <i className={classNames("font-20", "text-primary", icon)}></i>
            </span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default StatisticsWidget;
