// Minton_v10.1.0/Angular/Minton/src/app/views/dashboard/analytics/components/channels/channels.component.ts
import { Component } from '@angular/core'
import { channels } from '../../data'
import { NgbProgressbarModule } from '@ng-bootstrap/ng-bootstrap'

@Component({
  selector: 'analytics-channels',
  standalone: true,
  imports: [NgbProgressbarModule],
  templateUrl: './channels.component.html',
  styles: ``,
})
export class ChannelsComponent {
  channelList = channels
}

<div class="card">
  <div class="card-body">
    <div class="clearfix">
      <a href="javascript:void(0);" class="p-0 float-end mb-3"
        >Export <i class="mdi mdi-download ms-1"></i
      ></a>
      <h4 class="header-title">Channels</h4>
    </div>

    <div class="table-responsive">
      <table class="table table-sm table-centered mb-0 font-14">
        <thead class="table-light">
          <tr>
            <th>Channel</th>
            <th>Visits</th>
            <th style="width: 40%"></th>
          </tr>
        </thead>
        <tbody>
          @for (item of channelList; track $index) {
            <tr>
              <td>{{ item.channel }}</td>
              <td>{{ item.visits }}</td>
              <td>
                <ngb-progressbar
                  [type]="item.progress.variant!"
                  [value]="item.progress.value"
                  style="height: 3px"
                />
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
    <!-- end table-responsive-->
  </div>
  <!-- end card-body-->
</div>
<!-- end card-->

// Minton_v10.1.0/Next.js/TS/src/app/(admin)/dashboard/analytics/Channels.tsx
"use client"
import React from "react";
import { Card, ProgressBar } from "react-bootstrap";
import Link from "next/link";

// types
import { ChannelsTypes } from "./data";

interface ChannelsProps {
  channels: ChannelsTypes[];
}

const Channels = ({ channels }: ChannelsProps) => {
  return (
    <div className="card">
      <div className="card-body">
        <div className="clearfix">
          <Link href="" className="p-0 float-end mb-3">
            Export <i className="mdi mdi-download ms-1"></i>
          </Link>
          <h4 className="header-title">Channels</h4>
        </div>

        <div className="table-responsive">
          <table className="table table-sm table-centered mb-0 font-14">
            <thead className="table-light">
              <tr>
                <th>Channel</th>
                <th>Visits</th>
                <th style={{ width: "40%" }}></th>
              </tr>
            </thead>
            <tbody>
              {(channels || []).map((item, index) => {
                return (
                  <tr key={index}>
                    <td>{item.channel}</td>
                    <td>{item.visits}</td>
                    <td>
                      <ProgressBar
                        now={item.progress.value}
                        variant={item.progress.variant}
                        style={{ height: "3px" }}
                      />
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default Channels;
