// Minton_v10.1.0/React.js/JS/src/app/(admin)/widgets/StatisticsChartWidget4.jsx
import ReactApexChart from "react-apexcharts";

// components
import { ChartStatistics } from "@/components";
import { Card, CardBody, Col, Row } from "react-bootstrap";
const StatisticsChartWidget4 = () => {
  const options = {
    chart: {
      type: "pie",
      sparkline: {
        enabled: true
      }
    },
    colors: ["#e3eaef", "#3bafda", "#1abc9c", "#f1556c"],
    legend: {
      show: false
    },
    dataLabels: {
      enabled: false
    },
    tooltip: {
      fixed: {
        enabled: false
      },
      x: {
        show: false
      },
      y: {
        title: {
          formatter: () => {
            return "";
          }
        }
      },
      marker: {
        show: false
      }
    }
  };
  const series = [20, 40, 30, 10];
  return <Card>
      <CardBody>
        <h4 className="header-title mb-3">Sales Status</h4>

        <div className="widget-chart text-center">
          <ReactApexChart type="pie" options={options} series={series} height={168} className="apex-charts mt-0" />

          <Row className="mt-3">
            <Col xs={4}>
              <ChartStatistics title="Target" stats="$982" />
            </Col>
            <Col xs={4}>
              <ChartStatistics title="Last week" stats="$525" />
            </Col>
            <Col xs={4}>
              <ChartStatistics title="Last Month" stats="$937" />
            </Col>
          </Row>
        </div>
      </CardBody>
    </Card>;
};
export default StatisticsChartWidget4;

// Minton_v10.1.0/Angular/Minton/src/app/views/apps/widgets/components/statistics-chart-widget4/statistics-chart-widget4.component.ts
import { Component } from '@angular/core'
import type { ChartOptions } from '@common/apexchart.model'
import { currency } from '@common/constants'
import { NgApexchartsModule } from 'ng-apexcharts'

@Component({
  selector: 'statistics-chart-widget4',
  standalone: true,
  imports: [NgApexchartsModule],
  templateUrl: './statistics-chart-widget4.component.html',
  styles: ``,
})
export class StatisticsChartWidget4Component {
  currency = currency
  sparkline3Chart: Partial<ChartOptions> = {
    chart: {
      type: 'pie',
      sparkline: {
        enabled: true,
      },
      height: 168,
    },
    series: [20, 40, 30, 10],
    colors: ['#e3eaef', '#3bafda', '#1abc9c', '#f1556c'],
    legend: {
      show: false,
    },
    dataLabels: {
      enabled: false,
    },
    tooltip: {
      fixed: {
        enabled: false,
      },
      x: {
        show: false,
      },
      y: {
        title: {
          formatter: (seriesName: string) => {
            return ''
          },
        },
      },
      marker: {
        show: false,
      },
    },
  }
}

<div class="card">
  <div class="card-body">
    <h4 class="header-title mb-3">Recent Users</h4>

    <div class="widget-chart text-center">
      <div
        id="sparkline3"
        data-colors="#e3eaef,#3bafda,#1abc9c,#f1556c"
        class="text-center"
      >
        <apx-chart
          [chart]="sparkline3Chart.chart!"
          [series]="sparkline3Chart.series!"
          [colors]="sparkline3Chart.colors!"
          [legend]="sparkline3Chart.legend!"
          [dataLabels]="sparkline3Chart.dataLabels!"
          [tooltip]="sparkline3Chart.tooltip!"
        />
      </div>
      <div class="row mt-3">
        <div class="col-4">
          <p class="text-muted font-15 mb-1 text-truncate">Target</p>
          <h4>{{ currency }}982</h4>
        </div>
        <div class="col-4">
          <p class="text-muted font-15 mb-1 text-truncate">Last week</p>
          <h4>{{ currency }}525</h4>
        </div>
        <div class="col-4">
          <p class="text-muted font-15 mb-1 text-truncate">Last Month</p>
          <h4>{{ currency }}937</h4>
        </div>
      </div>
    </div>
  </div>
</div>
