// Minton_v10.1.0/Angular/Starter-Kit/src/app/layouts/auth-layout/auth-layout.component.ts
import { Component } from '@angular/core'
import { RouterModule } from '@angular/router'
import { credits, currentYear } from '@common/constants'

@Component({
  selector: 'app-auth-layout',
  standalone: true,
  imports: [RouterModule],
  template: `
    <div class="account-pages mt-5 mb-5">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-8 col-lg-6 col-xl-4">
            <router-outlet />
          </div>
        </div>
      </div>
    </div>
    <footer class="footer footer-alt">
      {{ year }} &copy; Minton theme by
      <a href="javascript:void(0);" class="text-dark">{{ credits.name }}</a>
    </footer>
  `,
  styles: ``,
})
export class AuthLayoutComponent {
  year = currentYear
  credits = credits
}

// Minton_v10.1.0/React.js/JS/src/components/AuthLayout.jsx
import { Container, Row, Col, Card, CardBody } from "react-bootstrap";

// images
import LogoDark from "@/assets/images/logo-dark.png";
import LogoLight from "@/assets/images/logo-light.png";
import { Link } from "react-router-dom";
const AuthLayout = ({
  helpText,
  bottomLinks,
  children,
  isCombineForm
}) => {
  return <>
      <div className="account-pages mt-5 mb-5">
        <Container>
          <Row className="justify-content-center">
            <Col md={8} lg={6} className={`col-xl-${isCombineForm ? 9 : 4}`}>
              <Card>
                <CardBody className="p-4">
                  <div className="text-center w-75 m-auto">
                    <div className="auth-logo">
                      <Link to="/" className="logo logo-dark text-center">
                        <span className="logo-lg">
                          <img src={LogoDark} alt="logo" height={22} width={119} />
                        </span>
                      </Link>

                      <Link to="/" className="logo logo-light text-center">
                        <span className="logo-lg">
                          <img src={LogoLight} alt="logo" height={22} width={119} />
                        </span>
                      </Link>
                    </div>
                    {helpText && <p className="text-muted mb-4 mt-3">{helpText}</p>}
                  </div>
                  {children}
                </CardBody>
              </Card>

              {/* bottom links */}
              {bottomLinks}
            </Col>
          </Row>
        </Container>
      </div>

      <footer className="footer footer-alt">
        {new Date().getFullYear()} &copy; Minton theme by{" "}
        <Link to="https://coderthemes.com/" className="text-dark" target="_blank">
          Coderthemes
        </Link>
      </footer>
    </>;
};
export default AuthLayout;
