// Minton_v10.1.0/Angular/Minton/src/app/components/statistics-chart-widget/statistics-chart-widget.component.ts
import { DecimalPipe } from '@angular/common'
import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core'
import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap'
import { NgApexchartsModule } from 'ng-apexcharts'
import { CountUpModule } from 'ngx-countup'

@Component({
  selector: 'app-statistics-chart-widget',
  standalone: true,
  imports: [NgApexchartsModule, CountUpModule, NgbDropdownModule],
  templateUrl: './statistics-chart-widget.component.html',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class StatisticsChartWidgetComponent {
  @Input() hasHeader?: boolean = false
  @Input() title?: string = ''
  @Input() color: string = '#727cf5' // default color
  @Input() data: number = 0
  @Input() stats: number = 0
  @Input() description: string = ''
  @Input() counterOptions?: any

  apexOpts: any
  apexData: number[]

  constructor() {
    this.apexData = [this.data]
  }

  ngOnChanges(): void {
    this.apexOpts = {
      chart: {
        type: 'radialBar',
        width: 82,
        height: 82,
        sparkline: { enabled: true },
      },
      dataLabels: { enabled: false },
      plotOptions: {
        radialBar: {
          hollow: { margin: 0, size: '77%' },
          track: { margin: 0 },
          dataLabels: {
            name: { show: false },
            value: {
              show: true,
              color: this.color,
              fontSize: '14px',
              offsetY: 5,
              formatter: (val: number) => String(val),
            },
          },
        },
      },
      states: {
        hover: { filter: { type: 'none' } },
      },
      colors: [this.color],
    }

    // Update data series
    this.apexData = [this.data]
  }
}

<div class="card">
  <div class="card-body">
    @if (hasHeader) {
      <div ngbDropdown class="dropdown float-end">
        <a
          ngbDropdownToggle
          href="javascript:void(0);"
          class="arrow-none card-drop"
        >
          <i class="mdi mdi-dots-horizontal"></i>
        </a>
        <div ngbDropdownMenu class="dropdown-menu-end">
          <!-- item-->
          <a href="javascript:void(0);" class="dropdown-item">Action</a>
          <!-- item-->
          <a href="javascript:void(0);" class="dropdown-item">Another action</a>
          <!-- item-->
          <a href="javascript:void(0);" class="dropdown-item">Something else</a>
          <!-- item-->
          <a href="javascript:void(0);" class="dropdown-item">Separated link</a>
        </div>
      </div>
      <h4 class="header-title mt-0 mb-3">{{ title }}</h4>
    }

    <div class="d-flex justify-content-between align-items-center">
      <div dir="ltr">
        <apx-chart
          [series]="apexData"
          [chart]="apexOpts.chart"
          [plotOptions]="apexOpts.plotOptions"
          [dataLabels]="apexOpts.dataLabels"
          [colors]="apexOpts.colors"
          class="apex-charts"
          [width]="72"
          [height]="hasHeader ? 75 : 82"
        ></apx-chart>
      </div>
      <div class="text-end">
        <h3 class="mb-1 mt-0">
          <span [countUp]="stats" [options]="counterOptions!"></span>
        </h3>
        <p class="text-muted mb-0">{{ description }}</p>
      </div>
    </div>
  </div>
</div>

// Minton_v10.1.0/React.js/JS/src/components/StatisticsChartWidget.jsx
;
import { Card, CardBody, Dropdown } from "react-bootstrap";
import CountUp from "react-countup";
import classNames from "classnames";
import ReactApexChart from "react-apexcharts";
const StatisticsChartWidget = ({
  hasHeader,
  title,
  color,
  data,
  stats,
  description,
  counterOptions
}) => {
  const apexOpts = {
    chart: {
      type: "radialBar",
      width: 65,
      height: 65,
      sparkline: {
        enabled: true
      }
    },
    dataLabels: {
      enabled: false
    },
    plotOptions: {
      radialBar: {
        hollow: {
          margin: 0,
          size: "75%"
        },
        track: {
          margin: 0
        },
        dataLabels: {
          name: {
            show: false
          },
          value: {
            show: true,
            color: color,
            fontSize: "14px",
            offsetY: 5,
            formatter: val => {
              return String(val);
            }
          }
        }
      }
    },
    states: {
      hover: {
        filter: {
          type: "none"
        }
      }
    },
    colors: [color]
  };
  const apexData = [data];
  return <Card>
      <CardBody>
        {hasHeader && <>
            <Dropdown className="float-end">
              <Dropdown.Toggle as="a" className="arrow-none cursor-pointer card-drop">
                <i className="mdi mdi-dots-horizontal"></i>
              </Dropdown.Toggle>
              <Dropdown.Menu align="end">
                <Dropdown.Item>Action</Dropdown.Item>
                <Dropdown.Item>Another action</Dropdown.Item>
                <Dropdown.Item>Something else</Dropdown.Item>
                <Dropdown.Item>Separated link</Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>

            <h4 className="header-title mt-0">{title}</h4>
          </>}

        <div className={classNames({
        "mt-3": hasHeader
      })}>
          <div className="d-flex align-items-start">
            <div dir="ltr">
              <ReactApexChart options={apexOpts} series={apexData} type="radialBar" height={hasHeader ? 75 : 82} width={72} className="apex-charts" />
            </div>
            <div className="flex-1 text-end align-self-center">
              <h3 className="mt-0 mb-1">
                {hasHeader ? stats : <span>
                    <CountUp duration={1} end={stats} {...counterOptions} separator={","} />
                  </span>}
              </h3>
              <p className="text-muted mb-0">{description}</p>
            </div>
          </div>
        </div>
      </CardBody>
    </Card>;
};
export default StatisticsChartWidget;
