// Minton_v10.1.0/React.js/JS/src/app/(admin)/charts/apex/BarChart.jsx
import { Card } from "react-bootstrap";
import { basicBarChartData } from "@/app/(admin)/charts/apex/data";
import ReactApexChart from "react-apexcharts";
const BarChart = () => {
  const options = {
    chart: {
      height: 380,
      type: "bar",
      toolbar: {
        show: false
      }
    },
    colors: ["#1abc9c"],
    plotOptions: {
      bar: {
        horizontal: true
      }
    },
    dataLabels: {
      enabled: false
    },
    states: {
      hover: {
        filter: {
          type: "none"
        }
      }
    },
    grid: {
      borderColor: "#f1f3fa"
    },
    xaxis: {
      categories: ["South Korea", "Canada", "United Kingdom", "Netherlands", "Italy", "France", "Japan", "United States", "China", "Germany"]
    }
  };
  const series = [{
    data: basicBarChartData.data
  }];
  return <Card>
            <Card.Body>
                <h5 className="header-title mb-0">Basic bar chart</h5>
                <div className="pt-3">
                    <ReactApexChart options={options} series={series} type="bar" height={380} />
                </div>
            </Card.Body>
        </Card>;
};
export default BarChart;

// Minton_v10.1.0/Angular/Minton/src/app/views/charts/apex/components/bar-chart/bar-chart.component.ts
import { Component } from '@angular/core'
import type { ChartOptions } from '@common/apexchart.model'
import { CustomCardPortletComponent } from '@component/custom-card-portlet/custom-card-portlet.component'
import { NgApexchartsModule } from 'ng-apexcharts'

@Component({
  selector: 'bar-chart',
  standalone: true,
  imports: [NgApexchartsModule, CustomCardPortletComponent],
  templateUrl: './bar-chart.component.html',
  styles: ``,
})
export class BarChartComponent {
  apexbar1Chart: Partial<ChartOptions> = {
    chart: {
      height: 380,
      type: 'bar',
      toolbar: {
        show: false,
      },
    },
    plotOptions: {
      bar: {
        horizontal: true,
      },
    },
    dataLabels: {
      enabled: false,
    },
    series: [
      {
        data: [400, 430, 448, 470, 540, 580, 690, 1100, 1200, 1380],
      },
    ],
    colors: ['#1abc9c'],
    xaxis: {
      categories: [
        'South Korea',
        'Canada',
        'United Kingdom',
        'Netherlands',
        'Italy',
        'France',
        'Japan',
        'United States',
        'China',
        'Germany',
      ],
    },
    states: {
      hover: {
        filter: {
          type: 'none',
        },
      },
    },
    grid: {
      borderColor: '#f1f3fa',
    },
  }
}

<custom-card-portlet
  cardTitle="Basic Bar Chart"
  cardTitleClass="header-title mb-0"
>
  <div id="apex-bar-1" class="apex-charts" data-colors="#1abc9c">
    <apx-chart
      [chart]="apexbar1Chart.chart!"
      [plotOptions]="apexbar1Chart.plotOptions!"
      [dataLabels]="apexbar1Chart.dataLabels!"
      [series]="apexbar1Chart.series!"
      [colors]="apexbar1Chart.colors!"
      [xaxis]="apexbar1Chart.xaxis!"
      [states]="apexbar1Chart.states!"
      [grid]="apexbar1Chart.grid!"
    />
  </div>
</custom-card-portlet>
