// Minton_v10.1.0/React.js/TS/src/app/(admin)/dashboard/crm/RecentLeads.tsx


import { Card, CardBody, Dropdown } from "react-bootstrap";
import classNames from "classnames";


interface RecentLeadsProps {
  recentLeads: {
    id: number;
    name: string;
    avatar: string;
    email: string;
    status: string;
  }[];
}

const RecentLeads = ({ recentLeads }: RecentLeadsProps) => {
  return (
    <>
      <Card>
        <CardBody>
          <Dropdown className="float-end" align="end">
            <Dropdown.Toggle as="a" className=" arrow-none card-drop">
              <i className="mdi mdi-dots-vertical"></i>
            </Dropdown.Toggle>
            <Dropdown.Menu>
              <Dropdown.Item>Settings</Dropdown.Item>
              <Dropdown.Item>Action</Dropdown.Item>
            </Dropdown.Menu>
          </Dropdown>

          <h4 className="header-title mb-4">Recent Leads</h4>

          {(recentLeads || []).map((item, index) => {
            return (
              <div
                key={index}
                className={classNames("d-flex", { "mt-3": index !== 0 })}
              >
                <img
                  className="avatar-sm align-self-center me-3 rounded-circle"
                  src={item.avatar}
                  alt=""
                  height={36}
                  width={36}
                />
                <div className="flex-1">
                  <span
                    className={classNames(
                      "badge",
                      "badge-soft-success",
                      "float-end",
                      {
                        "badge-soft-success": item.status === "Won",
                        "badge-soft-warning": item.status === "Cold",
                        "badge-soft-danger": item.status === "Lost",
                      }
                    )}
                  >
                    {item.status} lead
                  </span>
                  <h5 className="mt-0 mb-1">{item.name}</h5>
                  <span className="text-muted font-13">{item.email}</span>
                </div>
              </div>
            );
          })}
        </CardBody>
      </Card>
    </>
  );
};

export default RecentLeads;

// Minton_v10.1.0/Angular/Minton/src/app/views/dashboard/crm/components/recent-leads/recent-leads.component.ts
import { Component } from '@angular/core'
import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap'
import { recentLeads } from '../../data'
import { CommonModule } from '@angular/common'

@Component({
  selector: 'crm-recent-leads',
  standalone: true,
  imports: [NgbDropdownModule, CommonModule],
  templateUrl: './recent-leads.component.html',
  styles: ``,
})
export class RecentLeadsComponent {
  leadList = recentLeads
}

<div class="card">
  <div class="card-body">
    <div ngbDropdown class="dropdown float-end">
      <a
        ngbDropdownToggle
        class="dropdown-toggle arrow-none card-drop"
        role="button"
      >
        <i class="mdi mdi-dots-vertical"></i>
      </a>
      <div ngbDropdownMenu class="dropdown-menu dropdown-menu-end">
        <!-- item-->
        <a href="javascript:void(0);" class="dropdown-item">Settings</a>
        <!-- item-->
        <a href="javascript:void(0);" class="dropdown-item">Action</a>
      </div>
    </div>
    <h4 class="header-title mb-4">Recent Leads</h4>

    @for (item of leadList; track $index; let first = $first) {
      <div class="d-flex" [ngClass]="{ 'mt-3': !first }">
        <img
          class="avatar-sm align-self-center me-3 rounded-circle"
          [src]="item.avatar"
          alt="Generic placeholder image"
        />
        <div class="flex-1">
          <span
            class="badge float-end"
            [ngClass]="{
              'badge-soft-warning': item.status == 'Cold',
              'badge-soft-danger': item.status == 'Lost',
              'badge-soft-success': item.status == 'Won',
            }"
            >{{ item.status }} lead</span
          >
          <h5 class="mt-0 mb-1">{{ item.name }}</h5>
          <span class="text-muted font-13">{{ item.email }}</span>
        </div>
      </div>
    }
  </div>
</div>
