// Minton_v10.1.0/Next.js/JS/src/app/(admin)/pages/sitemap/page.jsx
import React from "react";
import Link from "next/link";
import Image from "next/image";
import classNames from "classnames";

// components
import PageBreadcrumb from "@/components/PageBreadcrumb";

// dummy data
import { sitemap1, sitemap2, sitemap3 } from "./data";

// images
import logo from "@/assets/images/logo-sm-dark.png";
const SiteMenuTitle = ({
  label
}) => {
  return <Link href="" className="text-uppercase fw-bold">
      <Image src={logo} alt="" height={12} width={12} className="me-1" /> {label}
    </Link>;
};
const SiteMapMenu = ({
  item
}) => {
  return <ul>
      {(item.children || []).map((item, index) => <SiteMapMenuItem key={index} item={item} />)}
    </ul>;
};
const SiteMapMenuItem = ({
  item
}) => {
  const {
    children,
    level
  } = item;
  const hasChildren = item && children && children.length;
  return <li>
      <Link href="" className={classNames(item.className)}>
        {item.icon && <i className={classNames(item.icon, "me-1")}></i>}
        {level === 1 ? <b>{item.label}</b> : item.label}
      </Link>
      {hasChildren && <SiteMapMenu item={item} />}
    </li>;
};
export const metadata = {
  title: "Sitemap"
};
const Sitemap = () => {
  return <>
      <PageBreadcrumb breadCrumbItems={[{
      label: "Extra Pages",
      path: "/pages/sitemap"
    }, {
      label: "Sitemap",
      path: "/pages/sitemap",
      active: true
    }]} title={"Sitemap"} />
      <div className="row">
        <div className="col">
          <div className="card">
            <div className="card-body">
              <div className="row">
                <div className="col-lg-4">
                  <ul className="sitemap">
                    <li>
                      <SiteMenuTitle label={sitemap1["label"]} />
                      <SiteMapMenu item={sitemap1} />
                    </li>
                  </ul>
                </div>
                <div className="col-lg-4">
                  <ul className="sitemap">
                    <li>
                      <SiteMenuTitle label={sitemap2["label"]} />
                      <SiteMapMenu item={sitemap2} />
                    </li>
                  </ul>
                </div>
                <div className="col-lg-4">
                  <ul className="sitemap">
                    <li>
                      <SiteMenuTitle label={sitemap3["label"]} />
                      <SiteMapMenu item={sitemap3} />
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>;
};
export default Sitemap;

// Minton_v10.1.0/Angular/Minton/src/app/views/extra-pages/sitemap/sitemap.component.ts
import { Component } from '@angular/core'
import { PageTitleComponent } from '@component/page-title.component'
import { sitemap1, sitemap2, sitemap3, type ItemType } from './data'
import { CommonModule } from '@angular/common'

@Component({
  selector: 'app-sitemap',
  standalone: true,
  imports: [PageTitleComponent, CommonModule],
  templateUrl: './sitemap.component.html',
  styles: ``,
})
export class SitemapComponent {
  breadCrumbItems = [
    { label: 'Extras', path: '/pages/starter' },
    { label: 'Sitemap', path: '/pages/sitemap', active: true },
  ]

  sitemap1 = sitemap1
  sitemap2 = sitemap2
  sitemap3 = sitemap3

  hasChildren(item: ItemType) {
    return item && item.children && item.children.length > 0
  }
}

<app-page-title title="Sitemap" [breadCrumbItems]="breadCrumbItems" />
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-lg-4">
            <ul class="sitemap">
              <li>
                <ng-container
                  *ngTemplateOutlet="
                    menuTitle;
                    context: { label: sitemap1.label }
                  "
                ></ng-container>
                <ng-container
                  *ngTemplateOutlet="menu; context: { item: sitemap1 }"
                ></ng-container>
              </li>
            </ul>
          </div>
          <!-- end col-->

          <div class="col-lg-4">
            <ul class="sitemap">
              <li>
                <ng-container
                  *ngTemplateOutlet="
                    menuTitle;
                    context: { label: sitemap2.label }
                  "
                ></ng-container>
                <ng-container
                  *ngTemplateOutlet="menu; context: { item: sitemap2 }"
                ></ng-container>
              </li>
            </ul>
          </div>

          <div class="col-lg-4">
            <ul class="sitemap">
              <li>
                <ng-container
                  *ngTemplateOutlet="
                    menuTitle;
                    context: { label: sitemap3.label }
                  "
                ></ng-container>
                <ng-container
                  *ngTemplateOutlet="menu; context: { item: sitemap3 }"
                ></ng-container>
              </li>
            </ul>
          </div>
          <!-- end col-->
        </div>
        <!-- end row-->
      </div>
    </div>
    <!-- end card-box-->
  </div>
  <!-- end col-->
</div>

<ng-template #menuTitle let-label="label">
  <a href="javascript:void(0);" class="text-uppercase fw-bold">
    <img src="assets/images/logo-sm-dark.png" alt="" height="12" class="me-1" />
    {{ label }}
  </a>
</ng-template>

<ng-template #menu let-item="item">
  <ul>
    @for (child of item.children; track $index) {
      <li>
        <a href="javascript:void(0);" [ngClass]="child.className">
          @if (child.icon) {
            <i [ngClass]="child.icon + ' me-1'"></i>
          }
          @if (child.level === 1) {
            <b>{{ child.label }}</b>
          } @else {
            {{ child.label }}
          }
        </a>
        @if (hasChildren(child)) {
          <ng-container
            *ngTemplateOutlet="menu; context: { item: child }"
          ></ng-container>
        }
      </li>
    }
  </ul>
</ng-template>
