// Minton_v10.1.0/Angular/Minton/src/app/views/charts/apex/components/bubble-chart/bubble-chart.component.ts
import { Component } from '@angular/core'
import type { ChartOptions } from '@common/apexchart.model'
import { CustomCardPortletComponent } from '@component/custom-card-portlet/custom-card-portlet.component'
import { NgApexchartsModule } from 'ng-apexcharts'
import { generateData } from '../../data'

@Component({
  selector: 'bubble-chart',
  standalone: true,
  imports: [NgApexchartsModule, CustomCardPortletComponent],
  templateUrl: './bubble-chart.component.html',
  styles: ``,
})
export class BubbleChartComponent {
  apexbubble1Chart: Partial<ChartOptions> = {
    chart: {
      height: 380,
      type: 'bubble',
      toolbar: {
        show: false,
      },
    },
    dataLabels: {
      enabled: false,
    },
    series: [
      {
        name: 'Bubble 1',
        data: generateData(new Date('11 Feb 2017 GMT').getTime(), 20, {
          min: 10,
          max: 60,
        }),
      },
      {
        name: 'Bubble 2',
        data: generateData(new Date('11 Feb 2017 GMT').getTime(), 20, {
          min: 10,
          max: 60,
        }),
      },
      {
        name: 'Bubble 3',
        data: generateData(new Date('11 Feb 2017 GMT').getTime(), 20, {
          min: 10,
          max: 60,
        }),
      },
    ],
    fill: {
      opacity: 0.8,
    },
    colors: ['#3bafda', '#1abc9c', '#f672a7'],
    xaxis: {
      tickAmount: 12,
      type: 'category',
    },
    yaxis: {
      max: 70,
    },
    grid: {
      borderColor: '#f1f3fa',
      padding: {
        bottom: 10,
      },
    },
    legend: {
      offsetY: 7,
    },
  }
}

<custom-card-portlet
  cardTitle="Simple Bubble Chart"
  cardTitleClass="header-title mb-0"
>
  <div
    id="apex-bubble-1"
    class="apex-charts"
    data-colors="#3bafda,#1abc9c,#f672a7"
  >
    <apx-chart
      [chart]="apexbubble1Chart.chart!"
      [dataLabels]="apexbubble1Chart.dataLabels!"
      [series]="apexbubble1Chart.series!"
      [fill]="apexbubble1Chart.fill!"
      [colors]="apexbubble1Chart.colors!"
      [xaxis]="apexbubble1Chart.xaxis!"
      [yaxis]="apexbubble1Chart.yaxis!"
      [grid]="apexbubble1Chart.grid!"
      [legend]="apexbubble1Chart.legend!"
    />
  </div>
</custom-card-portlet>

// Minton_v10.1.0/React.js/JS/src/app/(admin)/charts/apex/BubbleChart.jsx
import { Card } from "react-bootstrap";
import { bubbleChartData } from "@/app/(admin)/charts/apex/data";
import ReactApexChart from "react-apexcharts";
const BubbleChart = () => {
  const options = {
    chart: {
      height: 380,
      type: "bubble",
      toolbar: {
        show: false
      }
    },
    dataLabels: {
      enabled: false
    },
    colors: ["#3bafda", "#1abc9c", "#f672a7"],
    fill: {
      opacity: 0.8
    },
    xaxis: {
      tickAmount: 12,
      type: "category"
    },
    yaxis: {
      max: 70
    },
    grid: {
      borderColor: "#f1f3fa",
      padding: {
        bottom: 10
      }
    },
    legend: {
      offsetY: 7
    }
  };
  const series = [{
    name: "Bubble 1",
    data: bubbleChartData.data1 || []
  }, {
    name: "Bubble 2",
    data: bubbleChartData.data2 || []
  }, {
    name: "Bubble 3",
    data: bubbleChartData.data3 || []
  }];
  return <Card>
            <Card.Body>
                <h5 className="header-title mb-0">Simple Bubble Chart</h5>
                <div className="pt-3">
                    <ReactApexChart options={options} series={series} type="bubble" height={380} />
                </div>
            </Card.Body>
        </Card>;
};
export default BubbleChart;
