// Minton_v10.1.0/Angular/Minton/src/app/views/charts/apex/components/mixed-chart/mixed-chart.component.ts
import { Component } from '@angular/core'
import type { ChartOptions } from '@common/apexchart.model'
import { CustomCardPortletComponent } from '@component/custom-card-portlet/custom-card-portlet.component'
import { NgApexchartsModule } from 'ng-apexcharts'

@Component({
  selector: 'mixed-chart',
  standalone: true,
  imports: [NgApexchartsModule, CustomCardPortletComponent],
  templateUrl: './mixed-chart.component.html',
  styles: ``,
})
export class MixedChartComponent {
  apexmixed1Chart: Partial<ChartOptions> = {
    chart: {
      height: 380,
      type: 'line',
    },
    stroke: {
      width: 2,
      curve: 'smooth',
    },

    series: [
      {
        name: 'TEAM A',
        type: 'area',
        data: [44, 55, 31, 47, 31, 43, 26, 41, 31, 47, 33],
      },
      {
        name: 'TEAM B',
        type: 'line',
        data: [55, 69, 45, 61, 43, 54, 37, 52, 44, 61, 43],
      },
    ],
    colors: ['#CED4DC', '#3bafda'],
    fill: {
      type: 'solid',
      opacity: [0.35, 1],
    },
    labels: [
      'Dec 01',
      'Dec 02',
      'Dec 03',
      'Dec 04',
      'Dec 05',
      'Dec 06',
      'Dec 07',
      'Dec 08',
      'Dec 09 ',
      'Dec 10',
      'Dec 11',
    ],
    markers: {
      size: 0,
    },
    yaxis: [
      {
        title: {
          text: 'Series A',
        },
      },
      {
        opposite: true,
        title: {
          text: 'Series B',
        },
      },
    ],
    tooltip: {
      shared: true,
      intersect: false,
      y: {
        formatter: function (y) {
          if (typeof y !== 'undefined') {
            return y.toFixed(0) + ' points'
          }
          return y
        },
      },
    },
    legend: {
      offsetY: 7,
    },
  }
}

<custom-card-portlet
  cardTitle="Mixed Chart - Line & Area"
  cardTitleClass="header-title mb-0"
>
  <div id="apex-mixed-1" class="apex-charts" data-colors="#CED4DC,#3bafda">
    <apx-chart
      [chart]="apexmixed1Chart.chart!"
      [stroke]="apexmixed1Chart.stroke!"
      [series]="apexmixed1Chart.series!"
      [colors]="apexmixed1Chart.colors!"
      [fill]="apexmixed1Chart.fill!"
      [labels]="apexmixed1Chart.labels!"
      [markers]="apexmixed1Chart.markers!"
      [yaxis]="apexmixed1Chart.yaxis!"
      [tooltip]="apexmixed1Chart.tooltip!"
      [legend]="apexmixed1Chart.legend!"
    />
  </div>
</custom-card-portlet>

// Minton_v10.1.0/React.js/JS/src/app/(admin)/charts/apex/MixedChart.jsx
import { Card } from "react-bootstrap";
import { mixedChart1Data } from "@/app/(admin)/charts/apex/data";
import ReactApexChart from "react-apexcharts";

// Mixed chart
const MixedChart = () => {
  // default options
  const apexMixedOpts = {
    chart: {
      height: 380,
      type: "line"
    },
    stroke: {
      width: [2],
      curve: "smooth"
    },
    fill: {
      type: "solid",
      opacity: [0.35, 1]
    },
    colors: ["#CED4DC", "#3bafda"],
    labels: ["Dec 01", "Dec 02", "Dec 03", "Dec 04", "Dec 05", "Dec 06", "Dec 07", "Dec 08", "Dec 09 ", "Dec 10", "Dec 11"],
    markers: {
      size: 0
    },
    legend: {
      offsetY: 7
    },
    yaxis: [{
      title: {
        text: "Series A"
      }
    }, {
      opposite: true,
      title: {
        text: "Series B"
      }
    }],
    tooltip: {
      shared: true,
      intersect: false,
      y: {
        formatter: function (y) {
          if (typeof y !== "undefined") {
            return y.toFixed(0) + " points";
          }
          return y;
        }
      }
    }
  };

  // chart data
  const apexMixedData = [{
    name: "Team A",
    type: "area",
    data: mixedChart1Data.data1 || []
  }, {
    name: "Team B",
    type: "line",
    data: mixedChart1Data.data2 || []
  }];
  return <Card>
            <Card.Body>
                <h5 className="header-title mb-0">Mixed Chart - Line & Area</h5>
                <div className="pt-3">
                    <ReactApexChart options={apexMixedOpts} series={apexMixedData} type="line" height={380} />
                </div>
            </Card.Body>
        </Card>;
};
export default MixedChart;
