// Minton_v10.1.0/Next.js/TS/src/app/(admin)/widgets/WeatherWidget.tsx
import React from "react";
import classNames from "classnames";

// types
import { WeatherTypes } from "./data";

interface WeatherWidgetProps {
  item: WeatherTypes;
}

const WeatherWidget = ({ item }: WeatherWidgetProps) => {
  return (
    <div className={classNames('card', "bg-" + item.variant, "border-" + item.variant)}>
      <div className="card-body">
        <div className="row">
          <div className="col-md-7">
            <div className="row align-items-center">
              <div className="col-6 text-center">
                <h1 className="display-4">
                  <i className="wi wi-day-sleet text-white"></i>
                </h1>
              </div>
              <div className="col-6">
                <div className="text-white">
                  <h2 className="text-white">
                    <b>{item.temp}</b>
                  </h2>
                  <p>{item.clouds}</p>
                  <p className=" mb-0">
                    {item.windSpeed} - {item.humidity}
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div className="col-md-5">
            <div className="row">
              {(item.forecast || []).map((item, index) => {
                return (
                  <div className="col col-4 text-center" key={index}>
                    <h4 className="text-white mt-0">{item.day}</h4>
                    <h3 className="my-3">
                      <i className={classNames("text-white", item.icon)}></i>
                    </h3>
                    <h4 className="text-white mb-0">
                      {item.temp}
                      <i className="wi wi-degrees"></i>
                    </h4>
                  </div>
                )
              })}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default WeatherWidget;

// Minton_v10.1.0/Angular/Minton/src/app/views/apps/widgets/components/weather-widget/weather-widget.component.ts
import { Component, Input } from '@angular/core'
import type { WeatherTypes } from '../../data'
import { CommonModule } from '@angular/common'

@Component({
  selector: 'weather-widget',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './weather-widget.component.html',
  styles: ``,
})
export class WeatherWidgetComponent {
  @Input() item!: WeatherTypes
}

<div [ngClass]="['card', 'bg-' + item.variant, 'border-' + item.variant]">
  <div class="card-body">
    <div class="row">
      <div class="col-md-7">
        <div class="row align-items-center">
          <div class="col-6 text-center">
            <h1 class="display-4">
              <i class="wi wi-day-sleet text-white"></i>
            </h1>
          </div>
          <div class="col-6">
            <div class="text-white">
              <h2 class="text-white">
                <b>{{ item.temp }}</b>
              </h2>
              <p>{{ item.clouds }}</p>
              <p class="mb-0">{{ item.windSpeed }} - {{ item.humidity }}</p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-5">
        <div class="row">
          @for (forecast of item.forecast; track $index) {
            <div class="col-4 text-center">
              <h4 class="text-white mt-0">{{ forecast.day }}</h4>
              <h3 class="my-3">
                <i [ngClass]="['text-white', forecast.icon]"></i>
              </h3>
              <h4 class="text-white mb-0">
                {{ forecast.temp }}<i class="wi wi-degrees"></i>
              </h4>
            </div>
          }
        </div>
      </div>
    </div>
  </div>
</div>
