// Minton_v10.1.0/Angular/Minton/src/app/views/dashboard/analytics/components/browser-usage/browser-usage.component.ts
import { Component } from '@angular/core'
import { browserUsageData } from '../../data'
import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap'

@Component({
  selector: 'analytics-browser-usage',
  standalone: true,
  imports: [NgbDropdownModule],
  templateUrl: './browser-usage.component.html',
  styles: ``,
})
export class BrowserUsageComponent {
  browserList = browserUsageData
}

<div class="card">
  <div class="card-body">
    <div ngbDropdown class="dropdown float-end">
      <a
        ngbDropdownToggle
        class="dropdown-toggle arrow-none card-drop"
        role="button"
      >
        <i class="mdi mdi-dots-horizontal"></i>
      </a>
      <div ngbDropdownMenu class="dropdown-menu dropdown-menu-end">
        <!-- item-->
        <a href="javascript:void(0);" class="dropdown-item">Settings</a>
        <!-- item-->
        <a href="javascript:void(0);" class="dropdown-item">Download</a>
        <!-- item-->
        <a href="javascript:void(0);" class="dropdown-item">Upload</a>
        <!-- item-->
        <a href="javascript:void(0);" class="dropdown-item">Action</a>
      </div>
    </div>
    <h4 class="header-title mt-0 mb-3">Browser Used By Users</h4>
    <div class="table-responsive browser_users">
      <table class="table mb-0">
        <thead class="table-light">
          <tr>
            <th class="border-top-0">Browser</th>
            <th class="border-top-0">Sessions</th>
            <th class="border-top-0">Bounce Rate</th>
            <th class="border-top-0">Transactions</th>
          </tr>
          <!--end tr-->
        </thead>
        <tbody>
          @for (item of browserList; track $index) {
            <tr>
              <td>
                <i
                  class="fab fa-{{ item.browser.icon }} me-2 text-{{
                    item.browser.variant
                  }} font-16"
                ></i
                >{{ item.browser.name }}
              </td>
              <td>
                {{ item.sessions.value }}
                <small class="text-muted">({{ item.sessions.rate }})</small>
              </td>
              <td>{{ item.bounce_rate }}%</td>
              <td>
                {{ item.transactions.value }}
                <small class="text-muted">({{ item.transactions.rate }})</small>
              </td>
            </tr>
            <!--end tr-->
          }
        </tbody>
      </table>
      <!--end table-->
    </div>
    <!--end /div-->
  </div>
  <!--end card-body-->
</div>
<!--end card-->

// Minton_v10.1.0/React.js/JS/src/app/(admin)/dashboard/analytics/BrowserUsage.jsx
import classNames from "classnames";

// types

import { Card, CardBody } from "react-bootstrap";
import AnalyticDropdown from "./AnalyticDropdown";
const BrowserUsage = ({
  browserUsageData
}) => {
  return <Card>
      <CardBody>
        <AnalyticDropdown />

        <h4 className="header-title mt-0 mb-3">Browser Used By Users</h4>

        <div className="table-responsive browser_users">
          <table className="table mb-0">
            <thead className="table-light">
              <tr>
                <th className="border-top-0">Browser</th>
                <th className="border-top-0">Sessions</th>
                <th className="border-top-0">Bounce Rate</th>
                <th className="border-top-0">Transactions</th>
              </tr>
            </thead>
            <tbody>
              {(browserUsageData || []).map((item, index) => {
              return <tr key={index}>
                    <td>
                      <i className={classNames("fab", "fa-" + item.browser.icon, "me-2", "text-" + item.browser.variant, "font-16")}></i>
                      {item.browser.name}
                    </td>
                    <td>
                      {item.sessions.value}{" "}
                      <small className="text-muted">
                        ({item.sessions.rate})
                      </small>
                    </td>
                    <td> {item.bounce_rate}%</td>
                    <td>
                      {item.transactions.value}{" "}
                      <small className="text-muted">
                        ({item.transactions.rate})
                      </small>
                    </td>
                  </tr>;
            })}
            </tbody>
          </table>
        </div>
      </CardBody>
    </Card>;
};
export default BrowserUsage;
