// Minton_v10.1.0/Angular/Minton/src/app/views/charts/apex/components/scatter-chart/scatter-chart.component.ts
import { Component } from '@angular/core'
import type { ChartOptions } from '@common/apexchart.model'
import { CustomCardPortletComponent } from '@component/custom-card-portlet/custom-card-portlet.component'
import { NgApexchartsModule } from 'ng-apexcharts'

@Component({
  selector: 'scatter-chart',
  standalone: true,
  imports: [NgApexchartsModule, CustomCardPortletComponent],
  templateUrl: './scatter-chart.component.html',
  styles: ``,
})
export class ScatterChartComponent {
  apexscatter1Chart: Partial<ChartOptions> = {
    chart: {
      height: 380,
      type: 'scatter',
      zoom: {
        enabled: false,
      },
    },

    series: [
      {
        name: 'Sample A',
        data: [
          [16.4, 5.4],
          [21.7, 2],
          [25.4, 3],
          [19, 2],
          [10.9, 1],
          [13.6, 3.2],
          [10.9, 7.4],
          [10.9, 0],
          [10.9, 8.2],
          [16.4, 0],
          [16.4, 1.8],
          [13.6, 0.3],
          [13.6, 0],
          [29.9, 0],
          [27.1, 2.3],
          [16.4, 0],
          [13.6, 3.7],
          [10.9, 5.2],
          [16.4, 6.5],
          [10.9, 0],
          [24.5, 7.1],
          [10.9, 0],
          [8.1, 4.7],
          [19, 0],
          [21.7, 1.8],
          [27.1, 0],
          [24.5, 0],
          [27.1, 0],
          [29.9, 1.5],
          [27.1, 0.8],
          [22.1, 2],
        ],
      },
      {
        name: 'Sample B',
        data: [
          [6.4, 13.4],
          [1.7, 11],
          [5.4, 8],
          [9, 17],
          [1.9, 4],
          [3.6, 12.2],
          [1.9, 14.4],
          [1.9, 9],
          [1.9, 13.2],
          [1.4, 7],
          [6.4, 8.8],
          [3.6, 4.3],
          [1.6, 10],
          [9.9, 2],
          [7.1, 15],
          [1.4, 0],
          [3.6, 13.7],
          [1.9, 15.2],
          [6.4, 16.5],
          [0.9, 10],
          [4.5, 17.1],
          [10.9, 10],
          [0.1, 14.7],
          [9, 10],
          [12.7, 11.8],
          [2.1, 10],
          [2.5, 10],
          [27.1, 10],
          [2.9, 11.5],
          [7.1, 10.8],
          [2.1, 12],
        ],
      },
      {
        name: 'Sample C',
        data: [
          [21.7, 3],
          [23.6, 3.5],
          [24.6, 3],
          [29.9, 3],
          [21.7, 20],
          [23, 2],
          [10.9, 3],
          [28, 4],
          [27.1, 0.3],
          [16.4, 4],
          [13.6, 0],
          [19, 5],
          [22.4, 3],
          [24.5, 3],
          [32.6, 3],
          [27.1, 4],
          [29.6, 6],
          [31.6, 8],
          [21.6, 5],
          [20.9, 4],
          [22.4, 0],
          [32.6, 10.3],
          [29.7, 20.8],
          [24.5, 0.8],
          [21.4, 0],
          [21.7, 6.9],
          [28.6, 7.7],
          [15.4, 0],
          [18.1, 0],
          [33.4, 0],
          [16.4, 0],
        ],
      },
    ],
    xaxis: {
      tickAmount: 10,
    },
    yaxis: {
      tickAmount: 7,
    },
    colors: ['#1abc9c', '#f672a7', '#6c757d'],
    grid: {
      borderColor: '#f1f3fa',
      padding: {
        bottom: 10,
      },
    },
    legend: {
      offsetY: 7,
    },
    responsive: [
      {
        breakpoint: 600,
        options: {
          chart: {
            toolbar: {
              show: false,
            },
          },
          legend: {
            show: false,
          },
        },
      },
    ],
  }
}

<custom-card-portlet
  cardTitle="Scatter (XY) Chart"
  cardTitleClass="header-title mb-0"
>
  <div
    id="apex-scatter-1"
    class="apex-charts"
    data-colors="#1abc9c,#f672a7,#6c757d"
  >
    <apx-chart
      [chart]="apexscatter1Chart.chart!"
      [series]="apexscatter1Chart.series!"
      [xaxis]="apexscatter1Chart.xaxis!"
      [yaxis]="apexscatter1Chart.yaxis!"
      [colors]="apexscatter1Chart.colors!"
      [grid]="apexscatter1Chart.grid!"
      [legend]="apexscatter1Chart.legend!"
      [responsive]="apexscatter1Chart.responsive!"
    />
  </div>
</custom-card-portlet>

// Minton_v10.1.0/Next.js/JS/src/app/(admin)/charts/apex/ScatterChart.jsx
"use client";

// components
import { scatterChartData } from "@/app/(admin)/charts/apex/data";
import { Card } from "react-bootstrap";
import React from "react";
import ReactApexChart from "react-apexcharts";
const ScatterChart = () => {
  const options = {
    chart: {
      height: 380,
      type: "scatter",
      zoom: {
        enabled: false
      }
    },
    colors: ["#1abc9c", "#f672a7", "#6c757d"],
    xaxis: {
      tickAmount: 10
    },
    yaxis: {
      tickAmount: 7
    },
    grid: {
      borderColor: "#f1f3fa",
      padding: {
        bottom: 10
      }
    },
    legend: {
      offsetY: 7
    }
  };
  const series = [{
    name: "Sample A",
    data: scatterChartData.data1
  }, {
    name: "Sample B",
    data: scatterChartData.data2
  }, {
    name: "Sample C",
    data: scatterChartData.data3
  }];
  return <Card>
            <Card.Body>
                <h5 className="header-title mb-0">Scatter (XY) Chart</h5>
                <div className="pt-3">
                    <ReactApexChart options={options} series={series} type="scatter" height={380} />
                </div>
            </Card.Body>
        </Card>;
};
export default ScatterChart;
