// Minton_v10.1.0/React.js/JS/src/app/(admin)/dashboard/crm/RevenueChart.jsx
import { Button, ButtonGroup, Card, CardBody, Col, Row } from "react-bootstrap";
// chart

// utility function to generate time series
import { generateDayWiseTimeSeries } from "@/utils/chart";
import ReactApexChart from "react-apexcharts";
const RevenueChart = () => {
  const options = {
    chart: {
      stacked: true,
      toolbar: {
        show: false
      }
    },
    colors: ["#3bafda", "#ced4dc"],
    dataLabels: {
      enabled: false
    },
    stroke: {
      width: [2],
      curve: "smooth"
    },
    fill: {
      type: "gradient",
      gradient: {
        opacityFrom: 0.3,
        opacityTo: 0.9
      }
    },
    legend: {
      offsetY: 5
    },
    xaxis: {
      type: "datetime"
    },
    grid: {
      padding: {
        bottom: 10
      }
    },
    yaxis: {
      title: {
        text: "Revenue",
        style: {
          color: undefined,
          fontSize: "13px",
          cssClass: "apexcharts-yaxis-title"
        }
      }
    }
  };
  const series = [{
    name: "Total Revenue",
    data: generateDayWiseTimeSeries(new Date("11 Feb 2017 GMT").getTime(), 20, {
      min: 100,
      max: 1500
    })
  }, {
    name: "Total Pipeline",
    data: generateDayWiseTimeSeries(new Date("11 Feb 2017 GMT").getTime(), 20, {
      min: 100,
      max: 1000
    })
  }];
  return <Card>
      <CardBody>
        <div className="d-flex justify-content-between">
          <h4 className="header-title">Revenue</h4>
          <ButtonGroup className="mb-2">
            <Button variant="light" className="btn-xs active">
              Today
            </Button>
            <Button variant="light" className="btn-xs">
              Weekly
            </Button>
            <Button variant="light" className="btn-xs">
              Monthly
            </Button>
          </ButtonGroup>
        </div>
        <Row className="mt-4 text-center">
          <Col xs={4}>
            <p className="text-muted font-15 mb-1 text-truncate">
              Current Month
            </p>
            <h4>
              <i className="fe-arrow-up text-success me-1"></i>$1.4k
            </h4>
          </Col>
          <Col xs={4}>
            <p className="text-muted font-15 mb-1 text-truncate">
              Previous Month
            </p>
            <h4>
              <i className="fe-arrow-down text-danger me-1"></i>$15k
            </h4>
          </Col>
          <Col xs={4}>
            <p className="text-muted font-15 mb-1 text-truncate">Target</p>
            <h4>
              <i className="fe-arrow-down text-danger me-1"></i>$7.8k
            </h4>
          </Col>
        </Row>

        <div className="mt-3" dir="ltr">
          <ReactApexChart options={options} series={series} type="area" height={260} className="apex-charts" />
        </div>
      </CardBody>
    </Card>;
};
export default RevenueChart;

// Minton_v10.1.0/Angular/Minton/src/app/views/dashboard/crm/components/revenue-chart/revenue-chart.component.ts
import { Component } from '@angular/core'
import type { ChartOptions } from '@common/apexchart.model'
import { currency } from '@common/constants'
import { NgApexchartsModule } from 'ng-apexcharts'

export type Range = {
  min: number
  max: number
}

export type Point = {
  x: number
  y: number
}

@Component({
  selector: 'crm-revenue-chart',
  standalone: true,
  imports: [NgApexchartsModule],
  templateUrl: './revenue-chart.component.html',
  styles: ``,
})
export class RevenueChartComponent {
  currency = currency

  generateDayWiseTimeSeries(baseval: number, count: number, yrange: Range) {
    let i = 0
    let series: Point[] = []
    while (i < count) {
      let x = baseval
      let y =
        Math.floor(Math.random() * (yrange.max - yrange.min + 1)) + yrange.min

      series.push({ x, y })
      baseval += 86400000
      i++
    }
    return series
  }

  revenue: Partial<ChartOptions> = {
    chart: {
      height: 260,
      type: 'area',
      stacked: true,
      toolbar: {
        show: false,
      },
    },
    series: [
      {
        name: 'Total Revenue',
        data: this.generateDayWiseTimeSeries(
          new Date('11 Feb 2017 GMT').getTime(),
          20,
          {
            min: 100,
            max: 1500,
          }
        ),
      },

      {
        name: 'Total Pipeline',
        data: this.generateDayWiseTimeSeries(
          new Date('11 Feb 2017 GMT').getTime(),
          20,
          {
            min: 100,
            max: 1000,
          }
        ),
      },
    ],
    colors: ['#3bafda', '#ced4dc'],
    dataLabels: {
      enabled: false,
    },
    stroke: {
      width: [2],
      curve: 'smooth',
    },
    fill: {
      type: 'gradient',
      gradient: {
        opacityFrom: 0.3,
        opacityTo: 0.9,
      },
    },
    legend: {
      offsetY: 5,
    },
    xaxis: {
      type: 'datetime',
    },
    grid: {
      padding: {
        bottom: 10,
      },
    },
    yaxis: {
      title: {
        text: 'Revenue',
        style: {
          color: undefined,
          fontSize: '13px',
          cssClass: 'apexcharts-yaxis-title',
        },
      },
    },
  }
}

<div class="card">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <h4 class="header-title">Revenue</h4>
      <div class="btn-group mb-2">
        <button type="button" class="btn btn-xs btn-light active">Today</button>
        <button type="button" class="btn btn-xs btn-light">Weekly</button>
        <button type="button" class="btn btn-xs btn-light">Monthly</button>
      </div>
    </div>

    <div class="row mt-4 text-center">
      <div class="col-4">
        <p class="text-muted font-15 mb-1 text-truncate">Current Month</p>
        <h4><i class="fe-arrow-up text-success me-1"></i>{{ currency }}1.4k</h4>
      </div>
      <div class="col-4">
        <p class="text-muted font-15 mb-1 text-truncate">Previous Month</p>
        <h4><i class="fe-arrow-down text-danger me-1"></i>{{ currency }}15k</h4>
      </div>
      <div class="col-4">
        <p class="text-muted font-15 mb-1 text-truncate">Target</p>
        <h4>
          <i class="fe-arrow-down text-danger me-1"></i>{{ currency }}7.8k
        </h4>
      </div>
    </div>

    <div class="mt-3" dir="ltr">
      <div id="revenue-chart" class="apex-charts" data-colors="#3bafda,#ced4dc">
        <apx-chart
          [chart]="revenue.chart!"
          [series]="revenue.series!"
          [colors]="revenue.colors!"
          [dataLabels]="revenue.dataLabels!"
          [stroke]="revenue.stroke!"
          [fill]="revenue.fill!"
          [legend]="revenue.legend!"
          [xaxis]="revenue.xaxis!"
          [grid]="revenue.grid!"
          [yaxis]="revenue.yaxis!"
        />
      </div>
    </div>
  </div>
  <!-- end card-body-->
</div>
<!-- end card-->
