// Minton_v10.1.0/Next.js/TS/src/app/(admin)/pages/timeline/page.tsx
import React from "react";
import Image from "next/image";
import Link from "next/link";

// components
import PageBreadcrumb  from "@/components/PageBreadcrumb";

// images
import small1 from "@/assets/images/small/img-1.jpg";
import small2 from "@/assets/images/small/img-2.jpg";
import small3 from "@/assets/images/small/img-3.jpg";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Timeline",
}

// Timeline component
const Timeline = () => {
  return (
    <React.Fragment>
      <PageBreadcrumb
        breadCrumbItems={[
          { label: "Extra Pages", path: "/pages/timeline" },
          { label: "Timeline", path: "/pages/timeline", active: true },
        ]}
        title={"Timeline"}
      />

      <div className="row justify-content-center">
        <div className="col-xs-12">
          <div className="timeline">
            <article className="timeline-item">
              <h2 className="m-0 d-none">&nbsp;</h2>
              <div className="time-show mt-0">
                <Link href="" className="btn btn-primary width-lg">
                  Today
                </Link>
              </div>
            </article>

            <article className="timeline-item timeline-item-left">
              <div className="timeline-desk">
                <div className="timeline-box">
                  <span className="arrow-alt"></span>
                  <span className="timeline-icon">
                    <i className="mdi mdi-adjust"></i>
                  </span>
                  <h4 className="mt-0 font-16">1 hour ago</h4>
                  <p className="text-muted">
                    <small>08:25 am</small>
                  </p>
                  <p className="mb-0">
                    Dolorum provident rerum aut hic quasi placeat iure tempora
                    laudantium ipsa ad debitis unde?{" "}
                  </p>
                </div>
              </div>
            </article>

            <article className="timeline-item">
              <div className="timeline-desk">
                <div className="timeline-box">
                  <span className="arrow"></span>
                  <span className="timeline-icon">
                    <i className="mdi mdi-adjust"></i>
                  </span>
                  <h4 className="mt-0 font-16">2 hours ago</h4>
                  <p className=" text-muted">
                    <small>08:25 am</small>
                  </p>
                  <p className="mb-0">
                    consectetur adipisicing elit. Iusto, optio, dolorum{" "}
                    <Link href="">John deon</Link> provident rerum aut hic quasi
                    placeat iure tempora laudantium
                  </p>
                </div>
              </div>
            </article>

            <article className="timeline-item timeline-item-left">
              <div className="timeline-desk">
                <div className="timeline-box">
                  <span className="arrow-alt"></span>
                  <span className="timeline-icon">
                    <i className="mdi mdi-adjust"></i>
                  </span>
                  <h4 className="mt-0 font-16">10 hours ago</h4>
                  <p className="text-muted">
                    <small>08:25 am</small>
                  </p>
                  <p>3 new photo Uploaded on facebook fan page</p>
                  <div className="timeline-album">
                    <Link href="">
                      <Image alt="" src={small1} width={54} height={36} />
                    </Link>
                    <Link href="">
                      <Image alt="" src={small2} width={54} height={36} />
                    </Link>
                    <Link href="">
                      <Image alt="" src={small3} width={54} height={36} />
                    </Link>
                  </div>
                </div>
              </div>
            </article>

            <article className="timeline-item">
              <div className="timeline-desk">
                <div className="timeline-box">
                  <span className="arrow"></span>
                  <span className="timeline-icon">
                    <i className="mdi mdi-adjust"></i>
                  </span>
                  <h4 className="mt-0 font-16">14 hours ago</h4>
                  <p className="text-muted">
                    <small>08:25 am</small>
                  </p>
                  <p className="mb-0">
                    Outdoor visit at California State Route 85 with John Boltana
                    & Harry Piterson regarding to setup a new show room.
                  </p>
                </div>
              </div>
            </article>

            <article className="timeline-item  timeline-item-left">
              <div className="timeline-desk">
                <div className="panel">
                  <div className="timeline-box">
                    <span className="arrow-alt"></span>
                    <span className="timeline-icon">
                      <i className="mdi mdi-adjust"></i>
                    </span>
                    <h4 className="mt-0 font-16">19 hours ago</h4>
                    <p className="text-muted">
                      <small>08:25 am</small>
                    </p>
                    <p className="mb-0">
                      Jonatha Smith added new milestone{" "}
                      <span>
                        <Link href="">Pathek</Link>
                      </span>{" "}
                      Lorem ipsum dolor sit amet consiquest dio
                    </p>
                  </div>
                </div>
              </div>
            </article>

            <article className="timeline-item">
              <h2 className="m-0 d-none">&nbsp;</h2>
              <div className="time-show">
                <Link href="" className="btn btn-primary width-lg">
                  Yesterday
                </Link>
              </div>
            </article>

            <article className="timeline-item">
              <div className="timeline-desk">
                <div className="panel">
                  <div className="timeline-box">
                    <span className="arrow"></span>
                    <span className="timeline-icon">
                      <i className="mdi mdi-adjust"></i>
                    </span>
                    <h4 className="mt-0 font-16">07 January 2020</h4>
                    <p className="text-muted">
                      <small>08:25 am</small>
                    </p>
                    <p className="mb-0">
                      Montly Regular Medical check up at Greenland Hospital by
                      the doctor{" "}
                      <span>
                        <Link href=""> Johm meon </Link>
                      </span>
                    </p>
                  </div>
                </div>
              </div>
            </article>
            <article className="timeline-item timeline-item-left">
              <div className="timeline-desk">
                <div className="panel">
                  <div className="timeline-box">
                    <span className="arrow-alt"></span>
                    <span className="timeline-icon">
                      <i className="mdi mdi-adjust"></i>
                    </span>
                    <h4 className="mt-0 font-16">07 January 2020</h4>
                    <p className="text-muted">
                      <small>08:25 am</small>
                    </p>
                    <p className="mb-0">
                      Download the new updates of Minton admin dashboard
                    </p>
                  </div>
                </div>
              </div>
            </article>

            <article className="timeline-item">
              <div className="timeline-desk">
                <div className="panel">
                  <div className="timeline-box">
                    <span className="arrow"></span>
                    <span className="timeline-icon">
                      <i className="mdi mdi-adjust"></i>
                    </span>
                    <h4 className="mt-0 font-16">07 January 2019</h4>
                    <p className="text-muted">
                      <small>08:25 am</small>
                    </p>
                    <p className="mb-0">
                      Jonatha Smith added new milestone{" "}
                      <span>
                        <Link className="blue" href="">
                          crishtian
                        </Link>
                      </span>{" "}
                      Lorem ipsum dolor sit amet consiquest dio
                    </p>
                  </div>
                </div>
              </div>
            </article>

            <article className="timeline-item">
              <h2 className="m-0 d-none">&nbsp;</h2>
              <div className="time-show">
                <Link href="" className="btn btn-primary width-lg">
                  Last Month
                </Link>
              </div>
            </article>

            <article className="timeline-item timeline-item-left">
              <div className="timeline-desk">
                <div className="panel">
                  <div className="timeline-box">
                    <span className="arrow-alt"></span>
                    <span className="timeline-icon">
                      <i className="mdi mdi-adjust"></i>
                    </span>
                    <h4 className="mt-0 font-16">31 December 2019</h4>
                    <p className="text-muted">
                      <small>08:25 am</small>
                    </p>
                    <p className="mb-0">
                      Download the new updates of Minton admin dashboard
                    </p>
                  </div>
                </div>
              </div>
            </article>

            <article className="timeline-item">
              <div className="timeline-desk">
                <div className="panel">
                  <div className="timeline-box">
                    <span className="arrow"></span>
                    <span className="timeline-icon">
                      <i className="mdi mdi-adjust"></i>
                    </span>
                    <h4 className="mt-0 font-16">16 Decembar 2019</h4>
                    <p className="text-muted">
                      <small>08:25 am</small>
                    </p>
                    <p className="mb-0">
                      Jonatha Smith added new milestone{" "}
                      <span>
                        <Link href="">prank</Link>
                      </span>{" "}
                      Lorem ipsum dolor sit amet consiquest dio
                    </p>
                  </div>
                </div>
              </div>
            </article>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
};

export default Timeline;

// Minton_v10.1.0/Angular/Minton/src/app/views/extra-pages/timeline/timeline.component.ts
import { Component } from '@angular/core'
import { PageTitleComponent } from '@component/page-title.component'

@Component({
  selector: 'app-timeline',
  standalone: true,
  imports: [PageTitleComponent],
  templateUrl: './timeline.component.html',
  styles: ``,
})
export class TimelineComponent {
  breadCrumbItems = [
    { label: 'Extras', path: '/pages/starter' },
    { label: 'Timeline', path: '/pages/timeline', active: true },
  ]
}

<app-page-title title="Timeline" [breadCrumbItems]="breadCrumbItems" />

<div class="row">
  <div class="col-12">
    <div class="timeline">
      <article class="timeline-item">
        <h2 class="m-0 d-none">&nbsp;</h2>
        <div class="time-show mt-0">
          <a href="javascript:void(0);" class="btn btn-primary width-lg"
            >Today</a
          >
        </div>
      </article>

      <article class="timeline-item timeline-item-left">
        <div class="timeline-desk">
          <div class="timeline-box">
            <span class="arrow-alt"></span>
            <span class="timeline-icon"><i class="mdi mdi-adjust"></i></span>
            <h4 class="mt-0 font-16">1 hour ago</h4>
            <p class="text-muted"><small>08:25 am</small></p>
            <p class="mb-0">
              Dolorum provident rerum aut hic quasi placeat iure tempora
              laudantium ipsa ad debitis unde?
            </p>
          </div>
        </div>
      </article>

      <article class="timeline-item timeline-item-right">
        <div class="timeline-desk">
          <div class="timeline-box">
            <span class="arrow"></span>
            <span class="timeline-icon"><i class="mdi mdi-adjust"></i></span>
            <h4 class="mt-0 font-16">2 hours ago</h4>
            <p class="text-muted"><small>08:25 am</small></p>
            <p class="mb-0">
              consectetur adipisicing elit. Iusto, optio, dolorum
              <a href="javascript:void(0);">John deon</a> provident rerum aut
              hic quasi placeat iure tempora laudantium
            </p>
          </div>
        </div>
      </article>

      <article class="timeline-item timeline-item-left">
        <div class="timeline-desk">
          <div class="timeline-box">
            <span class="arrow-alt"></span>
            <span class="timeline-icon"><i class="mdi mdi-adjust"></i></span>
            <h4 class="mt-0 font-16">10 hours ago</h4>
            <p class="text-muted"><small>08:25 am</small></p>
            <p>3 new photo Uploaded on facebook fan page</p>
            <div class="timeline-album">
              <a href="javascript: void(0);">
                <img alt="" src="assets/images/small/img-1.jpg" />
              </a>
              <a href="javascript: void(0);">
                <img alt="" src="assets/images/small/img-2.jpg" />
              </a>
              <a href="javascript: void(0);">
                <img alt="" src="assets/images/small/img-3.jpg" />
              </a>
            </div>
          </div>
        </div>
      </article>

      <article class="timeline-item timeline-item-right">
        <div class="timeline-desk">
          <div class="timeline-box">
            <span class="arrow"></span>
            <span class="timeline-icon"><i class="mdi mdi-adjust"></i></span>
            <h4 class="mt-0 font-16">14 hours ago</h4>
            <p class="text-muted"><small>08:25 am</small></p>
            <p class="mb-0">
              Outdoor visit at California State Route 85 with John Boltana &
              Harry Piterson regarding to setup a new show room.
            </p>
          </div>
        </div>
      </article>

      <article class="timeline-item timeline-item-left">
        <div class="timeline-desk">
          <div class="panel">
            <div class="timeline-box">
              <span class="arrow-alt"></span>
              <span class="timeline-icon"><i class="mdi mdi-adjust"></i></span>
              <h4 class="mt-0 font-16">19 hours ago</h4>
              <p class="text-muted"><small>08:25 am</small></p>
              <p class="mb-0">
                Jonatha Smith added new milestone
                <span><a href="javascript:void(0);">Pathek</a></span> Lorem
                ipsum dolor sit amet consiquest dio
              </p>
            </div>
          </div>
        </div>
      </article>

      <article class="timeline-item">
        <h2 class="m-0 d-none">&nbsp;</h2>
        <div class="time-show">
          <a href="javascript:void(0);" class="btn btn-primary width-lg"
            >Yesterday</a
          >
        </div>
      </article>

      <article class="timeline-item timeline-item-right">
        <div class="timeline-desk">
          <div class="panel">
            <div class="timeline-box">
              <span class="arrow"></span>
              <span class="timeline-icon"><i class="mdi mdi-adjust"></i></span>
              <h4 class="mt-0 font-16">07 January 2020</h4>
              <p class="text-muted"><small>08:25 am</small></p>
              <p class="mb-0">
                Montly Regular Medical check up at Greenland Hospital by the
                doctor
                <span><a href="javascript:void(0);"> Johm meon </a></span>
              </p>
            </div>
          </div>
        </div>
      </article>
      <article class="timeline-item timeline-item-left">
        <div class="timeline-desk">
          <div class="panel">
            <div class="timeline-box">
              <span class="arrow-alt"></span>
              <span class="timeline-icon"><i class="mdi mdi-adjust"></i></span>
              <h4 class="mt-0 font-16">07 January 2020</h4>
              <p class="text-muted"><small>08:25 am</small></p>
              <p class="mb-0">
                Download the new updates of Minton admin dashboard
              </p>
            </div>
          </div>
        </div>
      </article>

      <article class="timeline-item timeline-item-right">
        <div class="timeline-desk">
          <div class="panel">
            <div class="timeline-box">
              <span class="arrow"></span>
              <span class="timeline-icon"><i class="mdi mdi-adjust"></i></span>
              <h4 class="mt-0 font-16">07 January 2019</h4>
              <p class="text-muted"><small>08:25 am</small></p>
              <p class="mb-0">
                Jonatha Smith added new milestone
                <span
                  ><a class="blue" href="javascript:void(0);"
                    >crishtian</a
                  ></span
                >
                Lorem ipsum dolor sit amet consiquest dio
              </p>
            </div>
          </div>
        </div>
      </article>

      <article class="timeline-item">
        <h2 class="m-0 d-none">&nbsp;</h2>
        <div class="time-show">
          <a href="javascript:void(0);" class="btn btn-primary width-lg"
            >Last Month</a
          >
        </div>
      </article>

      <article class="timeline-item timeline-item-left">
        <div class="timeline-desk">
          <div class="panel">
            <div class="timeline-box">
              <span class="arrow-alt"></span>
              <span class="timeline-icon"><i class="mdi mdi-adjust"></i></span>
              <h4 class="mt-0 font-16">31 December 2019</h4>
              <p class="text-muted"><small>08:25 am</small></p>
              <p class="mb-0">
                Download the new updates of Minton admin dashboard
              </p>
            </div>
          </div>
        </div>
      </article>

      <article class="timeline-item timeline-item-right">
        <div class="timeline-desk">
          <div class="panel">
            <div class="timeline-box">
              <span class="arrow"></span>
              <span class="timeline-icon"><i class="mdi mdi-adjust"></i></span>
              <h4 class="mt-0 font-16">16 Decembar 2019</h4>
              <p class="text-muted"><small>08:25 am</small></p>
              <p class="mb-0">
                Jonatha Smith added new milestone
                <span><a href="javascript:void(0);">prank</a></span> Lorem ipsum
                dolor sit amet consiquest dio
              </p>
            </div>
          </div>
        </div>
      </article>
    </div>
  </div>
</div>
