// Minton_v10.1.0/Angular/Minton/src/app/views/contacts/profile/components/skills/skills.component.ts
import { Component } from '@angular/core'
import { NgbProgressbarModule } from '@ng-bootstrap/ng-bootstrap'
import { skills } from '../../data'
import { CommonModule } from '@angular/common'

@Component({
  selector: 'profile-skills',
  standalone: true,
  imports: [NgbProgressbarModule, CommonModule],
  templateUrl: './skills.component.html',
  styles: ``,
})
export class SkillsComponent {
  skillList = skills
}

<div class="card">
  <div class="card-body">
    <h4 class="header-title">Skills</h4>
    <p class="sub-header mb-3">
      Everyone realizes why a new common language would be desirable
    </p>

    @for (item of skillList; track $index; let first = $first) {
      <div class="pt-1" [ngClass]="{ 'mt-2': !first }">
        <h6 class="text-uppercase" [ngClass]="{ 'mt-0': first }">
          {{ item.language }}
          <span class="float-end">{{ item.progress }}%</span>
        </h6>
        <ngb-progressbar
          type="purple"
          [value]="item.progress"
          class="progress-sm m-0"
        ></ngb-progressbar>
      </div>
    }
  </div>
</div>

// Minton_v10.1.0/React.js/TS/src/app/(admin)/apps/contacts/profile/Skills.tsx

import classNames from "classnames";
import { Card, ProgressBar } from "react-bootstrap";

// types
import { SkillTypes } from "./data";

interface SkillsProps {
    skills: SkillTypes[];
}

const Skills = ({skills}: SkillsProps) => {
    return (
        <Card>
            <Card.Body>
                <h4 className="header-title">Skills</h4>
                <p className="sub-header mb-3">
                    Everyone realizes why a new common language would be desirable
                </p>

                {(skills || []).map((skill, index) => {
                    return (
                        <div
                            key={index}
                            className={classNames("pt-1", {"mt-2": index !== 0})}
                        >
                            <h6
                                className={classNames("text-uppercase", {
                                    "mt-0": index === 0,
                                })}
                            >
                                {skill.language}{" "}
                                <span className="float-end">{skill.progress}%</span>
                            </h6>
                            <ProgressBar
                                now={skill.progress}
                                variant="purple"
                                className="progress-sm m-0"
                            />
                        </div>
                    );
                })}
            </Card.Body>
        </Card>
    );
};

export default Skills;
