// Minton_v10.1.0/Angular/Minton/src/app/views/dashboard/crm/components/campaign-chart/campaign-chart.component.ts
import { Component } from '@angular/core'
import type { ChartOptions } from '@common/apexchart.model'
import { NgApexchartsModule } from 'ng-apexcharts'

@Component({
  selector: 'crm-campaign-chart',
  standalone: true,
  imports: [NgApexchartsModule],
  templateUrl: './campaign-chart.component.html',
  styles: ``,
})
export class CampaignChartComponent {
  campaigns: Partial<ChartOptions> = {
    chart: {
      height: 300,
      type: 'donut',
    },
    series: [44, 55, 41],
    legend: {
      show: false,
      position: 'bottom',
      horizontalAlign: 'center',
    },
    labels: ['Total Sent', 'Reached', 'Opened'],
    colors: ['#f7b84b', '#1abc9c', '#3bafda'],
    responsive: [
      {
        breakpoint: 600,
        options: {
          chart: {
            height: 210,
          },
          legend: {
            show: false,
          },
        },
      },
    ],
  }
}

<div class="card">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <h4 class="header-title">Campaigns</h4>
      <div class="btn-group mb-2">
        <button type="button" class="btn btn-xs btn-light active">Today</button>
        <button type="button" class="btn btn-xs btn-light">Weekly</button>
        <button type="button" class="btn btn-xs btn-light">Monthly</button>
      </div>
    </div>
    <div class="mt-3" dir="ltr">
      <div
        id="campaigns-chart"
        class="apex-charts"
        data-colors="#f7b84b,#1abc9c,#3bafda"
      >
        <apx-chart
          [chart]="campaigns.chart!"
          [series]="campaigns.series!"
          [legend]="campaigns.legend!"
          [labels]="campaigns.labels!"
          [colors]="campaigns.colors!"
          [responsive]="campaigns.responsive!"
        />
      </div>
    </div>
    <div class="row text-center mt-2">
      <div class="col-sm-4">
        <h4 class="fw-normal mt-3">
          <span>6,510</span>
        </h4>
        <p class="text-muted mb-0 mb-2">
          <i class="mdi mdi-checkbox-blank-circle text-warning"></i> Total Sent
        </p>
      </div>
      <div class="col-sm-4">
        <h4 class="fw-normal mt-3">
          <span>3,487</span>
        </h4>
        <p class="text-muted mb-0 mb-2">
          <i class="mdi mdi-checkbox-blank-circle text-success"></i> Reached
        </p>
      </div>
      <div class="col-sm-4">
        <h4 class="fw-normal mt-3">
          <span>1,568</span>
        </h4>
        <p class="text-muted mb-0 mb-2">
          <i class="mdi mdi-checkbox-blank-circle text-primary"></i> Opened
        </p>
      </div>
    </div>
  </div>
</div>
<!-- end card-->

// Minton_v10.1.0/React.js/JS/src/app/(admin)/dashboard/crm/CampaignChart.jsx
import { Button, ButtonGroup, Card, CardBody, Col, Row } from "react-bootstrap";
import classNames from "classnames";
import ReactApexChart from "react-apexcharts";

// chart

const CampaignStatistics = ({
  title,
  stats,
  bulletVariant
}) => {
  return <>
      <h4 className="fw-normal mt-3">
        <span>{stats}</span>
      </h4>
      <p className="text-muted mb-0 mb-2">
        <i className={classNames("mdi", "mdi-checkbox-blank-circle", "text-" + bulletVariant)}></i>{" "}
        {title}
      </p>
    </>;
};
const CampaignsChart = () => {
  const options = {
    chart: {
      height: 280,
      type: "donut"
    },
    legend: {
      show: false,
      position: "bottom",
      horizontalAlign: "center"
    },
    labels: ["Total Sent", "Reached", "Opened"],
    colors: ["#f7b84b", "#1abc9c", "#3bafda"],
    responsive: [{
      breakpoint: 600,
      options: {
        chart: {
          height: 210
        },
        legend: {
          show: false
        }
      }
    }]
  };
  const series = [44, 55, 41];
  return <Card>
      <CardBody>
        <div className="d-flex justify-content-between">
          <h4 className="header-title">Campaigns</h4>
          <ButtonGroup className="mb-2">
            <Button variant="light" className="btn-xs active">
              Today
            </Button>
            <Button variant="light" className="btn-xs">
              Weekly
            </Button>
            <Button variant="light" className="btn-xs">
              Monthly
            </Button>
          </ButtonGroup>
        </div>

        <div className="mt-3" dir="ltr">
          <ReactApexChart options={options} series={series} type="donut" height={280} className="apex-charts" />
        </div>

        <Row className="text-center mt-2">
          <Col sm={4}>
            <CampaignStatistics title="Total Sent" stats="6,510" bulletVariant="warning" />
          </Col>

          <Col sm={4}>
            <CampaignStatistics title="Reached" stats="3,487" bulletVariant="success" />
          </Col>

          <Col sm={4}>
            <CampaignStatistics title="Opened" stats="1,568" bulletVariant="primary" />
          </Col>
        </Row>
      </CardBody>
    </Card>;
};
export default CampaignsChart;
