// Minton_v10.1.0/React.js/JS/src/app/(auth)/auth/login/page.jsx
;
import { AuthLayout, SocialLinks } from "@/components";
import { FormInput } from "@/components/Form";
import { Button, Col, Row } from "react-bootstrap";
import { Link } from "react-router-dom";
import useSignIn from "./useSignIn";

/* bottom links */
const BottomLink = () => {
  return <Row className="mt-3">
            <Col xs={12} className="text-center">
                <p className="text-muted">
                    <Link to="/auth/forget-password" className="text-muted ms-1">
                        Forgot your password?
                    </Link>
                </p>
                <p className="text-muted">
                    Don&apos;t have an account?
                    <Link to="/auth/register" className="text-primary fw-bold ms-1">
                        Sign Up
                    </Link>
                </p>
            </Col>
        </Row>;
};
const Login = () => {
  const {
    loading,
    login,
    control
  } = useSignIn();
  return <AuthLayout helpText="Enter your email address and password to access admin panel." bottomLinks={<BottomLink />}>
            <form onSubmit={login}>
                <FormInput type="email" name="email" label="Email address" containerClass={"mb-2"} control={control} defaultValue="user@demo.com" />
                <FormInput label="Password" type="password" name="password" containerClass={"mb-2"} control={control} defaultValue="123456"></FormInput>

                <FormInput type="checkbox" name="checkbox" label="Remember me" containerClass={"mb-3"} defaultChecked control={control} />

                <div className="text-center d-grid">
                    <Button variant="primary" type="submit" disabled={loading}>
                        Log In
                    </Button>
                </div>
            </form>
            <div className="text-center">
                <h5 className="mt-3 text-muted">Sign in with</h5>
                <SocialLinks />
            </div>
        </AuthLayout>;
};
export default Login;

// Minton_v10.1.0/Angular/Starter-Kit/src/app/views/auth/login/login.component.ts
import { CommonModule } from '@angular/common'
import { Component, inject } from '@angular/core'
import {
  FormsModule,
  ReactiveFormsModule,
  UntypedFormBuilder,
  Validators,
  type UntypedFormGroup,
} from '@angular/forms'
import { Router, RouterModule } from '@angular/router'
import { Store } from '@ngrx/store'

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [RouterModule, CommonModule, FormsModule, ReactiveFormsModule],
  templateUrl: './login.component.html',
  styles: ``,
})
export class LoginComponent {
  signinForm!: UntypedFormGroup
  submitted: boolean = false

  public fb = inject(UntypedFormBuilder)
  store = inject(Store)
  route = inject(Router)
}

<div class="card">
  <div class="card-body p-4">
    <div class="text-center w-75 m-auto">
      <div class="auth-logo">
        <a routerLink="/" class="logo logo-dark text-center">
          <span class="logo-lg">
            <img src="assets/images/logo-dark.png" alt="" height="22" />
          </span>
        </a>

        <a routerLink="/" class="logo logo-light text-center">
          <span class="logo-lg">
            <img src="assets/images/logo-light.png" alt="" height="22" />
          </span>
        </a>
      </div>
      <p class="text-muted mb-4 mt-3">
        Enter your email address and password to access admin panel.
      </p>
    </div>

    <form>
      <div class="mb-2">
        <label for="emailaddress" class="form-label">Email address</label>
        <input
          class="form-control"
          type="email"
          id="emailaddress"
          required=""
          placeholder="Enter your email"
        />
      </div>

      <div class="mb-2">
        <label for="password" class="form-label">Password</label>
        <div class="input-group input-group-merge">
          <input
            type="password"
            id="password"
            class="form-control"
            placeholder="Enter your password"
          />

          <div class="input-group-text" data-password="false">
            <span class="password-eye"></span>
          </div>
        </div>
      </div>

      <div class="mb-3">
        <div class="form-check">
          <input
            class="form-check-input"
            type="checkbox"
            id="checkbox-signin"
            checked
          />
          <label class="form-check-label" for="checkbox-signin">
            Remember me
          </label>
        </div>
      </div>

      <div class="d-grid mb-0 text-center">
        <button class="btn btn-primary" type="submit">Log In</button>
      </div>
    </form>

    <div class="text-center">
      <h5 class="mt-3 text-muted">Sign in with</h5>
      <ul class="social-list list-inline mt-3 mb-0">
        <li class="list-inline-item">
          <a
            href="javascript: void(0);"
            class="social-list-item border-purple text-purple"
            ><i class="mdi mdi-facebook"></i
          ></a>
        </li>
        <li class="list-inline-item">
          <a
            href="javascript: void(0);"
            class="social-list-item border-danger text-danger"
            ><i class="mdi mdi-google"></i
          ></a>
        </li>
        <li class="list-inline-item">
          <a
            href="javascript: void(0);"
            class="social-list-item border-info text-info"
            ><i class="mdi mdi-twitter"></i
          ></a>
        </li>
        <li class="list-inline-item">
          <a
            href="javascript: void(0);"
            class="social-list-item border-secondary text-secondary"
            ><i class="mdi mdi-github"></i
          ></a>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="row mt-3">
  <div class="col-12 text-center">
    <p>
      <a routerLink="/auth/recoverpw" class="text-muted ms-1"
        >Forgot your password?</a
      >
    </p>
    <p class="text-muted">
      Don't have an account?
      <a routerLink="/auth/register" class="text-primary fw-medium ms-1"
        >Sign Up</a
      >
    </p>
  </div>
</div>
