// Minton_v10.1.0/Next.js/TS/src/app/(admin)/pages/search-results/AllResult.tsx
import React from "react";
import Link from "next/link";

// dummy data
import { AllResultType } from "./data";

// conver text into html
const createMarkup = (text: string) => {
  return { __html: text };
};

interface AllResultProps {
  allResults: AllResultType[];
}

const AllResult = ({ allResults }: AllResultProps) => {
  return (
    <>
      <div className="row">
        <div className="col-md-12">
          {(allResults || []).map((searchItem, index) => {
            return (
              <div key={index} className="search-item">
                {searchItem.title && (
                  <h4 className="mb-1">
                    <Link href="">{searchItem.title}</Link>
                  </h4>
                )}
                {searchItem.url && (
                  <div className="font-13 text-success mb-2 text-truncate">
                    {searchItem.url}
                  </div>
                )}
                <div
                  dangerouslySetInnerHTML={createMarkup(searchItem.content!)}
                ></div>
              </div>
            );
          })}

          <ul className="pagination pagination-rounded justify-content-end mt-0">
            <li className="page-item">
              <Link className="page-link" href="" aria-label="Previous">
                <span aria-hidden="true">«</span>
                <span className="visually-hidden">Previous</span>
              </Link>
            </li>
            <li className="page-item">
              <Link className="page-link" href="">
                1
              </Link>
            </li>
            <li className="page-item active">
              <Link className="page-link" href="">
                2
              </Link>
            </li>
            <li className="page-item">
              <Link className="page-link" href="">
                3
              </Link>
            </li>
            <li className="page-item">
              <Link className="page-link" href="">
                4
              </Link>
            </li>
            <li className="page-item">
              <Link className="page-link" href="">
                5
              </Link>
            </li>
            <li className="page-item">
              <Link className="page-link" href="" aria-label="Next">
                <span aria-hidden="true">»</span>
                <span className="visually-hidden">Next</span>
              </Link>
            </li>
          </ul>

          <div className="clearfix"></div>
        </div>
      </div>
    </>
  );
};

export default AllResult;

// Minton_v10.1.0/Angular/Minton/src/app/views/extra-pages/search-results/components/all-result/all-result.component.ts
import { Component, inject, type OnInit } from '@angular/core'
import { allResults } from '../../data'
import { NgbPaginationModule } from '@ng-bootstrap/ng-bootstrap'
import {
  DomSanitizer,
  type SafeHtml,
  type SafeResourceUrl,
} from '@angular/platform-browser'

@Component({
  selector: 'search-all-result',
  standalone: true,
  imports: [NgbPaginationModule],
  templateUrl: './all-result.component.html',
  styles: ``,
})
export class AllResultComponent implements OnInit {
  resultList = allResults
  public safeResults: any[] = []

  private sanitizer = inject(DomSanitizer)

  ngOnInit() {
    this.safeResults = this.resultList.map((result) => ({
      ...result,
      safeContent: this.sanitizer.bypassSecurityTrustHtml(result.content!),
    }))
  }
}

<div class="row">
  <div class="col-md-12">
    @for (item of safeResults; track $index) {
      <div class="search-item">
        <h4 class="mb-1">
          <a href="javascript:void(0);">{{ item.title }}</a>
        </h4>
        <div class="font-13 text-success mb-2 text-truncate">
          {{ item.url }}
        </div>
        <p class="mb-0 text-muted" [innerHTML]="item.safeContent"></p>
      </div>
    }

    <ngb-pagination
      [collectionSize]="50"
      [page]="2"
      class="pagination justify-content-end pagination-rounded mt-0"
    ></ngb-pagination>

    <div class="clearfix"></div>
  </div>
</div>
