// Minton_v10.1.0/Next.js/JS/src/app/(admin)/pages/search-results/page.jsx
import React from "react";
// components
import PageBreadcrumb from "@/components/PageBreadcrumb";
import ResultList from "@/app/(admin)/pages/search-results/ResultList";
export const metadata = {
  title: "Search Results"
};
const SearchResults = () => {
  return <>
      <PageBreadcrumb breadCrumbItems={[{
      label: "Extra Pages",
      path: "/pages/search-results"
    }, {
      label: "Search Results",
      path: "/pages/search-results",
      active: true
    }]} title={"Search Results"} />

      <div className="row">
        <div className="col">
          <div className="card search-result-box">
            <div className="card-body">
              <div className="row">
                <div className="col-md-8 offset-md-2">
                  <div className="pt-3 pb-4">
                    <div className="input-group">
                      <input type="text" className="form-control" defaultValue="Admin Dashboard" />
                      <button type="button" className="input-group-text btn waves-effect waves-light btn-purple">
                        <i className="fa fa-search me-1"></i> Search
                      </button>
                    </div>
                    <div className="mt-3 text-center">
                      <h4>Search Results For &quot;Admin Dashboard&quot;</h4>
                    </div>
                  </div>
                </div>
              </div>
              <ResultList />
            </div>
          </div>
        </div>
      </div>
    </>;
};
export default SearchResults;

// Minton_v10.1.0/Angular/Minton/src/app/views/extra-pages/search-results/search-results.component.ts
import { Component } from '@angular/core'
import { PageTitleComponent } from '@component/page-title.component'
import { AllResultComponent } from './components/all-result/all-result.component'
import { UsersComponent } from './components/users/users.component'
import { NgbNavModule } from '@ng-bootstrap/ng-bootstrap'

@Component({
  selector: 'app-search-results',
  standalone: true,
  imports: [
    PageTitleComponent,
    AllResultComponent,
    UsersComponent,
    NgbNavModule,
  ],
  templateUrl: './search-results.component.html',
  styles: ``,
})
export class SearchResultsComponent {
  breadCrumbItems = [
    { label: 'Extras', path: '/pages/search-results' },
    { label: 'Search Results', path: '/pages/search-results', active: true },
  ]
}

<app-page-title title="Search Results" [breadCrumbItems]="breadCrumbItems" />

<div class="row">
  <div class="col-lg-12">
    <div class="search-result-box card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-8 offset-md-2">
            <div class="pt-3 pb-4">
              <div class="input-group">
                <input
                  type="text"
                  class="form-control"
                  value="Admin Dashboard"
                />

                <button
                  type="button"
                  class="btn waves-effect waves-light btn-purple"
                >
                  <i class="fa fa-search me-1"></i> Search
                </button>
              </div>
              <div class="mt-3 text-center">
                <h4>Search Results For "Admin Dashboard"</h4>
              </div>
            </div>
          </div>
        </div>

        <ul ngbNav #nav="ngbNav" class="nav nav-tabs nav-bordered">
          <li ngbNavItem class="nav-item">
            <a ngbNavLink class="nav-link">
              All results <span class="badge bg-success ms-1">325</span>
            </a>
            <ng-template ngbNavContent>
              <search-all-result />
            </ng-template>
          </li>
          <li ngbNavItem class="nav-item">
            <a ngbNavLink class="nav-link">
              Users <span class="badge bg-danger ms-1">89</span>
            </a>
            <ng-template ngbNavContent>
              <search-users />
            </ng-template>
          </li>
        </ul>

        <div [ngbNavOutlet]="nav" class="tab-content"></div>
      </div>
    </div>
  </div>
</div>
