// Minton_v10.1.0/Angular/Starter-Kit/src/app/views/auth/signin-signup/signin-signup.component.ts
import { Component } from '@angular/core'
import { RouterModule } from '@angular/router'
import { credits, currentYear } from '@common/constants'

@Component({
  selector: 'app-signin-signup',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './signin-signup.component.html',
  styles: ``,
})
export class SigninSignupComponent {
  year = currentYear
  credits = credits
}

<div class="account-pages mt-5 mb-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-xl-9">
        <div class="card">
          <div class="card-body p-4">
            <div class="text-center mb-4">
              <div class="auth-logo">
                <a routerLink="/" class="logo logo-dark text-center">
                  <span class="logo-lg">
                    <img src="assets/images/logo-dark.png" alt="" height="22" />
                  </span>
                </a>

                <a routerLink="/" class="logo logo-light text-center">
                  <span class="logo-lg">
                    <img
                      src="assets/images/logo-light.png"
                      alt=""
                      height="22"
                    />
                  </span>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-lg-6">
                <div class="p-sm-3">
                  <!-- title-->
                  <h4 class="mt-0">Sign In</h4>
                  <p class="text-muted mb-4">
                    Enter your email address and password to access account.
                  </p>
                  <form action="#">
                    <div class="mb-3">
                      <label for="emailaddress" class="form-label"
                        >Email address</label
                      >
                      <input
                        class="form-control"
                        type="email"
                        id="emailaddress"
                        required=""
                        placeholder="Enter your email"
                      />
                    </div>

                    <div class="mb-3">
                      <a
                        routerLink="/auth/recoverpw"
                        class="text-muted font-13 float-end"
                        >Forgot your password?</a
                      >
                      <label for="password" class="form-label">Password</label>
                      <input
                        class="form-control"
                        type="password"
                        required=""
                        id="password"
                        placeholder="Enter your password"
                      />
                    </div>

                    <div class="mb-3">
                      <button
                        class="btn btn-primary float-sm-end"
                        type="submit"
                      >
                        Log In
                      </button>
                      <div class="form-check">
                        <input
                          class="form-check-input"
                          type="checkbox"
                          id="checkbox-signin"
                          checked
                        />
                        <label class="form-check-label" for="checkbox-signin">
                          Remember me
                        </label>
                      </div>
                    </div>
                  </form>
                </div>
              </div>

              <div class="col-lg-6">
                <div class="p-sm-3">
                  <h4 class="mt-3 mt-lg-0">Free Sign Up</h4>
                  <p class="text-muted mb-4">
                    Don't have an account? Create your account, it takes less
                    than a minute
                  </p>

                  <form action="#">
                    <div class="mb-3">
                      <label for="fullname" class="form-label">Full Name</label>
                      <input
                        class="form-control"
                        type="text"
                        id="fullname"
                        placeholder="Enter your name"
                        required
                      />
                    </div>
                    <div class="mb-3">
                      <label for="emailaddress2" class="form-label"
                        >Email address</label
                      >
                      <input
                        class="form-control"
                        type="email"
                        id="emailaddress2"
                        required
                        placeholder="Enter your email"
                      />
                    </div>
                    <div class="mb-3">
                      <label for="password2" class="form-label">Password</label>
                      <input
                        class="form-control"
                        type="password"
                        required
                        id="password2"
                        placeholder="Enter your password"
                      />
                    </div>
                    <div>
                      <button
                        class="btn btn-success float-sm-end"
                        type="submit"
                      >
                        Sign Up
                      </button>
                      <div class="form-check pt-1 overflow-hidden">
                        <input
                          class="form-check-input"
                          type="checkbox"
                          id="checkbox-signup"
                        />
                        <label class="form-check-label" for="checkbox-signup">
                          I accept
                          <a href="javascript: void(0);" class="text-dark"
                            >Terms and Conditions</a
                          >
                        </label>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
            <!-- end row-->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<footer class="footer footer-alt">
  {{ year }} &copy; Minton theme by
  <a href="javascript:void(0);" class="text-dark">{{ credits.name }}</a>
</footer>

// Minton_v10.1.0/Next.js/JS/src/app/(auth)/auth/signin-signup/page.jsx
"use client";

import React from "react";
import { Button } from "react-bootstrap";

// components
import { FormInput } from "@/components/Form";
import { AuthLayout } from "@/components";
import Link from "next/link";
const SignInSignUp = () => {
  return <>
            <AuthLayout isCombineForm={true}>
                <div className="row mt-4">
                    <div className="col-lg-6">
                        <div className="p-sm-3">
                            <h4 className="mt-0">Sign In</h4>
                            <p className="text-muted mb-4">
                                Enter your email address and password to access account.
                            </p>

                            <form>
                                <FormInput type="email" name="email" label="Email address" placeholder="hello@coderthemes.com" containerClass={"mb-3"} />
                                <FormInput label="Password" type="password" name="loginpassword" placeholder="Enter your password" containerClass={"mb-3"}>
                                    <Link href="/auth/forget-password" className="text-muted float-end">
                                        <small>Forgot your password?</small>
                                    </Link>
                                </FormInput>

                                <div className="mb-3">
                                    <Button variant="primary" type="submit" className="btn btn-primary float-sm-end">
                                        Log In
                                    </Button>
                                    <FormInput label="Remember me" type="checkbox" name="checkbox" />
                                </div>
                            </form>
                        </div>
                    </div>

                    <div className="col-lg-6">
                        <div className="p-sm-3">
                            <h4 className="mt-0">Free Sign Up</h4>
                            <p className="text-muted mb-4">
                                Don&apos;t have an account? Create your account, it takes less than a minute
                            </p>

                            <form>
                                <FormInput label="Full Name" type="text" name="fullname" placeholder="Enter your name" containerClass={"mb-3"} />
                                <FormInput label="Email address" type="email" name="email2" placeholder="Enter your email" containerClass={"mb-3"} />
                                <FormInput label="Password" type="password" name="password" placeholder="Enter your password" containerClass={"mb-3"} />

                                <div className="mb-0">
                                    <Button variant="success" type="submit" className="btn btn-success float-sm-end">
                                        Sign Up
                                    </Button>
                                    <FormInput label="I accept Terms and Conditions" type="checkbox" name="checkboxsignup" containerClass={"pt-1"} />
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </AuthLayout>
        </>;
};
export default SignInSignUp;
