// Minton_v10.1.0/Angular/Minton/src/app/layouts/right-sidebar/right-sidebar.component.ts
import { Component, inject } from '@angular/core'
import { NgbActiveOffcanvas, NgbNavModule } from '@ng-bootstrap/ng-bootstrap'
import { SimplebarAngularModule } from 'simplebar-angular'
import { ChatComponent } from './components/chat/chat.component'
import { TaskComponent } from './components/task/task.component'
import { ThemeSettingComponent } from './components/theme-setting/theme-setting.component'

@Component({
  selector: 'app-right-sidebar',
  standalone: true,
  imports: [
    SimplebarAngularModule,
    NgbNavModule,
    ChatComponent,
    TaskComponent,
    ThemeSettingComponent,
  ],
  templateUrl: './right-sidebar.component.html',
  styles: `
    :host {
      display: contents;
    }
  `,
})
export class RightSidebarComponent {
  offcanvas = inject(NgbActiveOffcanvas)
}

<ngx-simplebar data-simplebar class="h-100">
  <ul
    ngbNav
    #nav="ngbNav"
    [activeId]="3"
    class="nav nav-tabs nav-bordered nav-justified"
    role="tablist"
  >
    <li [ngbNavItem]="1" class="nav-item">
      <a ngbNavLink class="nav-link py-2" role="tab">
        <i class="mdi mdi-message-text-outline d-block font-22 my-1"></i>
      </a>
      <ng-template ngbNavContent>
        <sidebar-chat />
      </ng-template>
    </li>
    <li [ngbNavItem]="2" class="nav-item">
      <a ngbNavLink class="nav-link py-2" role="tab">
        <i class="mdi mdi-format-list-checkbox d-block font-22 my-1"></i>
      </a>
      <ng-template ngbNavContent>
        <sidebar-task />
      </ng-template>
    </li>
    <li [ngbNavItem]="3" class="nav-item">
      <a ngbNavLink class="nav-link py-2" role="tab">
        <i class="mdi mdi-cog-outline d-block font-22 my-1"></i>
      </a>
      <ng-template ngbNavContent>
        <sidebar-theme-setting />
      </ng-template>
    </li>
  </ul>

  <div [ngbNavOutlet]="nav" class="tab-content pt-0"></div>
</ngx-simplebar>

<!-- Right bar overlay-->
<div class="rightbar-overlay"></div>

// Minton_v10.1.0/React.js/TS/src/layouts/RightSidebar/index.tsx
import React, { useRef } from "react";
import { Nav, Offcanvas, Tab } from "react-bootstrap";

// components
import Chats from "../../components/Chats";
import Tasks from "../../components/Tasks";
import ThemeCustomizer from "../../components/ThemeCustomizer";

import { useLayoutContext } from "@/context/useLayoutContext";
import SimpleBar from "simplebar-react";
import { chats, tasks } from "./data";


const RightSideBar = () => {

    const {themeCustomizer} = useLayoutContext()

    const rightBarNodeRef: any = useRef(null);

    return (
        <React.Fragment>
            <Offcanvas
                show={themeCustomizer.open}
                onHide={themeCustomizer.toggle}
                className="right-bar"
                placement="end"
            >
                <div className="h-100" ref={rightBarNodeRef}>
                    <SimpleBar style={{maxHeight: '100%', zIndex: 10000}} scrollbarMaxSize={320}>
                        <Tab.Container
                            defaultActiveKey="themecustomizer"
                        >
                            <Nav
                                variant="tabs"
                                as="ul"
                                className="nav-bordered nav-justified"
                            >
                                <Nav.Item as="li">
                                    <Nav.Link eventKey="chats" className="py-2">
                                        <i className="mdi mdi-message-text-outline d-block font-22 my-1"/>
                                    </Nav.Link>
                                </Nav.Item>
                                <Nav.Item as="li">
                                    <Nav.Link eventKey="tasks" className="py-2">
                                        <i className="mdi mdi-format-list-checkbox d-block font-22 my-1"/>
                                    </Nav.Link>
                                </Nav.Item>
                                <Nav.Item as="li">
                                    <Nav.Link eventKey="themecustomizer" className="py-2">
                                        <i className="mdi mdi-cog-outline d-block font-22 my-1"/>
                                    </Nav.Link>
                                </Nav.Item>
                            </Nav>

                            <Tab.Content className="pt-0">
                                <Tab.Pane eventKey="chats">
                                    <Chats chats={chats}/>
                                </Tab.Pane>
                                <Tab.Pane eventKey="tasks">
                                    <Tasks tasks={tasks}/>
                                </Tab.Pane>
                                <Tab.Pane eventKey="themecustomizer">
                                    <ThemeCustomizer/>
                                </Tab.Pane>
                            </Tab.Content>
                        </Tab.Container>
                    </SimpleBar>
                </div>
            </Offcanvas>
            <div className="rightbar-overlay"></div>
        </React.Fragment>
    );
};

export default RightSideBar;
