// Minton_v10.1.0/Angular/Starter-Kit/src/app/views/auth/lock-screen/lock-screen.component.ts
import { Component } from '@angular/core'
import { RouterModule } from '@angular/router'

@Component({
  selector: 'app-lock-screen',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './lock-screen.component.html',
  styles: ``,
})
export class LockScreenComponent {}

<div class="card">
  <div class="card-body p-4">
    <div class="text-center mb-4">
      <div class="auth-logo">
        <a routerLink="/" class="logo logo-dark text-center">
          <span class="logo-lg">
            <img src="assets/images/logo-dark.png" alt="" height="22" />
          </span>
        </a>

        <a routerLink="/" class="logo logo-light text-center">
          <span class="logo-lg">
            <img src="assets/images/logo-light.png" alt="" height="22" />
          </span>
        </a>
      </div>
    </div>

    <div class="text-center w-75 m-auto">
      <img
        src="assets/images/users/avatar-1.jpg"
        alt="user-image"
        class="rounded-circle avatar-lg img-thumbnail"
      />
      <h4 class="text-dark-50 text-center mt-3">Hi ! Nik Patel</h4>
      <p class="text-muted mb-4">Enter your password to access the admin.</p>
    </div>

    <form action="#">
      <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input
          class="form-control"
          type="password"
          required=""
          id="password"
          placeholder="Enter your password"
        />
      </div>

      <div class="d-grid text-center">
        <button class="btn btn-primary" type="submit">Log In</button>
      </div>
    </form>
  </div>
</div>

<div class="row mt-3">
  <div class="col-12 text-center">
    <p class="text-muted">
      Not you? return
      <a routerLink="/auth/login" class="text-primary fw-medium ms-1"
        >Sign In</a
      >
    </p>
  </div>
</div>

// Minton_v10.1.0/Next.js/JS/src/app/(auth)/auth/lock-screen/page.jsx
"use client";

import React from "react";
import { Button } from "react-bootstrap";
import * as yup from "yup";
import { yupResolver } from "@hookform/resolvers/yup";

// components
import { VerticalForm, FormInput } from "@/components/Form";
import { AuthLayout } from "@/components";

// images
import userImg from "@/assets/images/users/avatar-1.jpg";
import Link from "next/link";
import Image from "next/image";
/* bottom link */
const BottomLink = () => {
  return <div className="row mt-3">
      <div className="col-xs-12 text-center">
        <p className="text-muted">
          Not you? return{" "}
          <Link href={"/auth/login"} className="text-primary fw-medium ms-1">
            <b>Sign In</b>
          </Link>
        </p>
      </div>
    </div>;
};
const LockScreen = () => {
  /*
   * form validation schema
   */
  const schemaResolver = yupResolver(yup.object().shape({
    password: yup.string().required("Please enter Password")
  }));
  return <>
      <AuthLayout bottomLinks={<BottomLink />}>
        <div className="text-center w-75 m-auto mt-4">
          <Image src={userImg} alt="" className="rounded-circle avatar-lg img-thumbnail" height={72} width={72} />
          <h4 className="text-dark-50 text-center mt-3">
            Hi ! Nik Patel 
          </h4>
          <p className="text-muted mb-4">
            Enter your password to access the admin.
          </p>
        </div>
        <VerticalForm onSubmit={() => {}} resolver={schemaResolver}>
          <FormInput label="Password" type="password" name="password" placeholder="Enter your password" containerClass={"mb-3"} />

          <div className="d-grid text-center">
            <Button variant="primary" type="submit">
              Log In
            </Button>
          </div>
        </VerticalForm>
      </AuthLayout>
    </>;
};
export default LockScreen;
