// Minton_v10.1.0/React.js/TS/src/app/(admin)/dashboard/analytics/SessionOverview.tsx

import {Fragment} from "react";
import {Card, CardBody, Col, ProgressBar, Row} from "react-bootstrap";
import { Link } from "react-router-dom";
// types
import {SessionSummaryType} from "./data";
import { UsaVectorMap } from "@/components/VectorMap";


interface SessionOverviewProps {
    sessionSummary: SessionSummaryType[];
}

const SessionOverview = ({sessionSummary}: SessionOverviewProps) => {
    return (
        <Card>
            <CardBody>
                <ul className="nav float-end d-none d-lg-flex">
                    <li className="nav-item">
                        <Link className="nav-link text-muted" to="">
                            Today
                        </Link>
                    </li>
                    <li className="nav-item">
                        <Link className="nav-link text-muted" to="">
                            7d
                        </Link>
                    </li>
                    <li className="nav-item">
                        <Link className="nav-link active" to="">
                            15d
                        </Link>
                    </li>
                    <li className="nav-item">
                        <Link className="nav-link text-muted" to="">
                            1m
                        </Link>
                    </li>
                    <li className="nav-item">
                        <Link className="nav-link text-muted" to="">
                            1y
                        </Link>
                    </li>
                </ul>

                <h4 className="header-title mb-3">Sessions Overview</h4>

                <Row className="align-items-center">
                    <Col xl={8}>
                        <UsaVectorMap
                            height="363px"
                            width="100%"
                            options={{
                                zoomOnScroll: false,
                                backgroundColor: "transparent",
                                regionStyle: {
                                    initial: {
                                        fill: "#3bafda",
                                    },
                                },
                            }}
                        />
                    </Col>
                    <Col xl={4}>
                        {sessionSummary.length > 0 &&
                            sessionSummary.map((session, index) => {
                                return (
                                    <Fragment key={index}>
                                        <h5 className="mb-1 mt-0">
                                            {session.stats}{" "}
                                            <small className="text-muted ms-2">
                                                {session.website}
                                            </small>
                                        </h5>
                                        <Row className="align-items-center g-0 mb-2 pb-1">
                                            <Col>
                                                <ProgressBar
                                                    variant={session.progressVariant}
                                                    now={session.progressValue}
                                                    className="progress-sm"
                                                />
                                            </Col>
                                            <Col>
                                                <div className="fw-medium ms-2">
                                                    {session.progressValue}%
                                                </div>
                                            </Col>
                                        </Row>
                                    </Fragment>
                                );
                            })}
                    </Col>
                </Row>
            </CardBody>
        </Card>
    );
};

export default SessionOverview;

// Minton_v10.1.0/Angular/Minton/src/app/views/dashboard/analytics/components/session-overview/session-overview.component.ts
import { Component } from '@angular/core'
import { sessionSummary } from '../../data'
import { NgbProgressbarModule } from '@ng-bootstrap/ng-bootstrap'
import { WorldVectorMapComponent } from '@component/vector-maps/world-vector-map.component'
import 'jsvectormap'
import 'jsvectormap/dist/maps/us-merc-en'

@Component({
  selector: 'analytics-session-overview',
  standalone: true,
  imports: [NgbProgressbarModule, WorldVectorMapComponent],
  templateUrl: './session-overview.component.html',
  styles: ``,
})
export class SessionOverviewComponent {
  sessionList = sessionSummary

  usaMapConfig = {
    backgroundColor: 'transparent',
    regionStyle: {
      initial: {
        fill: '#3bafda',
      },
    },
  }
}

<div class="card">
  <div class="card-body">
    <ul class="nav float-end d-none d-lg-flex">
      <li class="nav-item">
        <a class="nav-link text-muted" href="javascript:void(0);">Today</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-muted" href="javascript:void(0);">7d</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="javascript:void(0);">15d</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-muted" href="javascript:void(0);">1m</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-muted" href="javascript:void(0);">1y</a>
      </li>
    </ul>
    <h4 class="header-title mb-3">Sessions Overview</h4>

    <div class="row align-items-center">
      <div class="col-xl-8">
        <div id="usa-vectormap" style="height: 363px" data-colors="#3bafda">
          <app-world-vector-map
            mapId="usa-vector-map"
            type="us_merc_en"
            [options]="usaMapConfig"
            height="363px"
            width="100%"
          ></app-world-vector-map>
        </div>
      </div>
      <div class="col-xl-4">
        @for (item of sessionList; track $index) {
          <h5 class="mb-1 mt-0">
            {{ item.stats }}
            <small class="text-muted ms-2">{{ item.website }}</small>
          </h5>
          <div class="row align-items-center g-0 mb-2 pb-1">
            <div class="col">
              <ngb-progressbar
                [type]="item.progressVariant"
                [value]="item.progressValue"
                class="progress-sm"
              />
            </div>
            <div class="col-auto">
              <div class="fw-medium ms-2">{{ item.progressValue }}%</div>
            </div>
          </div>
        }
      </div>
    </div>
  </div>
  <!-- end card-body-->
</div>
<!-- end card-->
