// Minton_v10.1.0/Angular/Minton/src/app/views/pages/coming-soon/coming-soon.component.ts
import { Component, type OnDestroy, type OnInit } from '@angular/core'
import { credits, currentYear } from '@common/constants'
import { calculateTimeToEvent } from '@helper/utils'
import { interval, type Subscription } from 'rxjs'

@Component({
  selector: 'app-coming-soon',
  standalone: true,
  imports: [],
  templateUrl: './coming-soon.component.html',
  styles: ``,
})
export class ComingSoonComponent implements OnInit, OnDestroy {
  year = currentYear
  credits = credits

  _days?: number
  _hours?: number
  _minutes?: number
  _seconds?: number
  countdown: { days: number; hours: number; minutes: number; seconds: number } =
    {
      days: 0,
      hours: 0,
      minutes: 0,
      seconds: 0,
    }
  private intervalSubscription!: Subscription

  ngOnInit(): void {
    this.countdown = calculateTimeToEvent()
    this.intervalSubscription = interval(1000).subscribe(() => {
      this.countdown = calculateTimeToEvent()
    })
  }

  ngOnDestroy(): void {
    this.intervalSubscription.unsubscribe()
  }
}

<div class="my-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-10">
        <div class="text-center">
          <img
            src="assets/images/animat-rocket-color.gif"
            alt=""
            height="160"
          />

          <h3 class="mt-4">Stay tunned, we're launching very soon</h3>
          <p class="text-muted">We're making the system more awesome.</p>

          <div class="row mt-5 justify-content-center">
            <div class="col-md-8">
              <div class="counter-number">
                <div class="coming-box">
                  {{ countdown.days }} <span>Days</span>
                </div>
                <div class="coming-box">
                  {{ countdown.hours }} <span>Hours</span>
                </div>
                <div class="coming-box">
                  {{ countdown.minutes }} <span>Minutes</span>
                </div>
                <div class="coming-box">
                  {{ countdown.seconds }} <span>Seconds</span>
                </div>
              </div>
            </div>
            <!-- end col-->
          </div>
          <!-- end row-->
        </div>
        <!-- end /.text-center-->
      </div>
    </div>
  </div>
</div>

<footer class="footer footer-alt">
  {{ year }} &copy; Minton theme by
  <a href="javascript:void(0);">{{ credits.name }}</a>
</footer>

// Minton_v10.1.0/Next.js/JS/src/app/(error)/coming-soon/page.jsx
import React from "react";
import Link from "next/link";
import Image from "next/image";
import Counter from "@/app/(error)/coming-soon/Counter";

// images
import rocketGif from "@/assets/images/animat-rocket-color.gif";
export const metadata = {
  title: "Coming Soon"
};
const ComingSoon = () => {
  return <>
      <div className="my-5">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-10">
              <div className="text-center">
                <Image src={rocketGif} alt="" height={160} width={160} />

                <h3 className="mt-4">Stay tunned, we&apos;re launching very soon</h3>
                <p className="text-muted">
                  We&apos;re making the system more awesome.
                </p>

                <div className="row mt-5 justify-content-center">
                  <div className="col-md-8">
                    <Counter />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <footer className="footer footer-alt">
        {new Date().getFullYear()} &copy; Minton theme by{" "}
        <Link href="https://coderthemes.com/" target='_blank'>Coderthemes</Link>
      </footer>
    </>;
};
export default ComingSoon;
