// Minton_v10.1.0/React.js/JS/src/app/(admin)/pages/starter/page.jsx
// components
import PageBreadcrumb from "@/components/PageBreadcrumb";
const Starter = () => {
  return <>
      <PageBreadcrumb breadCrumbItems={[{
      label: "Extra Pages",
      path: "/pages/starter"
    }, {
      label: "Starter",
      path: "/pages/starter",
      active: true
    }]} title={"Starter"} />
    </>;
};
export default Starter;

// Minton_v10.1.0/Angular/Minton/src/app/views/extra-pages/starter/starter.component.ts
import { Component } from '@angular/core'
import { PageTitleComponent } from '@component/page-title.component'

@Component({
  selector: 'app-starter',
  standalone: true,
  imports: [PageTitleComponent],
  templateUrl: './starter.component.html',
  styles: ``,
})
export class StarterComponent {
  breadCrumbItems = [
    { label: 'Extras', path: '' },
    { label: 'Starter', path: '', active: true },
  ]
}

<app-page-title title="Starter" [breadCrumbItems]="breadCrumbItems" />
