// Minton_v10.1.0/Angular/Minton/src/app/views/extra-pages/invoice/invoice.component.ts
import { Component } from '@angular/core'
import { PageTitleComponent } from '@component/page-title.component'
import { invoiceData } from '../data'
import { DecimalPipe } from '@angular/common'
import { RouterLink } from '@angular/router'
import { currency } from '@common/constants'

@Component({
  selector: 'app-invoice',
  standalone: true,
  imports: [PageTitleComponent, DecimalPipe, RouterLink],
  templateUrl: './invoice.component.html',
  styles: ``,
})
export class InvoiceComponent {
  breadCrumbItems = [
    { label: 'Extras', path: '/pages/invoice' },
    { label: 'Invoice', path: '/pages/invoice', active: true },
  ]

  currency = currency
  invoice = invoiceData
}

<app-page-title title="Invoice" [breadCrumbItems]="breadCrumbItems" />

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <div class="clearfix">
          <div class="float-start">
            <div class="auth-logo">
              <a routerLink="/" class="logo logo-dark">
                <span class="logo-lg">
                  <img src="assets/images/logo-dark.png" alt="" height="22" />
                </span>
              </a>

              <a routerLink="/" class="logo logo-light">
                <span class="logo-lg">
                  <img src="assets/images/logo-light.png" alt="" height="22" />
                </span>
              </a>
            </div>
          </div>
          <div class="float-end">
            <h4 class="m-0 d-print-none">Invoice</h4>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="mt-3">
              <p>
                <b>Hello, {{ invoice.customer }}</b>
              </p>
              <p class="text-muted">{{ invoice.notes }}</p>
            </div>
          </div>
          <div class="col-md-4 offset-md-2">
            <div class="mt-3 float-end">
              <p class="m-b-10">
                <strong>Order Date : </strong>
                <span class="float-end">
                  &nbsp;&nbsp;&nbsp;&nbsp; {{ invoice.order_date }}</span
                >
              </p>
              <p class="m-b-10">
                <strong>Order Status : </strong>
                <span class="float-end"
                  ><span class="badge bg-danger">{{
                    invoice.order_status
                  }}</span></span
                >
              </p>
              <p class="m-b-10">
                <strong>Order No. : </strong>
                <span class="float-end">{{ invoice.invoice_id }} </span>
              </p>
            </div>
          </div>
        </div>

        <div class="row mt-3">
          <div class="col-sm-6">
            <h5>Billing Address</h5>
            <address>
              {{ invoice.address.owner }}<br />
              {{ invoice.address.line_1 }}<br />
              {{ invoice.address.city }} {{ invoice.address.state }}
              {{ invoice.address.zip }}<br />
              <abbr title="Phone">P:</abbr> {{ invoice.address.phone }}
            </address>
          </div>

          <div class="col-sm-6">
            <h5>Shipping Address</h5>
            <address>
              {{ invoice.address.owner }}<br />
              {{ invoice.address.line_1 }}<br />
              {{ invoice.address.city }} {{ invoice.address.state }}
              {{ invoice.address.zip }}<br />
              <abbr title="Phone">P:</abbr> {{ invoice.address.phone }}
            </address>
          </div>
        </div>

        <div class="row">
          <div class="col-12">
            <div class="table-responsive">
              <table class="table mt-4 table-centered">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Item</th>
                    <th style="width: 10%">Hours</th>
                    <th style="width: 10%">Hours Rate</th>
                    <th style="width: 10%" class="text-end">Total</th>
                  </tr>
                </thead>
                <tbody>
                  @for (item of invoice.items; track $index) {
                    <tr>
                      <td>{{ item.id }}</td>
                      <td>
                        <b>{{ item.name }}</b> <br />
                        {{ item.description }}
                      </td>
                      <td>{{ item.hours }}</td>
                      <td>{{ currency }}{{ item.hour_rate }}</td>
                      <td class="text-end">
                        {{ currency }}{{ item.total | number: '2.2' }}
                      </td>
                    </tr>
                  }
                </tbody>
              </table>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-6">
            <div class="clearfix pt-5">
              <h6 class="text-muted">Notes:</h6>

              <small class="text-muted">
                All accounts are to be paid within 7 days from receipt of
                invoice. To be paid by cheque or credit card or direct payment
                online. If account is not paid within 7 days the credits details
                supplied as confirmation of work undertaken will be charged the
                agreed quoted fee noted above.
              </small>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="float-end">
              <p>
                <b>Sub-total:</b>
                <span class="float-end"
                  >{{ currency }}{{ invoice.sub_total | number: '2.2' }}</span
                >
              </p>
              <p>
                <b>Discount (10%):</b>
                <span class="float-end">
                  &nbsp;&nbsp;&nbsp; {{ currency
                  }}{{ invoice.discount | number: '2.2' }}</span
                >
              </p>
              <h3>{{ currency }}{{ invoice.total | number: '2.2' }} USD</h3>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>

        <div class="mt-4 mb-1">
          <div class="text-end d-print-none">
            <a
              href="javascript:window.print()"
              class="btn btn-primary waves-effect waves-light me-1"
              ><i class="mdi mdi-printer me-1"></i> Print</a
            >
            <a
              href="javascript:void(0);"
              class="btn btn-success waves-effect waves-light"
              >Submit</a
            >
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// Minton_v10.1.0/React.js/TS/src/app/(admin)/pages/invoice/page.tsx




// components
import PageBreadcrumb from "@/components/PageBreadcrumb";

// images
import logoDark from "@/assets/images/logo-dark.png";
import logoLight from "@/assets/images/logo-light.png";

// dummy data
import { invoiceData } from "../data";
import { Card, CardBody, Col, Row, Table } from "react-bootstrap";
import WindowPrintButton from "./WindowPrintButton";
import React from "react";

// invoice component
const Invoice = () => {
  return (
    <React.Fragment>
      <PageBreadcrumb
        breadCrumbItems={[
          { label: "Extra Pages", path: "/pages/invoice" },
          { label: "Invoice", path: "/pages/invoice", active: true },
        ]}
        title={"Invoice"}
      />

      <Row>
        <Col>
          <Card>
            <CardBody>
              <div className="clearfix">
                <div className="float-start">
                  <div className="auth-logo">
                    <div className="logo logo-dark">
                      <span className="logo-lg">
                        <img src={logoDark} alt="logo" height={22} width={119} />
                      </span>
                    </div>
                    <div className="logo logo-light">
                      <span className="logo-lg">
                        <img src={logoLight} alt="logo" height={22} width={119} />
                      </span>
                    </div>
                  </div>
                </div>
                <div className="float-end">
                  <h4 className="m-0 d-print-none">Invoice</h4>
                </div>
              </div>

              <Row>
                <Col md={6}>
                  <div className="mt-3">
                    <p>
                      <b>Hello, {invoiceData.customer}</b>
                    </p>
                    <p className="text-muted">{invoiceData.notes}</p>
                  </div>
                </Col>

                <Col md={4} className="offset-md-2">
                  <div className="mt-3 float-end">
                    <p>
                      <strong>Order Date : </strong>{" "}
                      <span className="float-end">
                        {" "}
                        &nbsp;&nbsp;&nbsp; {invoiceData.order_date}{" "}
                      </span>
                    </p>
                    <p>
                      <strong>Order Status : </strong>{" "}
                      <span className="float-end">
                        {" "}
                        <span className="badge bg-danger">
                          {invoiceData.order_status}
                        </span>
                      </span>
                    </p>
                    <p>
                      <strong>Order No. : </strong>
                      <span className="float-end">
                        {" "}
                        <span className="float-end">
                          {invoiceData.invoice_id}
                        </span>
                      </span>
                    </p>
                  </div>
                </Col>
              </Row>

              <Row className="mt-3">
                <Col sm={6}>
                  <h5>Billing Address</h5>
                  <address>
                    {invoiceData.address.owner}
                    <br />
                    {invoiceData.address.line_1}
                    <br />
                    {invoiceData.address.city}, {invoiceData.address.state}{" "}
                    {invoiceData.address.zip}
                    <br />
                    <abbr title="Phone">P:</abbr> {invoiceData.address.phone}
                  </address>
                </Col>
                <Col sm={6}>
                  <h5>Shipping Address</h5>
                  <address>
                    {invoiceData.address.owner}
                    <br />
                    {invoiceData.address.line_1}
                    <br />
                    {invoiceData.address.city}, {invoiceData.address.state}{" "}
                    {invoiceData.address.zip}
                    <br />
                    <abbr title="Phone">P:</abbr> {invoiceData.address.phone}
                  </address>
                </Col>
              </Row>

              <Row>
                <Col xs={12}>
                  <div className="table-responsive">
                    <Table className="mt-4 table-centered">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>Item</th>
                          <th style={{ width: "10%" }}>Hours</th>
                          <th style={{ width: "10%" }}>Hours Rate</th>
                          <th style={{ width: "10%" }} className="text-end">
                            Total
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        {(invoiceData.items || []).map((item, idx) => {
                          return (
                            <tr key={idx}>
                              <td>{idx + 1}</td>
                              <td>
                                <b>{item.name}</b> <br />
                                {item.description}
                              </td>
                              <td>{item.hours}</td>
                              <td>{item.hour_rate}</td>
                              <td className="text-end">{item.total}</td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </Table>
                  </div>
                </Col>
              </Row>

              <Row>
                <Col sm={6}>
                  <div className="clearfix pt-5">
                    <h6 className="text-muted">Notes:</h6>
                    <small className="text-muted">
                      All accounts are to be paid within 7 days from receipt of
                      invoice. To be paid by cheque or credit card or direct
                      payment online. If account is not paid within 7 days the
                      credits details supplied as confirmation of work
                      undertaken will be charged the agreed quoted fee noted
                      above.
                    </small>
                  </div>
                </Col>
                <Col sm={6}>
                  <div className="float-end">
                    <p>
                      <b>Sub-total:</b>{" "}
                      <span className="float-end">
                        ${invoiceData.sub_total}
                      </span>
                    </p>
                    <p>
                      <b>Discount (10%):</b>{" "}
                      <span className="float-end">
                        {" "}
                        &nbsp;&nbsp;&nbsp; ${invoiceData.discount}
                      </span>
                    </p>
                    <h3>${invoiceData.total} USD</h3>
                  </div>
                  <div className="clearfix"></div>
                </Col>
              </Row>

              <div className="mt-4 mb-1">
                <div className="text-end d-print-none">
                  <WindowPrintButton />
                  <button className="btn btn-success waves-effect waves-light">
                    Submit
                  </button>
                </div>
              </div>
            </CardBody>
          </Card>
        </Col>
      </Row>
    </React.Fragment>
  );
};

export default Invoice;
