// Minton_v10.1.0/React.js/TS/src/app/(admin)/charts/apex/SparkLineChart.tsx


import {ApexOptions} from "apexcharts";
// data
import {SparkLineChartData} from "./data";

import ReactApexChart from "react-apexcharts";

interface LineChartProps {
    sparkLineChartData: SparkLineChartData;
    colors: string[];
    titleText: string;
    subTitleText: string;
}

// simple line chart
const SparkLineChart = ({
                            sparkLineChartData,
                            colors,
                            titleText,
                            subTitleText,
                        }: LineChartProps) => {
    // default options
    const sparkLineChartOptions: ApexOptions = {
        chart: {
            type: "area",
            height: 160,
            sparkline: {
                enabled: true,
            },
        },
        stroke: {
            width: 2,
            curve: "straight",
        },
        fill: {
            opacity: 0.2,
        },
        yaxis: {
            min: 0,
        },
        colors: colors,
        title: {
            text: titleText,
            offsetX: 10,
            style: {
                fontSize: "22px",
            },
        },
        subtitle: {
            text: subTitleText,
            offsetX: 10,
            offsetY: 35,
            style: {
                fontSize: "13px",
            },
        },
    };

    // chart data
    const sparkLineChartSeries: SparkLineChartData[] = [sparkLineChartData];

    return (
        <>
            <ReactApexChart
                
                options={sparkLineChartOptions}
                series={sparkLineChartSeries}
                type="area"
                height={160}
            />
        </>
    );
};

export default SparkLineChart;

// Minton_v10.1.0/Angular/Minton/src/app/views/charts/apex/components/sparkline-chart/sparkline-chart.component.ts
import { Component } from '@angular/core'
import type { ChartOptions } from '@common/apexchart.model'
import { NgApexchartsModule } from 'ng-apexcharts'
import { randomizeArray } from '../../data'
import { CustomCardPortletComponent } from '@component/custom-card-portlet/custom-card-portlet.component'

@Component({
  selector: 'sparkline-chart',
  standalone: true,
  imports: [NgApexchartsModule, CustomCardPortletComponent],
  templateUrl: './sparkline-chart.component.html',
  styles: ``,
})
export class SparklineChartComponent {
  sparklineData = [
    47, 45, 54, 38, 56, 24, 65, 31, 37, 39, 62, 51, 35, 41, 35, 27, 93, 53, 61,
    27, 54, 43, 19, 46,
  ]

  spark1Chart: Partial<ChartOptions> = {
    chart: {
      type: 'area',
      height: 160,
      sparkline: {
        enabled: true,
      },
    },
    stroke: {
      width: 2,
      curve: 'straight',
    },
    fill: {
      opacity: 0.2,
    },
    series: [
      {
        name: 'Minton Sales ',
        data: randomizeArray(this.sparklineData),
      },
    ],
    yaxis: {
      min: 0,
    },
    colors: ['#3bafda'],
    title: {
      text: '$424,652',
      offsetX: 10,
      style: {
        fontSize: '22px',
      },
    },
    subtitle: {
      text: 'Total Sales',
      offsetX: 10,
      offsetY: 35,
      style: {
        fontSize: '13px',
      },
    },
  }

  spark2Chart: Partial<ChartOptions> = {
    chart: {
      type: 'area',
      height: 160,
      sparkline: {
        enabled: true,
      },
    },
    stroke: {
      width: 2,
      curve: 'straight',
    },
    fill: {
      opacity: 0.2,
    },
    series: [
      {
        name: 'Minton Expenses ',
        data: randomizeArray(this.sparklineData),
      },
    ],
    yaxis: {
      min: 0,
    },
    colors: ['#DCE6EC'],
    title: {
      text: '$235,312',
      offsetX: 10,
      style: {
        fontSize: '22px',
      },
    },
    subtitle: {
      text: 'Expenses',
      offsetX: 10,
      offsetY: 35,
      style: {
        fontSize: '13px',
      },
    },
  }

  spark3Chart: Partial<ChartOptions> = {
    chart: {
      type: 'area',
      height: 160,
      sparkline: {
        enabled: true,
      },
    },
    stroke: {
      width: 2,
      curve: 'straight',
    },
    fill: {
      opacity: 0.2,
    },
    series: [
      {
        name: 'Net Profits ',
        data: randomizeArray(this.sparklineData),
      },
    ],
    xaxis: {
      crosshairs: {
        width: 1,
      },
    },
    yaxis: {
      min: 0,
    },
    colors: ['#1abc9c'],
    title: {
      text: '$135,965',
      offsetX: 10,
      style: {
        fontSize: '22px',
      },
    },
    subtitle: {
      text: 'Profits',
      offsetX: 10,
      offsetY: 35,
      style: {
        fontSize: '13px',
      },
    },
  }
}

<custom-card-portlet
  cardTitle="Sparkline Charts"
  cardTitleClass="header-title mb-0"
>
  <div class="row">
    <div class="col-md-4">
      <div id="spark1" class="apex-charts" data-colors="#3bafda">
        <apx-chart
          [chart]="spark1Chart.chart!"
          [stroke]="spark1Chart.stroke!"
          [fill]="spark1Chart.fill!"
          [series]="spark1Chart.series!"
          [yaxis]="spark1Chart.yaxis!"
          [colors]="spark1Chart.colors!"
          [title]="spark1Chart.title!"
          [subtitle]="spark1Chart.subtitle!"
        />
      </div>
    </div>
    <div class="col-md-4">
      <div id="spark2" class="apex-charts" data-colors="#DCE6EC">
        <apx-chart
          [chart]="spark2Chart.chart!"
          [series]="spark2Chart.series!"
          [stroke]="spark2Chart.stroke!"
          [fill]="spark2Chart.fill!"
          [yaxis]="spark2Chart.yaxis!"
          [colors]="spark2Chart.colors!"
          [title]="spark2Chart.title!"
          [subtitle]="spark2Chart.subtitle!"
        />
      </div>
    </div>
    <div class="col-md-4">
      <div id="spark3" class="apex-charts" data-colors="#1abc9c">
        <apx-chart
          [chart]="spark3Chart.chart!"
          [stroke]="spark3Chart.stroke!"
          [fill]="spark3Chart.fill!"
          [series]="spark3Chart.series!"
          [xaxis]="spark3Chart.xaxis!"
          [yaxis]="spark3Chart.yaxis!"
          [colors]="spark3Chart.colors!"
          [title]="spark3Chart.title!"
          [subtitle]="spark3Chart.subtitle!"
        />
      </div>
    </div>
  </div>
</custom-card-portlet>
