// Minton_v10.1.0/Next.js/JS/src/app/(admin)/ui/tabs-accordions/page.jsx
import React from "react";
import AllTabsAndAccordions from "./AllTabsAndAccordions";

// components
import PageBreadcrumb from "@/components/PageBreadcrumb";
export const metadata = {
  title: "Tabs & Accordions"
};
const TabsAccordions = () => {
  return <>
      <PageBreadcrumb breadCrumbItems={[{
      label: "Base UI",
      path: "/ui/tabs-accordions"
    }, {
      label: "Tabs & Accordions",
      path: "/ui/tabs-accordions",
      active: true
    }]} title={"Tabs & Accordions"} />
      <AllTabsAndAccordions />
    </>;
};
export default TabsAccordions;

// Minton_v10.1.0/Angular/Minton/src/app/views/base-ui/tabs-accordions/tabs-accordions.component.ts
import { Component } from '@angular/core'
import { PageTitleComponent } from '@component/page-title.component'
import {
  NgbAccordionModule,
  NgbCollapseModule,
  NgbNavModule,
} from '@ng-bootstrap/ng-bootstrap'

@Component({
  selector: 'app-tabs-accordions',
  standalone: true,
  imports: [
    PageTitleComponent,
    NgbNavModule,
    NgbAccordionModule,
    NgbCollapseModule,
  ],
  templateUrl: './tabs-accordions.component.html',
  styles: ``,
})
export class TabsAccordionsComponent {
  breadCrumbItems = [
    { label: 'Base UI', path: '/ui/tabs-accordions' },
    { label: 'Tabs & Accordions', path: '/ui/tabs-accordions', active: true },
  ]
  isCollapsed = false
  isCollapsed2 = true
}
