// Minton_v10.1.0/Angular/Minton/src/app/views/extra-pages/pricing/pricing.component.ts
import { Component } from '@angular/core'
import { PageTitleComponent } from '@component/page-title.component'
import { pricingPlans } from '../data'
import { CommonModule } from '@angular/common'
import { currency } from '@common/constants'

@Component({
  selector: 'app-pricing',
  standalone: true,
  imports: [PageTitleComponent, CommonModule],
  templateUrl: './pricing.component.html',
  styles: ``,
})
export class PricingComponent {
  breadCrumbItems = [
    { label: 'Extras', path: '/pages/pricing' },
    { label: 'Pricing', path: '/pages/pricing', active: true },
  ]

  pricingPlans = pricingPlans
  currency = currency
}

<app-page-title title="Pricing" [breadCrumbItems]="breadCrumbItems" />

<div class="row justify-content-center">
  <div class="col-xl-12">
    <!-- Pricing Title-->
    <div class="text-center pb-2">
      <h3 class="mb-2">Our <span class="text-primary">Plans</span></h3>
      <p class="text-muted w-50 m-auto">
        We have plans and prices that fit your business perfectly. Make your
        client site a success with our products.
      </p>
    </div>

    <div class="row my-3">
      @for (plan of pricingPlans; track $index) {
        <div class="col-xl-3 col-md-6">
          <div
            class="card card-pricing"
            [ngClass]="{ 'ribbon-box': plan.isPopular }"
          >
            @if (plan.isPopular) {
              <div class="ribbon-two ribbon-two-danger">
                <span>Popular</span>
              </div>
            }
            <div class="card-body text-center">
              <p class="card-pricing-plan-name fw-bold text-uppercase">
                {{ plan.name }}
              </p>
              <span
                class="card-pricing-icon"
                [ngClass]="
                  plan.isPopular ? 'bg-danger text-white' : 'text-primary'
                "
              >
                <i [class]="plan.icon"></i>
              </span>
              <h2 class="card-pricing-price">
                {{ currency }}{{ plan.price }}
                <span>/ {{ plan.duration }}</span>
              </h2>
              <ul class="card-pricing-features">
                @for (feature of plan.features; track feature) {
                  <li>{{ feature }}</li>
                }
              </ul>
              <div class="d-grid">
                <button
                  class="btn waves-effect mt-4"
                  [ngClass]="
                    plan.isPopular ? 'btn-danger' : 'btn-primary waves-light'
                  "
                >
                  Sign Up
                </button>
              </div>
            </div>
          </div>
        </div>
      }
    </div>
  </div>
  <!-- end col-->
</div>

// Minton_v10.1.0/React.js/TS/src/app/(admin)/pages/pricing/page.tsx


// components
import PageBreadcrumb from "@/components/PageBreadcrumb";
import PricingCard from "@/components/PricingCard";

// dummy data
import { pricingPlans } from "../data";
import { Col, Row } from "react-bootstrap";


// Pricing component
const Pricing = () => {
  return (
    <>
      <PageBreadcrumb
        breadCrumbItems={[
          { label: "Extra Pages", path: "/pages/pricing" },
          { label: "Pricing", path: "/pages/pricing", active: true },
        ]}
        title={"Pricing"}
      />

      <Row className="justify-content-center">
        <Col xs={12}>
          <div className="text-center pb-2">
            <h3 className="mb-2">
              Our <span className="text-primary">Plans</span>
            </h3>
            <p className="text-muted w-50 m-auto">
              We have plans and prices that fit your business perfectly. Make
              your client site a success with our products.
            </p>
          </div>

          {/* pricing cards */}
          <PricingCard plans={pricingPlans} containerClass={"my-3"} />
        </Col>
      </Row>
    </>
  );
};

export default Pricing;
