// Minton_v10.1.0/React.js/JS/src/app/(admin)/dashboard/analytics/Statistics.jsx
import classNames from "classnames";
import { useEffect, useState } from "react";
import { Card, CardBody, OverlayTrigger, Tooltip } from "react-bootstrap";
const Statistics = ({
  title,
  stats,
  trend
}) => {
  const [updatedStats, setUpdatedStats] = useState(stats);
  useEffect(() => {
    const interval = setInterval(function () {
      const ac = Math.floor(Math.random() * 352 + 142);
      setUpdatedStats(ac);

      // var ac2 = Math.floor(Math.random() * ac + 86);
      // setStats2(ac2);
    }, 2000);
    return () => {
      clearInterval(interval);
    };
  }, []);
  return <Card>
      <CardBody>
        <OverlayTrigger placement="bottom" delay={{
        show: 250,
        hide: 100
      }} overlay={props => <Tooltip id="overlay-example" {...props}>
              More Info
            </Tooltip>}>
          <i className="fa fa-info-circle text-muted float-end"></i>
        </OverlayTrigger>
        <h4 className="m-0 font-16">{title}</h4>
        <h2 className="my-3 text-center">{updatedStats}</h2>
        <p className="text-muted m-0">
          {trend.title}: {trend.stats}
          <span className="float-end">
            <i className={classNames("mdi", {
            "mdi-arrow-down-bold text-danger": trend.direction === "down"
          }, {
            "mdi-arrow-up-bold text-success": trend.direction === "up"
          }, "me-1")}></i>
            {trend.rate}
          </span>
        </p>
      </CardBody>
    </Card>;
};
export default Statistics;

// Minton_v10.1.0/Angular/Minton/src/app/views/dashboard/analytics/components/statistics/statistics.component.ts
import { Component } from '@angular/core'
import { NgbAlertModule, NgbTooltipModule } from '@ng-bootstrap/ng-bootstrap'

@Component({
  selector: 'analytics-statistics',
  standalone: true,
  imports: [NgbTooltipModule, NgbAlertModule],
  templateUrl: './statistics.component.html',
  styles: ``,
})
export class StatisticsComponent {}

<ngb-alert type="info" class="mb-3">
  Property MN7xx is not receiving hits. Either your site is not receiving any
  sessions.
</ngb-alert>
<div class="card">
  <div class="card-body" id="tooltip-container">
    <i
      class="fa fa-info-circle text-muted float-end"
      data-bs-container="#tooltip-container"
      placement="bottom"
      ngbTooltip="More Info"
    ></i>
    <h4 class="m-0 font-16">Active Users</h4>
    <h2 class="my-3 text-center" id="active-users-count">121</h2>
    <p class="text-muted m-0">
      Since last month: 22506
      <span class="float-end"
        ><i class="mdi mdi-arrow-up-bold me-1 text-success"></i>10.25%</span
      >
    </p>
  </div>
  <!-- end card-body-->
</div>
<!--end card-->

<div class="card">
  <div class="card-body" id="tooltip-container1">
    <i
      class="fa fa-info-circle text-muted float-end"
      data-bs-container="#tooltip-container1"
      placement="bottom"
      ngbTooltip="More Info"
    ></i>
    <h4 class="m-0 font-16">Views Per Minute</h4>
    <h2 class="my-3 text-center" id="active-views-count">485</h2>
    <p class="text-muted m-0">
      Since previous week: 8541
      <span class="float-end"
        ><i class="mdi mdi-arrow-down-bold me-1 text-danger"></i>2.63%</span
      >
    </p>
  </div>
  <!-- end card-body-->
</div>
