// Minton_v10.1.0/Angular/Minton/src/app/views/dashboard/analytics/components/traffic-sources/traffic-sources.component.ts
import { Component } from '@angular/core'
import { trafficSources } from '../../data'
import { CommonModule } from '@angular/common'
import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap'

@Component({
  selector: 'analytics-traffic-sources',
  standalone: true,
  imports: [CommonModule, NgbDropdownModule],
  templateUrl: './traffic-sources.component.html',
  styles: ``,
})
export class TrafficSourcesComponent {
  trafficList = trafficSources
}

<div class="card">
  <div class="card-body">
    <div ngbDropdown class="dropdown float-end">
      <a
        ngbDropdownToggle
        class="dropdown-toggle arrow-none card-drop"
        role="button"
      >
        <i class="mdi mdi-dots-horizontal"></i>
      </a>
      <div ngbDropdownMenu class="dropdown-menu dropdown-menu-end">
        <!-- item-->
        <a href="javascript:void(0);" class="dropdown-item">Settings</a>
        <!-- item-->
        <a href="javascript:void(0);" class="dropdown-item">Download</a>
        <!-- item-->
        <a href="javascript:void(0);" class="dropdown-item">Upload</a>
        <!-- item-->
        <a href="javascript:void(0);" class="dropdown-item">Action</a>
      </div>
    </div>
    <h4 class="header-title mt-0 mb-3">Traffic Sources</h4>
    <div class="table-responsive browser_users">
      <table class="table mb-0">
        <thead class="table-light">
          <tr>
            <th class="border-top-0">Channel</th>
            <th class="border-top-0">Sessions</th>
            <th class="border-top-0">Prev.Period</th>
            <th class="border-top-0">% Change</th>
          </tr>
          <!--end tr-->
        </thead>
        <tbody>
          @for (item of trafficList; track $index) {
            <tr>
              <td>
                <a href="javascript:void(0);" class="text-primary">{{
                  item.channel
                }}</a>
              </td>
              <td>
                {{ item.sessions.value }}
                <small class="text-muted">({{ item.sessions.rate }})</small>
              </td>
              <td>
                {{ item.previewPeriod.value }}
                <small class="text-muted"
                  >({{ item.previewPeriod.rate }})</small
                >
              </td>
              <td>
                {{ item.change.value
                }}<i
                  class="fas fa-caret-{{ item.change.direction }} font-16 ms-1"
                  [ngClass]="
                    item.change.direction == 'up'
                      ? 'text-success'
                      : 'text-danger'
                  "
                ></i>
              </td>
            </tr>
            <!--end tr-->
          }
        </tbody>
      </table>
      <!--end table-->
    </div>
    <!--end /div-->
  </div>
  <!--end card-body-->
</div>
<!--end card-->

// Minton_v10.1.0/Next.js/JS/src/app/(admin)/dashboard/analytics/TrafficSources.jsx
import React from "react";
import Link from "next/link";
import classNames from "classnames";
const AnalyticDropdown = dynamic(() => import('./AnalyticDropdown'));

// types

import dynamic from "next/dynamic";
const TrafficSources = ({
  trafficSources
}) => {
  return <div className="card">
      <div className="card-body">
        <AnalyticDropdown />

        <h4 className="header-title mt-0 mb-3">Traffic Sources</h4>

        <div className="table-responsive browser_users">
          <table className="table mb-0">
            <thead className="table-light">
              <tr>
                <th className="border-top-0">Channel</th>
                <th className="border-top-0">Sessions</th>
                <th className="border-top-0">Prev.Period</th>
                <th className="border-top-0">% Change</th>
              </tr>
            </thead>
            <tbody>
              {(trafficSources || []).map((item, index) => {
              return <tr key={index}>
                    <td>
                      <Link href="" className="text-primary">
                        {item.channel}
                      </Link>
                    </td>
                    <td>
                      {item.sessions.value}{" "}
                      <small className="text-muted">
                        ({item.sessions.rate})
                      </small>
                    </td>
                    <td>
                      {item.previewPeriod.value}{" "}
                      <small className="text-muted">
                        ({item.previewPeriod.rate})
                      </small>
                    </td>
                    <td>
                      {" "}
                      {item.change.value}{" "}
                      <i className={classNames("fas", "fa-caret-" + item.change.direction, "font-16", item.change.direction === "up" ? "text-success" : "text-danger")}></i>
                    </td>
                  </tr>;
            })}
            </tbody>
          </table>
        </div>
      </div>
    </div>;
};
export default TrafficSources;
