// Minton_v10.1.0/Angular/Minton/src/app/views/ecommerce/sellers/sellers.component.ts
import { Component, inject } from '@angular/core'
import { PageTitleComponent } from '@component/page-title.component'
import { sellers } from '../data'
import { CommonModule, DecimalPipe } from '@angular/common'
import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap'
import { FormsModule } from '@angular/forms'
import { currency } from '@common/constants'

@Component({
  selector: 'app-sellers',
  standalone: true,
  imports: [
    PageTitleComponent,
    CommonModule,
    NgbDropdownModule,
    DecimalPipe,
    FormsModule,
  ],
  templateUrl: './sellers.component.html',
  styles: ``,
})
export class SellersComponent {
  currency = currency
  breadCrumbItems = [
    { label: 'eCommerce', path: '/ecommerce/products' },
    {
      label: 'Sellers',
      path: '/ecommerce/sellers',
      active: true,
    },
  ]

  sellerList = sellers
}

<app-page-title title="Sellers" [breadCrumbItems]="breadCrumbItems" />

<div class="row mb-2">
  <div class="col-sm-4">
    <a href="javascript:void(0);" class="btn btn-danger mb-2"
      ><i class="mdi mdi-plus-circle me-1"></i> Add Sellers</a
    >
  </div>
  <div class="col-sm-8">
    <div class="float-sm-end">
      <div class="d-flex flex-wrap align-items-center">
        <div class="d-flex flex-wrap align-items-center me-2">
          <label for="sellersearch-input" class="visually-hidden">Search</label>
          <input
            type="search"
            class="form-control"
            id="sellersearch-input"
            placeholder="Search..."
          />
        </div>
        <button type="button" class="btn btn-success mb-2 mb-sm-0">
          <i class="mdi mdi-cog"></i>
        </button>
      </div>
    </div>
  </div>
  <!-- end col-->
</div>

<div class="row">
  @for (item of sellerList; track $index) {
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <div class="d-flex align-items-start">
            <div class="me-3" [ngClass]="{ 'avatar-md': !item.image }">
              @if (item.image) {
                <img
                  [src]="item.image"
                  alt="user-image"
                  class="rounded avatar-md"
                />
              } @else {
                <div
                  class="avatar-title bg-light rounded text-body font-20 fw-semibold"
                >
                  {{ item.store.charAt(0) }}
                </div>
              }
            </div>
            <div class="flex-1">
              <h5 class="my-1">
                <a href="javascript:void(0);" class="text-dark">{{
                  item.store
                }}</a>
              </h5>
              <p class="text-muted mb-0">
                <i class="mdi mdi-account me-1"></i> {{ item.name }}
              </p>
            </div>
            <div ngbDropdown class="dropdown">
              <a ngbDropdownToggle class="text-body dropdown-toggle">
                <i class="mdi mdi-dots-vertical font-20"></i>
              </a>

              <div ngbDropdownMenu class="dropdown-menu dropdown-menu-end">
                <a class="dropdown-item" href="javascript:void(0);">Action</a>
                <a class="dropdown-item" href="javascript:void(0);"
                  >Another action</a
                >
                <a class="dropdown-item" href="javascript:void(0);"
                  >Something else here</a
                >
              </div>
            </div>
          </div>
          <hr />
          <div class="text-muted">
            <div class="row">
              <div class="col-sm-4 col-6">
                <div>
                  <p class="mb-0">Products</p>
                  <h5 class="mb-sm-0">{{ item.products }}</h5>
                </div>
              </div>
              <div class="col-sm-4 col-6">
                <div>
                  <p class="mb-0">Wallet Balance</p>
                  <h5 class="mb-sm-0">
                    {{ currency }}{{ item.balance | number }}
                  </h5>
                </div>
              </div>
              <div class="col-sm-4 col-6">
                <div class="mt-3 mt-sm-0">
                  <p class="mb-0">Revenue</p>
                  <h5 class="mb-0">{{ currency }}{{ item.revenue }}</h5>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  }
</div>

<div class="row">
  <div class="col-lg-12">
    <div>
      <div class="text-center my-3">
        <a href="javascript:void(0);" class="text-danger"
          ><i class="mdi mdi-spin mdi-loading font-20 align-middle me-2"></i>
          Load more
        </a>
      </div>
    </div>
  </div>
</div>

// Minton_v10.1.0/React.js/JS/src/app/(admin)/apps/ecommerce/sellers/page.jsx
import { Link } from "react-router-dom";

// dummy data
import { sellers } from "../data";
import PageBreadcrumb from "@/components/PageBreadcrumb";
import { Card, CardBody, Col, Row } from "react-bootstrap";
import SellerDropdown from "./SellerDropdown";
const SellerInfo = ({
  item
}) => {
  return <Card>
      <CardBody>
        <div className="d-flex align-items-start">
          {item.image ? <div className="me-3">
              <img src={item.image} alt="avatar" className="rounded avatar-md" height={56} width={56} />
            </div> : <div className="avatar-md me-3">
              <div className="avatar-title bg-light rounded text-body font-20 fw-semibold">
                {item.store[0]}
              </div>
            </div>}
          <div className="flex-1">
            <h5 className="my-1">
              <Link to="" className="text-dark">
                {item.store}
              </Link>
            </h5>
            <p className="text-muted mb-0">
              <i className="mdi mdi-account me-1"></i> {item.name}
            </p>
          </div>
          <SellerDropdown />
        </div>

        <hr />

        <div className="text-muted">
          <Row>
            <Col sm={4} xs={6}>
              <div>
                <p className="mb-0">Products</p>
                <h5 className="mb-sm-0">{item.products}</h5>
              </div>
            </Col>
            <Col sm={4} xs={6}>
              <div>
                <p className="mb-0">Wallet Balance</p>
                <h5 className="mb-sm-0">{item.balance}</h5>
              </div>
            </Col>
            <Col sm={4} xs={6}>
              <div className="mt-3 mt-sm-0">
                <p className="mb-0">Revenue</p>
                <h5 className="mb-0">{item.revenue}</h5>
              </div>
            </Col>
          </Row>
        </div>
      </CardBody>
    </Card>;
};
const Sellers = () => {
  return <>
      <PageBreadcrumb breadCrumbItems={[{
      label: "eCommerce",
      path: "/apps/ecommerce/sellers"
    }, {
      label: "Sellers",
      path: "/apps/ecommerce/sellers",
      active: true
    }]} title={"Sellers"} />

      <Row className="mb-2">
        <Col sm={4}>
          <Link to="" className="btn btn-danger mb-2">
            <i className="mdi mdi-plus-circle me-1"></i> Add Sellers
          </Link>
        </Col>
        <Col sm={8}>
          <div className="float-sm-end">
            <form className="d-flex flex-wrap align-items-center">
              <div className="d-flex flex-wrap align-items-center me-2">
                <label htmlFor="sellersearch-input" className="visually-hidden">
                  Search
                </label>
                <input type="search" className="form-control" id="sellersearch-input" placeholder="Search..." />
              </div>
              <button type="button" className="btn btn-success mb-2 mb-sm-0">
                <i className="mdi mdi-cog"></i>
              </button>
            </form>
          </div>
        </Col>
      </Row>

      <Row>
        {(sellers || []).map((item, index) => {
        return <Col lg={6} key={index}>
              <SellerInfo item={item} />
            </Col>;
      })}
      </Row>

      <Row>
        <Col lg={12}>
          <div>
            <div className="text-center my-3">
              <Link to="" className="text-danger">
                <i className="mdi mdi-spin mdi-loading font-20 align-middle me-2"></i>{" "}
                Load more{" "}
              </Link>
            </div>
          </div>
        </Col>
      </Row>
    </>;
};
export default Sellers;
