// Minton_v10.1.0/Angular/Minton/src/app/views/task/list/list.component.ts
import { Component } from '@angular/core'
import { PageTitleComponent } from '@component/page-title.component'
import { otherTasks, todayTasks, upcomingTasks } from './data'
import { SectionComponent } from './components/section/section.component'
import {
  NgbCollapseModule,
  NgbDropdownModule,
} from '@ng-bootstrap/ng-bootstrap'

@Component({
  selector: 'app-list',
  standalone: true,
  imports: [
    PageTitleComponent,
    SectionComponent,
    NgbDropdownModule,
    NgbCollapseModule,
  ],
  templateUrl: './list.component.html',
  styles: ``,
})
export class ListComponent {
  breadCrumbItems = [
    { label: 'Tasks', path: '/task/list' },
    { label: 'Tasks List', path: '/task/list', active: true },
  ]

  todayTasks = todayTasks
  upcomingTasks = upcomingTasks
  otherTasks = otherTasks

  isCollapsed = false
  isCollapsed1 = false
  isCollapsed2 = false
}

<app-page-title title="Tasks List" [breadCrumbItems]="breadCrumbItems" />

<div class="row">
  <div class="col-lg-12">
    <div class="row">
      <div class="col">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <a
                  href="javascript:void(0);"
                  class="btn btn-primary waves-effect waves-light"
                  ><i class="fe-plus me-1"></i>Add New</a
                >
              </div>
              <div class="col-sm-9">
                <div class="float-sm-end mt-3 mt-sm-0">
                  <div class="d-flex align-items-start flex-wrap">
                    <div class="mb-3 mb-sm-0 me-sm-2">
                      <form>
                        <div class="position-relative">
                          <input
                            type="text"
                            class="form-control"
                            placeholder="Search..."
                          />
                        </div>
                      </form>
                    </div>
                    <div ngbDropdown class="dropdown">
                      <button
                        ngbDropdownToggle
                        class="btn btn-light dropdown-toggle"
                        type="button"
                      >
                        <i class="mdi mdi-filter-variant"></i>
                      </button>
                      <div
                        ngbDropdownMenu
                        class="dropdown-menu dropdown-menu-end"
                      >
                        <a class="dropdown-item" href="javascript:void(0);"
                          >Due Date</a
                        >
                        <a class="dropdown-item" href="javascript:void(0);"
                          >Added Date</a
                        >
                        <a class="dropdown-item" href="javascript:void(0);"
                          >Assignee</a
                        >
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="custom-accordion">
              <div class="mt-4">
                <h5 class="position-relative mb-0">
                  <a
                    class="text-dark d-block"
                    data-bs-toggle="collapse"
                    (click)="collapse.toggle()"
                    >Today Tasks <span class="text-muted">(08)</span>
                    <i class="mdi mdi-chevron-down accordion-arrow"></i
                  ></a>
                </h5>
                <div
                  #collapse="ngbCollapse"
                  [(ngbCollapse)]="isCollapsed"
                  class="collapse show"
                  id="taskcollapse1"
                >
                  <task-section [task]="todayTasks" />
                </div>
              </div>

              <div class="mt-4">
                <h5 class="position-relative mb-0">
                  <a
                    class="text-dark d-block"
                    data-bs-toggle="collapse"
                    (click)="collapse1.toggle()"
                    >Upcoming Tasks <span class="text-muted">(05)</span>
                    <i class="mdi mdi-chevron-down accordion-arrow"></i
                  ></a>
                </h5>
                <div
                  #collapse1="ngbCollapse"
                  [(ngbCollapse)]="isCollapsed1"
                  class="collapse show"
                  id="taskcollapse2"
                >
                  <task-section [task]="upcomingTasks" />
                </div>
              </div>

              <div class="mt-4">
                <h5 class="position-relative mb-0">
                  <a
                    class="text-dark d-block"
                    data-bs-toggle="collapse"
                    (click)="collapse2.toggle()"
                    >Other Tasks <span class="text-muted">(03)</span>
                    <i class="mdi mdi-chevron-down accordion-arrow"></i
                  ></a>
                </h5>
                <div
                  #collapse2="ngbCollapse"
                  [(ngbCollapse)]="isCollapsed2"
                  class="collapse show"
                  id="taskcollapse3"
                >
                  <task-section [task]="otherTasks" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// Minton_v10.1.0/Next.js/TS/src/app/(admin)/apps/tasks/list/page.tsx
import Link from "next/link";
import dynamic from "next/dynamic";
const TaskDropdown = dynamic(() => import('./TaskDropdown'))
const AllTask = dynamic(() => import('./AllTask'))
import PageBreadcrumb from "@/components/PageBreadcrumb";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tasks List",
}

// Task List
const TaskList = () => {

  return (
    <>
      <PageBreadcrumb
        breadCrumbItems={[
          { label: "Tasks", path: "/apps/tasks/list" },
          { label: "Tasks List", path: "/apps/tasks/list", active: true },
        ]}
        title={"Tasks List"}
      />
      <div className="row">
        <div className="col-lg-12">
          <div className="row">
            <div className="col">
              <div className="card">
                <div className="card-body">
                  {/* cta */}
                  <div className="row">
                    <div className="col-sm-3">
                      <Link
                        href=""
                        className="btn btn-primary waves-effect waves-light"
                      >
                        <i className="fe-plus me-1"></i>Add New
                      </Link>
                    </div>
                    <div className="col-sm-9">
                      <div className="float-sm-end mt-3 mt-sm-0">
                        <div className="d-flex align-items-start flex-wrap">
                          <div className="mb-3 mb-sm-0 me-sm-2">
                            <form>
                              <div className="position-relative">
                                <input
                                  type="text"
                                  className="form-control"
                                  placeholder="Search..."
                                />
                              </div>
                            </form>
                          </div>
                          <TaskDropdown />
                        </div>
                      </div>
                    </div>
                  </div>
                  <AllTask />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default TaskList;
