// Minton_v10.1.0/Angular/Minton/src/app/views/apps/widgets/components/statistics-chart-widget7/statistics-chart-widget7.component.ts
import { Component } from '@angular/core'
import type { ChartOptions } from '@common/apexchart.model'
import { currency } from '@common/constants'
import { NgApexchartsModule } from 'ng-apexcharts'

@Component({
  selector: 'statistics-chart-widget7',
  standalone: true,
  imports: [NgApexchartsModule],
  templateUrl: './statistics-chart-widget7.component.html',
  styles: ``,
})
export class StatisticsChartWidget7Component {
  currency = currency
  sparkline7Chart: Partial<ChartOptions> = {
    chart: {
      type: 'line',
      height: 165,
      toolbar: {
        show: false,
      },
      sparkline: {
        enabled: true,
      },
    },
    series: [
      {
        type: 'bar',
        data: [3, 6, 7, 8, 6, 4, 7, 10, 12, 7, 4, 9, 12, 13, 11, 12],
      },
      {
        type: 'line',
        data: [3, 6, 7, 8, 6, 4, 7, 10, 12, 7, 4, 9, 12, 13, 11, 12],
      },
    ],
    plotOptions: {
      bar: {
        columnWidth: '65%',
      },
    },
    grid: {
      show: false,
      padding: {
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
      },
    },
    xaxis: {
      labels: {
        show: false,
      },
      axisTicks: {
        show: false,
      },
    },
    yaxis: {
      labels: {
        show: false,
      },
    },
    legend: {
      show: false,
    },
    stroke: {
      width: [1.5],
      curve: 'straight',
    },
    colors: ['#1abc9c', '#f1556c'],
    tooltip: {
      fixed: {
        enabled: false,
      },
      x: {
        show: false,
      },
      y: {
        title: {
          formatter: (seriesName: string) => {
            return ''
          },
        },
      },
      marker: {
        show: false,
      },
    },
  }
}

<div class="card">
  <div class="card-body">
    <h4 class="header-title mb-3">Recent Users</h4>

    <div class="widget-chart text-center">
      <div id="sparkline6" data-colors="#f1556c,#1abc9c" class="text-center">
        <apx-chart
          [chart]="sparkline7Chart.chart!"
          [series]="sparkline7Chart.series!"
          [plotOptions]="sparkline7Chart.plotOptions!"
          [grid]="sparkline7Chart.grid!"
          [xaxis]="sparkline7Chart.xaxis!"
          [yaxis]="sparkline7Chart.yaxis!"
          [legend]="sparkline7Chart.legend!"
          [stroke]="sparkline7Chart.stroke!"
          [colors]="sparkline7Chart.colors!"
          [tooltip]="sparkline7Chart.tooltip!"
        />
      </div>
      <div class="row mt-3">
        <div class="col-4">
          <p class="text-muted font-15 mb-1 text-truncate">Target</p>
          <h4>{{ currency }}1022</h4>
        </div>
        <div class="col-4">
          <p class="text-muted font-15 mb-1 text-truncate">Last week</p>
          <h4>{{ currency }}538</h4>
        </div>
        <div class="col-4">
          <p class="text-muted font-15 mb-1 text-truncate">Last Month</p>
          <h4>{{ currency }}988</h4>
        </div>
      </div>
    </div>
  </div>
</div>

// Minton_v10.1.0/Next.js/TS/src/app/(admin)/widgets/StatisticsChartWidget7.tsx
"use client"
import React from "react";
import ReactApexChart from "react-apexcharts";
import { ApexOptions } from "apexcharts";

// components
import { ChartStatistics } from "@/components";

const StatisticsChartWidget7 = () => {
  const apexOpts: ApexOptions = {
    chart: {
      type: "line",
      toolbar: {
        show: false,
      },
      sparkline: {
        enabled: true,
      },
    },
    plotOptions: {
      bar: {
        columnWidth: "65%",
      },
    },
    grid: {
      show: false,
      padding: {
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
      },
    },
    xaxis: {
      labels: {
        show: false,
      },
      axisTicks: {
        show: false,
      },
    },
    yaxis: {
      labels: {
        show: false,
      },
    },
    legend: {
      show: false,
    },
    stroke: {
      width: [1.5],
      curve: "straight",
    },
    colors: ["#1abc9c", "#f1556c"],
    tooltip: {
      fixed: {
        enabled: false,
      },
      x: {
        show: false,
      },
      y: {
        title: {
          formatter: (seriesName: string) => {
            return "";
          },
        },
      },
      marker: {
        show: false,
      },
    },
  };

  const apexData = [
    {
      type: "bar",
      data: [3, 6, 7, 8, 6, 4, 7, 10, 12, 7, 4, 9, 12, 13, 11, 12],
    },
    {
      type: "line",
      data: [3, 6, 7, 8, 6, 4, 7, 10, 12, 7, 4, 9, 12, 13, 11, 12],
    },
  ];

  return (
    <div className="card">
      <div className="card-body">
        <h4 className="header-title mb-3">Recent Users</h4>

        <div className="widget-chart text-center">
          <ReactApexChart
            options={apexOpts}
            series={apexData}
            type="line"
            height={165}
            width={215}
            className="apex-charts mt-0"
          />
          <div className="row mt-3">
            <div className="col-4">
              <ChartStatistics title="Target" stats="$1022" />
            </div>
            <div className="col-4">
              <ChartStatistics title="Last week" stats="$538" />
            </div>
            <div className="col-4">
              <ChartStatistics title="Last Month" stats="$988" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default StatisticsChartWidget7;
