// Minton_v10.1.0/Angular/Minton/src/app/views/dashboard/crm/components/performance-details/performance-details.component.ts
import { Component } from '@angular/core'
import { performanceDetails } from '../../data'
import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap'

@Component({
  selector: 'crm-performance-details',
  standalone: true,
  imports: [NgbDropdownModule],
  templateUrl: './performance-details.component.html',
  styles: ``,
})
export class PerformanceDetailsComponent {
  performanceList = performanceDetails
}

<div class="card">
  <div class="card-body">
    <div ngbDropdown class="dropdown float-end">
      <a
        ngbDropdownToggle
        class="dropdown-toggle arrow-none card-drop"
        role="button"
      >
        <i class="mdi mdi-dots-vertical"></i>
      </a>
      <div ngbDropdownMenu class="dropdown-menu dropdown-menu-end">
        <!-- item-->
        <a href="javascript:void(0);" class="dropdown-item">Settings</a>
        <!-- item-->
        <a href="javascript:void(0);" class="dropdown-item">Action</a>
      </div>
    </div>
    <h4 class="header-title mb-3">Top Performing</h4>

    <div class="table-responsive">
      <table class="table table-striped table-nowrap table-centered mb-0">
        <thead>
          <tr>
            <th>User</th>
            <th>Leads</th>
            <th>Deals</th>
            <th>Tasks</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          @for (item of performanceList; track $index) {
            <tr>
              <td>
                <h5 class="font-14 mt-0 mb-1 fw-normal">{{ item.user }}</h5>
                <span class="text-muted font-13">{{ item.position }}</span>
              </td>
              <td>{{ item.leads }}</td>
              <td>{{ item.deals }}</td>
              <td>{{ item.tasks }}</td>
              <td class="table-action">
                <a href="javascript: void(0);" class="action-icon">
                  <i class="mdi mdi-eye"></i
                ></a>
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
    <!-- end table-responsive-->
  </div>
  <!-- end card-body-->
</div>
<!-- end card-->

// Minton_v10.1.0/Next.js/TS/src/app/(admin)/dashboard/crm/PerformanceDetails.tsx
"use client"
import React from "react";
import { Card, Dropdown, Table } from "react-bootstrap";
import Link from "next/link";

interface PerformanceDetailsProps {
  performanceDetails: {
    id: number;
    user: string;
    position: string;
    leads: number;
    deals: number;
    tasks: number;
  }[];
}

const PerformanceDetails = ({
  performanceDetails,
}: PerformanceDetailsProps) => {
  return (
    <>
      <div className="card">
        <div className="card-body">
          <Dropdown className="float-end" align="end">
            <Dropdown.Toggle as="a" className="arrow-none card-drop">
              <i className="mdi mdi-dots-vertical"></i>
            </Dropdown.Toggle>
            <Dropdown.Menu>
              <Dropdown.Item>Settings</Dropdown.Item>
              <Dropdown.Item>Action</Dropdown.Item>
            </Dropdown.Menu>
          </Dropdown>

          <h4 className="header-title mb-3">Top Performing</h4>

          <div className="table-responsive">
            <Table className="table table-striped table-nowrap table-centered mb-0">
              <thead>
                <tr>
                  <th>User</th>
                  <th>Leads</th>
                  <th>Deals</th>
                  <th>Tasks</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {(performanceDetails || []).map((item, index) => {
                  return (
                    <tr key={index}>
                      <td>
                        <h5 className="font-14 mt-0 mb-1 fw-normal">
                          {item.user}
                        </h5>
                        <span className="text-muted font-13">
                          {item.position}
                        </span>
                      </td>
                      <td>{item.leads}</td>
                      <td>{item.deals}</td>
                      <td>{item.tasks}</td>
                      <td className="table-action">
                        <Link href="" className="action-icon">
                          {" "}
                          <i className="mdi mdi-eye"></i>
                        </Link>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </Table>
          </div>
        </div>
      </div>
    </>
  );
};

export default PerformanceDetails;
