// Minton_v10.1.0/Angular/Minton/src/app/views/base-ui/images/images.component.ts
import { Component } from '@angular/core'
import { PageTitleComponent } from '@component/page-title.component'

@Component({
  selector: 'app-images',
  standalone: true,
  imports: [PageTitleComponent],
  templateUrl: './images.component.html',
  styles: ``,
})
export class ImagesComponent {
  breadCrumbItems = [
    { label: 'Base UI', path: '/ui/images' },
    { label: 'Images', path: '/ui/images', active: true },
  ]
}

<app-page-title title="Images" [breadCrumbItems]="breadCrumbItems" />

<div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-xl-6">
            <h4 class="header-title">Images shapes</h4>
            <p class="sub-header mb-0">
              Add classes to an <code>&lt;img&gt;</code> element to easily style
              images in any project.
            </p>

            <div class="row">
              <div class="col-sm-4">
                <div class="mt-3">
                  <img
                    src="assets/images/small/img-1.jpg"
                    alt="image"
                    class="img-fluid rounded"
                    width="200"
                  />
                  <p class="mb-0">
                    <code>.rounded</code>
                  </p>
                </div>
              </div>

              <div class="col-sm-4 text-center">
                <div class="mt-3">
                  <img
                    src="assets/images/users/avatar-6.jpg"
                    alt="image"
                    class="img-fluid rounded-circle"
                    width="120"
                  />
                  <p class="mb-0">
                    <code>.rounded-circle</code>
                  </p>
                </div>
              </div>

              <div class="col-sm-4">
                <div class="mt-3">
                  <img
                    src="assets/images/small/img-3.jpg"
                    alt="image"
                    class="img-fluid img-thumbnail"
                    width="200"
                  />
                  <p class="mb-0">
                    <code>.img-thumbnail</code>
                  </p>
                </div>
              </div>
            </div>
          </div>
          <!-- end col-->

          <div class="col-xl-6 mt-3 mt-xl-0">
            <h4 class="header-title">Image sizes</h4>
            <p class="sub-header mb-0">
              Add classes to an <code>&lt;img&gt;</code> element to easily style
              images in any project.
            </p>

            <div class="row">
              <div class="col-sm-3">
                <div class="mt-3">
                  <img
                    src="assets/images/users/avatar-2.jpg"
                    alt="image"
                    class="img-fluid avatar-xs rounded"
                  />
                  <p class="mb-0">
                    <code>.avatar-xs</code>
                  </p>
                  <img
                    src="assets/images/users/avatar-2.jpg"
                    alt="image"
                    class="img-fluid avatar-sm rounded mt-2"
                  />
                  <p class="mb-0">
                    <code>.avatar-sm</code>
                  </p>
                </div>
              </div>

              <div class="col-sm-3">
                <div class="mt-3">
                  <img
                    src="assets/images/users/avatar-2.jpg"
                    alt="image"
                    class="img-fluid avatar-md rounded"
                  />
                  <p class="mb-0">
                    <code>.avatar-md</code>
                  </p>
                </div>
              </div>

              <div class="col-sm-3">
                <div class="mt-3">
                  <img
                    src="assets/images/users/avatar-2.jpg"
                    alt="image"
                    class="img-fluid avatar-lg rounded"
                  />
                  <p class="mb-0">
                    <code>.avatar-lg</code>
                  </p>
                </div>
              </div>

              <div class="col-sm-3">
                <div class="mt-3">
                  <img
                    src="assets/images/users/avatar-2.jpg"
                    alt="image"
                    class="img-fluid avatar-xl rounded"
                  />
                  <p class="mb-0">
                    <code>.avatar-xl</code>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- end row-->

<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <h4 class="header-title">Border-radius</h4>
        <p class="sub-header mb-0">
          Add classes to an element to easily round its corners.
        </p>

        <div class="row">
          <div class="col-md col-sm-6">
            <div class="mt-3">
              <img
                src="assets/images/users/avatar-3.jpg"
                alt="image"
                class="img-fluid avatar-md rounded"
              />
              <p class="mb-0">
                <code>.rounded</code>
              </p>
            </div>
          </div>
          <div class="col-md col-sm-6">
            <div class="mt-3">
              <img
                src="assets/images/users/avatar-3.jpg"
                alt="image"
                class="img-fluid avatar-md rounded-top"
              />
              <p class="mb-0">
                <code>.rounded-top</code>
              </p>
            </div>
          </div>
          <div class="col-md col-sm-6">
            <div class="mt-3">
              <img
                src="assets/images/users/avatar-3.jpg"
                alt="image"
                class="img-fluid avatar-md rounded-end"
              />
              <p class="mb-0">
                <code>.rounded-end</code>
              </p>
            </div>
          </div>

          <div class="col-md col-sm-6">
            <div class="mt-3">
              <img
                src="assets/images/users/avatar-3.jpg"
                alt="image"
                class="img-fluid avatar-md rounded-bottom"
              />
              <p class="mb-0">
                <code>.rounded-bottom</code>
              </p>
            </div>
          </div>

          <div class="col-md col-sm-6">
            <div class="mt-3">
              <img
                src="assets/images/users/avatar-3.jpg"
                alt="image"
                class="img-fluid avatar-md rounded-start"
              />
              <p class="mb-0">
                <code>.rounded-start</code>
              </p>
            </div>
          </div>
          <div class="col-md col-sm-6">
            <div class="mt-3">
              <img
                src="assets/images/users/avatar-3.jpg"
                alt="image"
                class="img-fluid avatar-md rounded-circle"
              />
              <p class="mb-0">
                <code>.rounded-circle</code>
              </p>
            </div>
          </div>
        </div>
        <!-- end row-->
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <h4 class="header-title">Sizes</h4>
        <p class="sub-header mb-0">
          Use the scaling classes for larger or smaller rounded corners
        </p>

        <div class="row">
          <div class="col-md col-sm-6">
            <div class="mt-3">
              <img
                src="assets/images/users/avatar-2.jpg"
                alt="image"
                class="img-fluid avatar-md rounded-0"
              />
              <p class="mb-0">
                <code>.rounded-0</code>
              </p>
            </div>
          </div>
          <div class="col-md col-sm-6">
            <div class="mt-3">
              <img
                src="assets/images/users/avatar-2.jpg"
                alt="image"
                class="img-fluid avatar-md rounded-1"
              />
              <p class="mb-0">
                <code>.rounded-1</code>
              </p>
            </div>
          </div>
          <div class="col-md col-sm-6">
            <div class="mt-3">
              <img
                src="assets/images/users/avatar-2.jpg"
                alt="image"
                class="img-fluid avatar-md rounded-2"
              />
              <p class="mb-0">
                <code>.rounded-2</code>
              </p>
            </div>
          </div>

          <div class="col-md col-sm-6">
            <div class="mt-3">
              <img
                src="assets/images/users/avatar-2.jpg"
                alt="image"
                class="img-fluid avatar-md rounded-3"
              />
              <p class="mb-0">
                <code>.rounded-3</code>
              </p>
            </div>
          </div>
        </div>
        <!-- end row-->
      </div>
    </div>
  </div>
</div>

// Minton_v10.1.0/Next.js/TS/src/app/(admin)/ui/images/page.tsx
import React from "react";
import Image from "next/image";
import classNames from "classnames";

export const metadata: Metadata = {
  title: "Images"
}

// components
import PageBreadcrumb  from "@/components/PageBreadcrumb";

// images
import avatar2 from "@/assets/images/users/avatar-2.jpg";
import avatar3 from "@/assets/images/users/avatar-3.jpg";
import avatar6 from "@/assets/images/users/avatar-6.jpg";

import img1 from "@/assets/images/small/img-1.jpg";
import img2 from "@/assets/images/small/img-3.jpg";
import { Metadata } from "next";

const ImageShapes = () => {
  return (
    <>
      <h4 className="header-title">Images shapes</h4>
      <p className="sub-header mb-0">
        Add classes to an <code>&lt;img /&gt;</code> element to easily style
        images in any project.
      </p>

      <div className="row">
        <div className="col-sm-4">
          <div className="mt-3">
            <Image src={img1} alt="" className="img-fluid rounded" width={200} height={133} />
            <p className="mb-0">
              <code>.rounded</code>
            </p>
          </div>
        </div>

        <div className="col-sm-4 text-center">
          <div className="mt-3">
            <Image
              src={avatar6}
              alt=""
              className="img-fluid rounded-circle"
              width={120}
              height={120}
            />
            <p className="mb-0">
              <code>.rounded-circle</code>
            </p>
          </div>
        </div>

        <div className="col-sm-4">
          <div className="mt-3">
            <Image
              src={img2}
              alt=""
              className="img-fluid img-thumbnail"
              width="200"
              height={136}
            />
            <p className="mb-0">
              <code>.img-thumbnail</code>
            </p>
          </div>
        </div>
      </div>
    </>
  );
};

const ImageSizes = () => {
  return (
    <>
      <h4 className="header-title">Image sizes</h4>
      <p className="sub-header mb-0">
        Add classes to an <code>&lt;img /&gt;</code> element to easily style
        images in any project.
      </p>

      <div className="row">
        <div className="col-md-3">
          <div className="mt-3">
            <Image src={avatar2} alt="" className="img-fluid avatar-xs rounded" height={24} width={24} />
            <p className="mb-0">
              <code>.avatar-xs</code>
            </p>
            <Image
              src={avatar2}
              alt=""
              className="img-fluid avatar-sm rounded mt-2"
              height={36}
              width={36}
            />
            <p className="mb-0">
              <code>.avatar-sm</code>
            </p>
          </div>
        </div>

        <div className="col-md-3">
          <div className="mt-3">
            <Image src={avatar2} alt="" className="img-fluid avatar-md rounded" height={56} width={56} />
            <p className="mb-0">
              <code>.avatar-md</code>
            </p>
          </div>
        </div>

        <div className="col-md-3">
          <div className="mt-3">
            <Image src={avatar2} alt="" className="img-fluid avatar-lg rounded" height={72} width={72} />
            <p className="mb-0">
              <code>.avatar-lg</code>
            </p>
          </div>
        </div>

        <div className="col-md-3">
          <div className="mt-3">
            <Image src={avatar2} alt="" className="img-fluid avatar-xl rounded" height={96} width={96} />
            <p className="mb-0">
              <code>.avatar-xl</code>
            </p>
          </div>
        </div>
      </div>
    </>
  );
};

const ImagesWithBorderRadius = () => {
  const variant = ["top", "end", "bottom", "start", "circle"];

  return (
    <>
      <h4 className="header-title">Border-radius</h4>
      <p className="sub-header mb-0">
        Add classes to an element to easily round its corners.
      </p>

      <div className="row">
        <div className="col-md col-sm-6">
          <div className="mt-3">
            <Image src={avatar3} alt="" className="img-fluid avatar-md rounded" height={56} width={56} />
            <p className="mb-0">
              <code>.rounded</code>
            </p>
          </div>
        </div>
        {(variant || []).map((variant, index) => {
          return (
            <div className="col-md col-sm-6" key={index}>
              <div className="mt-3">
                <Image
                  src={avatar3}
                  alt=""
                  className={classNames(
                    "img-fluid",
                    "avatar-md",
                    "rounded-" + variant
                  )}
                  height={56}
                  width={56}
                />
                <p className="mb-0">
                  <code>.{"rounded-" + variant}</code>
                </p>
              </div>
            </div>
          )
        })}
      </div>
    </>
  );
};

const ImageCustomSizes = () => {
  const sizes = ["0", "1", "2", "3"];

  return (
    <>
      <h4 className="header-title">Sizes</h4>
      <p className="sub-header mb-0">
        Use the scaling classes for larger or smaller rounded corners
      </p>

      <div className="row">
        {(sizes || []).map((size, index) => {
          return (
            <div className="col-md col-sm-6" key={index}>
              <div className="mt-3">
                <Image
                  src={avatar2}
                  alt=""
                  className={classNames(
                    "img-fluid",
                    "avatar-md",
                    "rounded-" + size
                  )}
                  height={56}
                  width={56}
                />
                <p className="mb-0">
                  <code>.{"rounded-" + size}</code>
                </p>
              </div>
            </div>
          );
        })}
        .
      </div>
    </>
  );
};

const Images = () => {
  return (
    <>
      <PageBreadcrumb
        breadCrumbItems={[
          { label: "Base UI", path: "/ui/images" },
          { label: "Images", path: "/ui/images", active: true },
        ]}
        title={"Images"}
      />

      <div className="row">
        <div className="col-sm-12">
          <div className="card">
            <div className="card-body">
              <div className="row">
                <div className="col-xl-6">
                  <ImageShapes />
                </div>
                <div className="col-xl-6 mt-3 mt-xl-0">
                  <ImageSizes />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="row">
        <div className="col-lg-12">
          <div className="card">
            <div className="card-body">
              <ImagesWithBorderRadius />
            </div>
          </div>
        </div>
      </div>

      <div className="row">
        <div className="col-lg-12">
          <div className="card">
            <div className="card-body">
              <ImageCustomSizes />
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Images;
