// Minton_v10.1.0/Angular/Minton/src/app/views/auth/register/register.component.ts
import { Component } from '@angular/core'
import { RouterModule } from '@angular/router'

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './register.component.html',
  styles: ``,
})
export class RegisterComponent {}

<div class="card">
  <div class="card-body p-4">
    <div class="text-center w-75 m-auto">
      <div class="auth-logo">
        <a routerLink="/" class="logo logo-dark text-center">
          <span class="logo-lg">
            <img src="assets/images/logo-dark.png" alt="" height="22" />
          </span>
        </a>

        <a routerLink="/" class="logo logo-light text-center">
          <span class="logo-lg">
            <img src="assets/images/logo-light.png" alt="" height="22" />
          </span>
        </a>
      </div>
      <p class="text-muted mb-4 mt-3">
        Don't have an account? Create your own account, it takes less than a
        minute
      </p>
    </div>

    <form action="#">
      <div class="mb-2">
        <label for="fullname" class="form-label">Full Name</label>
        <input
          class="form-control"
          type="text"
          id="fullname"
          placeholder="Enter your name"
          required
        />
      </div>
      <div class="mb-2">
        <label for="emailaddress" class="form-label">Email address</label>
        <input
          class="form-control"
          type="email"
          id="emailaddress"
          required
          placeholder="Enter your email"
        />
      </div>
      <div class="mb-2">
        <label for="password" class="form-label">Password</label>
        <div class="input-group input-group-merge">
          <input
            type="password"
            id="password"
            class="form-control"
            placeholder="Enter your password"
          />

          <div class="input-group-text" data-password="false">
            <span class="password-eye"></span>
          </div>
        </div>
      </div>
      <div class="mb-3">
        <div class="form-check">
          <input
            class="form-check-input"
            type="checkbox"
            id="checkbox-signup"
          />
          <label class="form-check-label" for="checkbox-signup">
            I accept
            <a href="javascript: void(0);" class="text-dark"
              >Terms and Conditions</a
            >
          </label>
        </div>
      </div>
      <div class="d-grid text-center">
        <button class="btn btn-primary" type="submit">Sign Up</button>
      </div>
    </form>

    <div class="text-center">
      <h5 class="mt-3 text-muted">Sign Up using</h5>
      <ul class="social-list list-inline mt-3 mb-0">
        <li class="list-inline-item">
          <a
            href="javascript: void(0);"
            class="social-list-item border-purple text-purple"
            ><i class="mdi mdi-facebook"></i
          ></a>
        </li>
        <li class="list-inline-item">
          <a
            href="javascript: void(0);"
            class="social-list-item border-danger text-danger"
            ><i class="mdi mdi-google"></i
          ></a>
        </li>
        <li class="list-inline-item">
          <a
            href="javascript: void(0);"
            class="social-list-item border-info text-info"
            ><i class="mdi mdi-twitter"></i
          ></a>
        </li>
        <li class="list-inline-item">
          <a
            href="javascript: void(0);"
            class="social-list-item border-secondary text-secondary"
            ><i class="mdi mdi-github"></i
          ></a>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="row mt-3">
  <div class="col-12 text-center">
    <p class="text-muted">
      Already have account?
      <a routerLink="/auth/login" class="text-primary fw--medium ms-1"
        >Sign In</a
      >
    </p>
  </div>
</div>

// Minton_v10.1.0/React.js/JS/src/app/(auth)/auth/register/page.jsx
;
import { yupResolver } from "@hookform/resolvers/yup";
import { Button, Col, Row } from "react-bootstrap";
import * as yup from "yup";
import { AuthLayout, SocialLinks } from "@/components";
import { FormInput } from "@/components/Form";
import { useForm } from "react-hook-form";
import { Link } from "react-router-dom";

/* bottom links */
const BottomLink = () => {
  return <Row className="mt-3">
            <Col xs={12} className="text-center">
                <p className="text-muted">
                    Already have account?{" "}
                    <Link to={"/auth/login"} className="text-primary fw--medium ms-1">
                        Sign In
                    </Link>
                </p>
            </Col>
        </Row>;
};
const Register = () => {
  const signUpFormSchema = yup.object({
    email: yup.string().email("Please enter a valid email").required("Please enter your email"),
    password: yup.string().required("Please enter your password"),
    confirmPassword: yup.string().oneOf([yup.ref("password")], "Password and confirm password doesn't match")
  });
  const {
    control,
    handleSubmit
  } = useForm({
    resolver: yupResolver(signUpFormSchema)
  });
  return <>
            <AuthLayout helpText={"Don't have an account? Create your own account, it takes less than a minute"} bottomLinks={<BottomLink />}>

                <form onSubmit={handleSubmit(() => {})}>
                    <FormInput label='Full Name' type="text" name="fullname" placeholder='Enter your name' containerClass={"mb-2"} control={control} />
                    <FormInput label='Email address' type="email" name="email" placeholder='Enter your email' containerClass={"mb-2"} control={control} />
                    <FormInput label='Password' type="password" name="password" placeholder='Enter your password' containerClass={"mb-2"} control={control} />
                    <FormInput label='I accept Terms and Conditions' type="checkbox" name="checkboxsignup" containerClass={"mb-3"} control={control} />

                    <div className="text-center d-grid">
                        <Button type="submit">
                            Sign Up
                        </Button>
                    </div>
                </form>

                <div className="text-center">
                    <h5 className="mt-3 text-muted">Sign Up using</h5>
                    <SocialLinks />
                </div>
            </AuthLayout>
        </>;
};
export default Register;
