// Minton_v10.1.0/React.js/JS/src/app/(admin)/widgets/StatisticsChartWidget3.jsx
import ReactApexChart from "react-apexcharts";
// components
import { ChartStatistics } from "@/components";
import { Card, CardBody, Col, Row } from "react-bootstrap";
const StatisticsChartWidget3 = () => {
  const apexOpts = {
    chart: {
      sparkline: {
        enabled: true
      }
    },
    plotOptions: {
      bar: {
        columnWidth: "65%"
      }
    },
    xaxis: {
      crosshairs: {
        width: 1
      }
    },
    stroke: {
      width: 0,
      curve: "smooth"
    },
    colors: ["#3bafda"],
    tooltip: {
      fixed: {
        enabled: false
      },
      x: {
        show: false
      },
      y: {
        title: {
          formatter: () => {
            return "";
          }
        }
      },
      marker: {
        show: false
      }
    }
  };
  const apexData = [{
    data: [3, 6, 7, 8, 6, 4, 7, 10, 12, 7, 4, 9, 12, 13, 11, 12]
  }];
  return <Card>
      <CardBody>
        <h4 className="header-title mb-3">Sales Status</h4>

        <div className="widget-chart text-center">
          <ReactApexChart options={apexOpts} series={apexData} type="bar" height={165} width={250} className="apex-charts mt-0" />
          <Row className="mt-3">
            <Col xs={4}>
              <ChartStatistics title="Target" stats="$825" />
            </Col>
            <Col xs={4}>
              <ChartStatistics title="Last week" stats="$423" />
            </Col>
            <Col xs={4}>
              <ChartStatistics title="Last Month" stats="$806" />
            </Col>
          </Row>
        </div>
      </CardBody>
    </Card>;
};
export default StatisticsChartWidget3;

// Minton_v10.1.0/Angular/Minton/src/app/views/apps/widgets/components/statistics-chart-widget3/statistics-chart-widget3.component.ts
import { Component } from '@angular/core'
import type { ChartOptions } from '@common/apexchart.model'
import { currency } from '@common/constants'
import { NgApexchartsModule } from 'ng-apexcharts'

@Component({
  selector: 'statistics-chart-widget3',
  standalone: true,
  imports: [NgApexchartsModule],
  templateUrl: './statistics-chart-widget3.component.html',
  styles: ``,
})
export class StatisticsChartWidget3Component {
  currency = currency

  sparkline2Chart: Partial<ChartOptions> = {
    chart: {
      type: 'bar',
      sparkline: {
        enabled: true,
      },
      height: 165,
    },
    series: [
      {
        data: [3, 6, 7, 8, 6, 4, 7, 10, 12, 7, 4, 9, 12, 13, 11, 12],
      },
    ],
    plotOptions: {
      bar: {
        columnWidth: '65%',
      },
    },
    xaxis: {
      crosshairs: {
        width: 1,
      },
    },
    stroke: {
      width: 0,
      curve: 'smooth',
    },
    colors: ['#3bafda'],
    tooltip: {
      fixed: {
        enabled: false,
      },
      x: {
        show: false,
      },
      y: {
        title: {
          formatter: (seriesName: string) => {
            return ''
          },
        },
      },
      marker: {
        show: false,
      },
    },
  }
}

<div class="card">
  <div class="card-body">
    <h4 class="header-title mb-3">Sales Status</h4>

    <div class="widget-chart text-center">
      <div id="sparkline2" data-colors="#3bafda" class="text-center">
        <apx-chart
          [chart]="sparkline2Chart.chart!"
          [series]="sparkline2Chart.series!"
          [plotOptions]="sparkline2Chart.plotOptions!"
          [xaxis]="sparkline2Chart.xaxis!"
          [stroke]="sparkline2Chart.stroke!"
          [colors]="sparkline2Chart.colors!"
          [tooltip]="sparkline2Chart.tooltip!"
        />
      </div>
      <div class="row mt-3">
        <div class="col-4">
          <p class="text-muted font-15 mb-1 text-truncate">Target</p>
          <h4>{{ currency }}825</h4>
        </div>
        <div class="col-4">
          <p class="text-muted font-15 mb-1 text-truncate">Last week</p>
          <h4>{{ currency }}423</h4>
        </div>
        <div class="col-4">
          <p class="text-muted font-15 mb-1 text-truncate">Last Month</p>
          <h4>{{ currency }}806</h4>
        </div>
      </div>
    </div>
  </div>
</div>
