// Minton_v10.1.0/Next.js/JS/src/app/(admin)/dashboard/crm/Statistics.jsx
"use client";

import React from "react";

// component
import StatisticsWidget from "@/components/StatisticsWidget";
const Statistics = () => {
  return <>
      <div className="row">
        <div className="col-xl-3 col-md-6">
          <StatisticsWidget icon="ri-stack-line" stats="865" title="Campaign Sent" trend={{
          value: "5.27%",
          title: "Since last month",
          icon: "mdi mdi-arrow-up-bold",
          variant: "success"
        }} />
        </div>
        <div className="col-xl-3 col-md-6">
          <StatisticsWidget icon="ri-slideshow-2-line" stats="384" title="New Leads" trend={{
          value: "3.27%",
          title: "Since last month",
          icon: "mdi mdi-arrow-down-bold",
          variant: "danger"
        }} />
        </div>
        <div className="col-xl-3 col-md-6">
          <StatisticsWidget icon="ri-hand-heart-line" stats="34521" title="Deals" trend={{
          value: "8.58%",
          title: "Since last month",
          icon: "mdi mdi-arrow-up-bold",
          variant: "success"
        }} />
        </div>
        <div className="col-xl-3 col-md-6">
          <StatisticsWidget icon="ri-money-dollar-box-line" stats="89357" title="Booked Revenue" counterOptions={{
          prefix: "$"
        }} trend={{
          value: "34.61%",
          title: "Since last month",
          icon: "mdi mdi-arrow-up-bold",
          variant: "success"
        }} />
        </div>
      </div>
    </>;
};
export default Statistics;

// Minton_v10.1.0/Angular/Minton/src/app/views/dashboard/crm/components/statistics/statistics.component.ts
import { Component } from '@angular/core'
import { StatisticsWidgetComponent } from '@component/statistics-widget/statistics-widget.component'

@Component({
  selector: 'crm-statistics',
  standalone: true,
  imports: [StatisticsWidgetComponent],
  templateUrl: './statistics.component.html',
  styles: ``,
})
export class StatisticsComponent {}

<div class="row">
  <div class="col-xl-3 col-md-6">
    <app-statistics-widget
      title="Campaign Sent"
      [stats]="865"
      [counterOptions]="{ startVal: '0' }"
      [trend]="{
        value: '5.27%',
        title: 'Since last month',
        icon: 'mdi mdi-arrow-up-bold',
        variant: 'success',
      }"
      icon="ri-stack-line"
    />
  </div>

  <div class="col-xl-3 col-md-6">
    <app-statistics-widget
      title="New Leads"
      [stats]="384"
      [counterOptions]="{ startVal: '0' }"
      [trend]="{
        value: '3.27%',
        title: 'Since last month',
        icon: 'mdi mdi-arrow-down-bold',
        variant: 'danger',
      }"
      icon="ri-slideshow-2-line"
    />
  </div>

  <div class="col-xl-3 col-md-6">
    <app-statistics-widget
      title="Deals"
      [stats]="34521"
      [counterOptions]="{ startVal: '0' }"
      [trend]="{
        value: '8.58%',
        title: 'Since last month',
        icon: 'mdi mdi-arrow-up-bold',
        variant: 'success',
      }"
      icon="ri-hand-heart-line"
    />
  </div>

  <div class="col-xl-3 col-md-6">
    <app-statistics-widget
      title="Booked Revenue"
      [stats]="89357"
      [counterOptions]="{ startVal: '0', prefix: '$' }"
      [trend]="{
        value: '34.61%',
        title: 'Since last month',
        icon: 'mdi mdi-arrow-up-bold',
        variant: 'success',
      }"
      icon="ri-money-dollar-box-line"
    />
  </div>
</div>
