// Minton_v10.1.0/Angular/Minton/src/app/views/base-ui/buttons/buttons.component.ts
import { Component } from '@angular/core'
import { PageTitleComponent } from '@component/page-title.component'
import { NgbDropdownModule } from '@ng-bootstrap/ng-bootstrap'

@Component({
  selector: 'app-buttons',
  standalone: true,
  imports: [PageTitleComponent, NgbDropdownModule],
  templateUrl: './buttons.component.html',
  styles: ``,
})
export class ButtonsComponent {
  breadCrumbItems = [
    { label: 'Base UI', path: '/ui/buttons' },
    { label: 'Buttons', path: '/ui/buttons', active: true },
  ]
}

// Minton_v10.1.0/React.js/JS/src/app/(admin)/ui/buttons/page.jsx
import PageBreadcrumb from "@/components/PageBreadcrumb";
import AllButtons from "./AllButtons";
import React from "react";
const Buttons = () => {
  return <React.Fragment>
      <PageBreadcrumb breadCrumbItems={[{
      label: "Base UI",
      path: "/ui/buttons"
    }, {
      label: "Buttons",
      path: "/ui/buttons",
      active: true
    }]} title={"Buttons"} />

      <AllButtons />
    </React.Fragment>;
};
export default Buttons;
