// Minton_v10.1.0/Angular/Minton/src/app/views/base-ui/portlets/portlets.component.ts
import { Component } from '@angular/core'
import { CustomCardPortletComponent } from '@component/custom-card-portlet/custom-card-portlet.component'
import { PageTitleComponent } from '@component/page-title.component'

@Component({
  selector: 'app-portlets',
  standalone: true,
  imports: [PageTitleComponent, CustomCardPortletComponent],
  templateUrl: './portlets.component.html',
  styles: ``,
})
export class PortletsComponent {
  breadCrumbItems = [
    { label: 'Base UI', path: '/ui/portlets' },
    { label: 'Portlets', path: '/ui/portlets', active: true },
  ]
}

<app-page-title title="Portlets" [breadCrumbItems]="breadCrumbItems" />

<div class="row">
  <div class="col-lg-4">
    <custom-card-portlet cardTitle="Card title" cardTitleClass="card-title">
      Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry
      richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard
      dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf
      moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla
      assumenda shoreditch et.
    </custom-card-portlet>
  </div>

  <div class="col-lg-4">
    <custom-card-portlet
      cardTitle="Card title"
      cardClass="bg-primary text-white"
      cardTitleClass="card-title text-white"
    >
      Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry
      richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard
      dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf
      moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla
      assumenda shoreditch et.
    </custom-card-portlet>
  </div>

  <div class="col-lg-4">
    <custom-card-portlet
      cardTitle="Card title"
      cardClass="bg-success text-white"
      cardTitleClass="card-title text-white"
    >
      Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry
      richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard
      dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf
      moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla
      assumenda shoreditch et.
    </custom-card-portlet>
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <custom-card-portlet
      cardTitle="Card title"
      headerClass="card-header bg-danger py-3 text-white"
      cardTitleClass="card-title text-white"
    >
      <div class="card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
        terry richardson ad squid. 3 wolf moon officia aute, non cupidatat
        skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.
        Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid
        single-origin coffee nulla assumenda shoreditch et.
      </div>
    </custom-card-portlet>
  </div>

  <div class="col-lg-4">
    <custom-card-portlet
      cardTitle="Card title"
      headerClass="card-header bg-purple py-3 text-white"
      cardTitleClass="card-title text-white"
    >
      <div class="card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
        terry richardson ad squid. 3 wolf moon officia aute, non cupidatat
        skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.
        Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid
        single-origin coffee nulla assumenda shoreditch et.
      </div>
    </custom-card-portlet>
  </div>

  <div class="col-lg-4">
    <custom-card-portlet
      cardTitle="Card title"
      headerClass="card-header bg-warning py-3 text-white"
      cardTitleClass="card-title text-white"
    >
      <div class="card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
        terry richardson ad squid. 3 wolf moon officia aute, non cupidatat
        skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.
        Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid
        single-origin coffee nulla assumenda shoreditch et.
      </div>
    </custom-card-portlet>
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <custom-card-portlet
      cardTitle="Card title"
      headerClass="card-header bg-info py-3 text-white"
      cardTitleClass="card-title text-white"
    >
      <div class="card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
        terry richardson ad squid. 3 wolf moon officia aute, non cupidatat
        skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.
        Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid
        single-origin coffee nulla assumenda shoreditch et.
      </div>
    </custom-card-portlet>
  </div>

  <div class="col-lg-4">
    <custom-card-portlet
      cardTitle="Card title"
      headerClass="card-header bg-dark py-3 text-white"
      cardTitleClass="card-title text-white"
    >
      <div class="card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
        terry richardson ad squid. 3 wolf moon officia aute, non cupidatat
        skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.
        Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid
        single-origin coffee nulla assumenda shoreditch et.
      </div>
    </custom-card-portlet>
  </div>

  <div class="col-lg-4">
    <custom-card-portlet
      cardTitle="Card title"
      headerClass="card-header bg-pink py-3 text-white"
      cardTitleClass="card-title text-white"
    >
      <div class="card-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus
        terry richardson ad squid. 3 wolf moon officia aute, non cupidatat
        skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.
        Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid
        single-origin coffee nulla assumenda shoreditch et.
      </div>
    </custom-card-portlet>
  </div>
</div>

// Minton_v10.1.0/React.js/TS/src/app/(admin)/ui/portlets/page.tsx

import classNames from "classnames";


import PortletWithHeader from '@/components/Portlet'
import BasicPortlet from '@/components/BasicPortlet'

// components
import PageBreadcrumb from "@/components/PageBreadcrumb";
import { Col, Row } from "react-bootstrap";

const Portlets = () => {
  const headerVariant = ["danger", "purple", "warning", "info", "dark", "pink"];
  return (
    <>
      <PageBreadcrumb
        breadCrumbItems={[
          { label: "Base UI", path: "/ui/portlets" },
          { label: "Portlets", path: "/ui/portlets", active: true },
        ]}
        title={"Portlets"}
      />

      <Row>
        <Col lg={4}>
          <BasicPortlet titleClass="card-title" cardTitle="Card title">
            <div>
              Anim pariatur cliche reprehenderit, enim eiusmod high life
              accusamus terry richardson ad squid. 3 wolf moon officia aute, non
              cupidatat skateboard dolor brunch. Food truck quinoa nesciunt
              laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird
              on it squid single-origin coffee nulla assumenda shoreditch et.
            </div>
          </BasicPortlet>
        </Col>
        <Col lg={4}>
          <BasicPortlet
            className="bg-primary text-white"
            cardTitle="Card title"
            titleClass="card-title text-white"
          >
            <div>
              Anim pariatur cliche reprehenderit, enim eiusmod high life
              accusamus terry richardson ad squid. 3 wolf moon officia aute, non
              cupidatat skateboard dolor brunch. Food truck quinoa nesciunt
              laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird
              on it squid single-origin coffee nulla assumenda shoreditch et.
            </div>
          </BasicPortlet>
        </Col>
        <Col lg={4}>
          <BasicPortlet
            className="bg-success text-white"
            cardTitle="Card title"
            titleClass="card-title text-white"
          >
            <div>
              Anim pariatur cliche reprehenderit, enim eiusmod high life
              accusamus terry richardson ad squid. 3 wolf moon officia aute, non
              cupidatat skateboard dolor brunch. Food truck quinoa nesciunt
              laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird
              on it squid single-origin coffee nulla assumenda shoreditch et.
            </div>
          </BasicPortlet>
        </Col>
      </Row>

      <Row>
        {(headerVariant || []).map((item, index) => {
          return (
            <Col lg={4} key={index}>
              <PortletWithHeader
                cardTitle="Card title"
                headerClass={classNames("py-3 text-white", "bg-" + item)}
                titleClass="card-title text-white"
              >
                <div>
                  Anim pariatur cliche reprehenderit, enim eiusmod high life
                  accusamus terry richardson ad squid. 3 wolf moon officia aute,
                  non cupidatat skateboard dolor brunch. Food truck quinoa
                  nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt
                  aliqua put a bird on it squid single-origin coffee nulla
                  assumenda shoreditch et.
                </div>
              </PortletWithHeader>
            </Col>
          );
        })}
      </Row>
    </>
  );
};

export default Portlets;
